### ISSUE TITLE
Same as #570 that was closed, error on Windows import mxnet

### ISSUE THREAD

**Issue by PinkhamCreeker** [dmlc/mxnet#1058]
Having the same problem.  Windows 7,64, Anaconda, Python 2.7.11
Tried the above fixes, still same error.

import mxnet as mx
Traceback (most recent call last):

  File "<ipython-input-8-cb88d04c42ec>", line 1, in <module>
    import mxnet as mx

  File "G:\dm\Anaconda2016\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError

  File "G:\dm\Anaconda2016\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 10, in <module>
    from . import libinfo

ImportError: cannot import name libinfo

**Comment by lancerts** [comment]
Same error in win 7 here. wait for solution
