### ISSUE TITLE
OSError: libcudart.so.7.5: cannot open shared object file

### ISSUE THREAD

**Issue by zhiplain** [dmlc/mxnet#1081]
Hi：

wm@wm:~/mxnet/example/image-classification$ sudo python train_mnist.py
[sudo] password for wm:
Traceback (most recent call last):
File "train_mnist.py", line 1, in <module>
import find_mxnet
File "/home/wm/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
import mxnet as mx
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
from .base import MXNetError
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
_LIB = _load_lib()
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory
wm@wm:~/mxnet/example/image-classification$ sudo python train_imagenet.py
Traceback (most recent call last):
File "train_imagenet.py", line 1, in <module>
import find_mxnet
File "/home/wm/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
import mxnet as mx
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
from .base import MXNetError
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
_LIB = _load_lib()
File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory
wm@wm:~/mxnet/example/image-classification$

**Comment by piiswrong** [comment]
did you install cuda? Is it in LD_LIBRARY_PATH?

**Comment by zhiplain** [comment]
cuda is installed. 

export CUDA_HOME=/usr/local/cuda-7.5
export LD_LIBRARY_PATH=${CUDA_HOME}/lib64 
PATH=${CUDA_HOME}/bin:${PATH} 
export PATH

is added in ~/.profile.

**Comment by zhiplain** [comment]
I have modify 
USE_CUDA_PATH = /usr/local/cuda-7.5 
ADD_CFLAGS =-I/usr/local/cuda-6.5/bin

as 

USE_CUDA_PATH = /usr/local/cuda 
ADD_CFLAGS =

now, it works。

thanks!
