### ISSUE TITLE
error in running train_cifar10.py

### ISSUE THREAD

**Issue by kaishijeng** [dmlc/mxnet#1106]
I can run python train_mnist.py OK. But when i run train_cifar10.py with the following command (I don't have a graphic card) and encountered the error below:
   python train_cifar10.py --gpus -1

2015-12-29 09:36:40,950 Node[0] start with arguments Namespace(batch_size=128, data_dir='cifar10/', gpus='-1', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=60000)
[09:36:40] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/train.rec, use 3 threads for decoding..
[09:36:40] src/io/./iter_normalize.h:103: Load mean image from cifar10/mean.bin
[09:36:41] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/test.rec, use 3 threads for decoding..
[09:36:41] src/io/./iter_normalize.h:103: Load mean image from cifar10/mean.bin
2015-12-29 09:36:41,174 Node[0] Start training with [gpu(-1)]
[09:36:41] ./dmlc-core/include/dmlc/././logging.h:208: [09:36:41] src/storage/../common/lazy_alloc_array.h:54: Check failed: (index) >= (0)
Traceback (most recent call last):
  File "train_cifar10.py", line 79, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/henry/src/mxnet/example/image-classification/train_model.py", line 84, in fit
    epoch_end_callback = checkpoint)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 655, in fit
    logger=logger, work_load_list=work_load_list, monitor=monitor)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 187, in _train_multi_device
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor.py", line 349, in __init__
    train_exec = symbol.simple_bind(ctx[i], 'write', **data_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 523, in simple_bind
    arg_ndarrays = [zeros(shape, ctx) for shape in arg_shapes]
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 428, in zeros

**Comment by lukemetz** [comment]
The problem is this line here:
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L47
the string -1 does not trigger the gpu case.

The mnist example has no default listed for gpu (https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_mnist.py#L13) and thus is run with the cpu.

The cifar example does have a default given. (https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_cifar10.py#L12). To make it run on a cpu you can just remove the default="0" line.

**Comment by mli** [comment]
you can use `--gpus None`, but i guess cpu could be very slow since we used a more complex model for cifar10 comparing to mnist

**Comment by kaishijeng** [comment]
It works by removing default="0"
