### ISSUE TITLE
python metric strings other than accuracy?

### ISSUE THREAD

**Issue by jmschrei** [dmlc/mxnet#1107]
The code for create in metric.py doesn't seem to allow strings to be used for metrics other than accuracy. It checks to see if the type is a string, and if so, checks to see if it's accuracy, and if not, raises an error.

```
def create(metric):
    """Create an evaluation metric.
    Parameters
    ----------
    metric : str or callable
        The name of the metric, or a function
        providing statistics given pred, label NDArray.
    """
    if callable(metric):
        return CustomMetric(metric)
    if not isinstance(metric, string_types):
        raise TypeError('metric should either be callable or str')
    if metric == 'acc' or metric == 'accuracy':
        return Accuracy()
    else:
        raise ValueError('Cannot find metric %s' % metric)
```

**Comment by jmschrei** [comment]
If I pass in mx.metric.RMSE to eval_metric in fit, I get the following error:

```
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
Traceback (most recent call last):
  File "ananas.py", line 75, in <module>
    main()
  File "ananas.py", line 68, in main
    batch_end_callback=mx.callback.Speedometer(batch_size)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 655, in fit
    logger=logger, work_load_list=work_load_list, monitor=monitor)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 241, in _train_multi_device
    eval_metric.update(data_batch.label, executor_manager.cpu_output_arrays)
  File "/net/noble/vol1/home/jmschr/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/metric.py", line 108, in update
    self.sum_metric += self._feval(label, pred)
TypeError: __init__() takes exactly 1 argument (3 given)
```

Same if I pass in mx.metric.MAE. This error is coming from CustomMetric which doesn't make sense to me. Here is my full code:

```
def Convolution( data, num_filter, kernel, stride=(1,1), pad=(0,0), name=None, suffix='' ):
	"""Create a convolution layer with batch normalization and relu activations."""

	conv = mx.symbol.Convolution( data=data, num_filter=num_filter, kernel=kernel, stride=stride, pad=pad, name='conv_{}{}'.format( name, suffix ) )
	bn = mx.symbol.BatchNorm( data=conv, name='bn_{}{}'.format( name, suffix ) )
	act = mx.symbol.Activation( data=bn, act_type='relu', name='relu_{}{}'.format( name, suffix ) )
	return act

def InnerProduct( data, num_hidden, name=None, suffix='', weight=None, bias=None ):
	"""Create an inner product layer with ReLU activations."""

	ip = mx.symbol.FullyConnected( data=data, num_hidden=num_hidden )
	act = mx.symbol.LeakyReLU( data=ip, act_type='prelu', name="relu_{}{}".format( name, suffix ) )
	return act


def main():
	X_train = numpy.load( '../data/X_train.npy' )
	y_train = numpy.load( '../data/y_train.npy' )

	X_test = numpy.load( '../data/X_test.npy' )
	y_test = numpy.load( '../data/y_test.npy' )

	print X_train.shape
	print y_train.shape
	print y_train.max()

	batch_size = 256

	sequence = mx.symbol.Variable( name='data' )
	conv1 = Convolution( sequence, 16, (5, 4), stride=(1, 1), name="conv1" )
	conv2 = Convolution( conv1, 16, (5, 1), stride=(1, 1), name="conv2" )
	conv3 = Convolution( conv2, 32, (5, 1), stride=(1, 1), name="conv3" )

	mp = mx.symbol.Pooling( conv3, kernel=(110, 1), pool_type='max', name="mp" )
	flatten = mx.symbol.Flatten( mp )

	ip1 = InnerProduct( flatten, 256, name="ip1" )
	ip2 = InnerProduct( ip1, 256, name="ip2" )
	ip3 = mx.symbol.FullyConnected( data=ip2, num_hidden=1, name="y" )

	y = mx.symbol.LinearRegressionOutput( data=ip3, name="y" )

	train_data  = mx.io.NDArrayIter( X_train, label={ 'y_label' : y_train }, batch_size=batch_size )
	eval_data   = mx.io.NDArrayIter( X_test,  label={ 'y_label' : y_test }, batch_size=batch_size )

	model = mx.model.FeedForward( ctx=[ mx.gpu(0), mx.gpu(1), mx.gpu(2), mx.gpu(3) ], 
							      symbol=y,
							      num_epoch=2,
							      learning_rate=0.00001,
							      wd=0.1,
							      optimizer='adam',
							    )
	model.fit( X=train_data, 
			   eval_data=eval_data, 
			   eval_metric=mx.metric.RMSE,
			   batch_end_callback=mx.callback.Speedometer(batch_size)
			 )
```

**Comment by jmschrei** [comment]
I can't find where LinearRegressionOutput or SoftmaxOutput are in the python repo. Can someone point me in that direction so I can fully understand how they work?

**Comment by jmschrei** [comment]
As a last note, when I train this model, I get the following for the first few epochs:

```
INFO:root:Auto-select kvstore type = local_update_cpu
INFO:root:Start training with [gpu(0), gpu(1), gpu(2), gpu(3)]
INFO:root:Iter[0] Batch [50]	Speed: 1271.76 samples/sec
INFO:root:Epoch[0] Train-accuracy=0.426018
INFO:root:Epoch[0] Time cost=13.799
INFO:root:Iter[1] Batch [50]	Speed: 1271.65 samples/sec
INFO:root:Epoch[1] Train-accuracy=0.426018
INFO:root:Epoch[1] Time cost=13.548
```

Why is it using accuracy as the metric if I'm using a LinearRegressionOutput? Is it calculating the gradient using MSE but then using a secondary accuracy metric? How do I get it to display a more appropriate metric?

**Comment by tqchen** [comment]
Currently the default metric do not come together with the objective used, so metric need to be manually specified in the fit method. We can however, support some automatic decision of metric

**Comment by jmschrei** [comment]
Manually specifying a metric other than accuracy doesn't seem to work. See the above errors.

**Comment by tqchen** [comment]
It should be ```metric.RMSE()```, with function invokation to create metric object, sorry for the confusion

**Comment by jmschrei** [comment]
Was the original issue resolved?
