### ISSUE TITLE
Installed CPU version only, but asks for GPU enabled compilation while running

### ISSUE THREAD

**Issue by UdayaBhanuG** [dmlc/mxnet#1121]
I installed CPU version of mxnet on Windows, and installed python using setup.py. I am using python 2.7. When training the model, I am getting the following error:

OpenCV is unavailable.
INFO:root:Start training with [gpu(0)]
[10:13:08] D:\chhong\mxnet\dmlc-core\include\dmlc/logging.h:208: [10:13:08] D:\chhong\mxnet\src\storage\storage.cc:44: Please compile with CUDA enabled
Traceback (most recent call last):
  File "Train.py", line 97, in <module>
    stytole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS))
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\model.py", line 655, in fit
    logger=logger, work_load_list=work_load_list, monitor=monitor)
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\model.py", line 187, in _train_multi_device
    logger=logger)
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\executor.py", line 349, in __init__
    train_exec = symbol.simple_bind(ctx[i], 'write', **data_shapes)
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\symbol.py", line 523, in simple_bind
    arg_ndarrays = [zeros(shape, ctx) for shape in arg_shapes]
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\ndarray.py", line 428, in zeros
    arr = empty(shape, ctx)
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\ndarray.py", line 411, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False))
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\ndarray.py", line 45, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "C:\Anaconda\lib\site-packages\mxnet-0.5.0-py2.7.egg\mxnet\base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [10:13:08] D:\chhong\mxnet\src\storage\storage.cc:44: Please compile with CUDA enabled

**Comment by piiswrong** [comment]
`INFO:root:Start training with [gpu(0)]`
you trying to use gpu. change it to mx.cpu() instead.
