### ISSUE TITLE
train_mnist.py fails once I switch on CUDA

### ISSUE THREAD

**Issue by colinpriest** [dmlc/mxnet#1174]
I'm a newby to linux. So sorry if this is a newby question. Can you help with the following?

train_mnist.py works when I compile with USE_CUDA = 0
But when I compile with USE_CUDA = 1, I get the following error:

Traceback (most recent call last):
  File "mxnet/example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/colin/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/base.py", line 34, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/libinfo.py", line 33, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
/home/colin/mxnet/python/mxnet/libmxnet.so
/home/colin/mxnet/python/mxnet/../../lib/libmxnet.so

**Comment by piiswrong** [comment]
did you do make clean_all after switching to USE_CUDA=1?

**Comment by colinpriest** [comment]
Sorry but that doesn't fix it.

Traceback (most recent call last):
  File "mxnet/example/image-classification/train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/colin/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/colin/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.5: cannot open shared object file: No such file or directory

**Comment by tornadomeet** [comment]
you should configure the USE_CUDA_PATH=$YOUR_PATH in the config.mk

**Comment by colinpriest** [comment]
Sorry but I am a newby. What path should that be?

When I tried USE_CUDA_PATH = /usr/local/cuda it compiles, but gives the run time error listed above. The same happens for USE_CUDA_PATH = /usr/local/cuda-7.5
When I tried USE_CUDA_PATH = ~/mxnet/cuda I get the compilation error shown below:

/bin/sh: 1: /home/colin/mxnet/cuda/bin/nvcc: not found
Makefile:134: recipe for target 'build/ndarray/unary_function_gpu.o' failed
make: *** [build/ndarray/unary_function_gpu.o] Error 127

**Comment by piiswrong** [comment]
run `export LD_LIBRARY_PATH=/usr/local/cuda/lib64`

**Comment by colinpriest** [comment]
Thanks. That fixed it!
