### ISSUE TITLE
Train cifar error: Unknown type enum

### ISSUE THREAD

**Issue by zhoubinxyz** [dmlc/mxnet#1224]
zhoub@zhoub-desktop:~/Software/mxnet/example/image-classification$ python train_cifar10.py 
OpenCV is unavailable.
2016-01-10 01:02:56,483 Node[0] start with arguments Namespace(batch_size=128, data_dir='cifar10/', gpus='0', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=60000)
--2016-01-10 01:02:56--  http://webdocs.cs.ualberta.ca/~bx3/data/cifar10.zip
Resolving webdocs.cs.ualberta.ca (webdocs.cs.ualberta.ca)... 129.128.184.6
Connecting to webdocs.cs.ualberta.ca (webdocs.cs.ualberta.ca)|129.128.184.6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133801102 (128M) [application/zip]
Saving to: ‘cifar10.zip’

cifar10.zip                                         100%[==================================================================================================================>] 127.60M  3.71MB/s   in 37s    

2016-01-10 01:03:34 (3.42 MB/s) - ‘cifar10.zip’ saved [133801102/133801102]

Archive:  cifar10.zip
   creating: cifar/
  inflating: cifar/train.lst         
  inflating: cifar/test.rec          
  inflating: cifar/train.rec         
  inflating: cifar/test.lst          
[01:03:35] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/train.rec, use 3 threads for decoding..
[01:03:35] src/io/./iter_normalize.h:218: Cannot find cifar10/mean.bin: create mean image, this will take some time...
[01:03:35] src/io/./iter_normalize.h:231: 10000 images processed, 0.262767 sec elapsed
[01:03:35] src/io/./iter_normalize.h:231: 20000 images processed, 0.467821 sec elapsed
[01:03:36] src/io/./iter_normalize.h:231: 30000 images processed, 0.675504 sec elapsed
[01:03:36] src/io/./iter_normalize.h:231: 40000 images processed, 0.823375 sec elapsed
[01:03:36] src/io/./iter_normalize.h:231: 50000 images processed, 1.00545 sec elapsed
[01:03:36] ./dmlc-core/include/dmlc/logging.h:208: [01:03:36] include/mxnet/./ndarray.h:69: Unknown type enum 891877532
Traceback (most recent call last):
  File "train_cifar10.py", line 79, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/zhoub/Software/mxnet/example/image-classification/train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_cifar10.py", line 64, in get_iterator
    part_index  = kv.rank)
  File "/home/zhoub/Software/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/io.py", line 508, in creator
    ctypes.byref(iter_handle)))
  File "/home/zhoub/Software/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [01:03:36] include/mxnet/./ndarray.h:69: Unknown type enum 891877532

**Comment by eule710** [comment]
get the same error after re-installation

**Comment by zhoubinxyz** [comment]
The cause is the newest updates on ndarray.h:69:

inline TBlob data() const {
MSHADOW_TYPE_SWITCH(dtype_, DType, {
return TBlob(static_cast<DType*>(ptr_->shandle.dptr)
 + offset_, shape_, ptr_->shandle.ctx.dev_mask());
});
return TBlob();
}


Correct it back to:
  inline TBlob data() const {
	return TBlob(static_cast<real_t*>(ptr_->shandle.dptr) + offset_, \
		shape_, ptr_->shandle.ctx.dev_mask());
  }

and recompile will solve the problem.

**Comment by piiswrong** [comment]
fixed by https://github.com/dmlc/mxnet/pull/1227
Please pull the change, remake, remove cifar10/mean.bin, and try again.
Thanks for reporting this bug.
