### ISSUE TITLE
Cannot get cifar10 example to run on OSX 10.10.5

### ISSUE THREAD

**Issue by ieee8023** [dmlc/mxnet#1226]
Any ideas? Installed opencv with macports (homebrew wasn't working) and it is accepted by the makefile but it still complains here and then gives me this NDArray error. I have cuda 7.5 installed on OSX 10.10.5.

[config.mk.txt](https://github.com/dmlc/mxnet/files/83791/config.mk.txt)
[build-log.txt](https://github.com/dmlc/mxnet/files/83793/build-log.txt)

$ python train_cifar10.py 
OpenCV is unavailable.
2016-01-09 13:32:38,028 Node[0] start with arguments Namespace(batch_size=128, data_dir='cifar10/', gpus='0', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=60000)
[13:32:38] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/train.rec, use 1 threads for decoding..
[13:32:38] src/io/./iter_normalize.h:103: Load mean image from cifar10/mean.bin
[13:32:38] ./dmlc-core/include/dmlc/logging.h:208: [13:32:38] src/ndarray/ndarray.cc:525: Check failed: fi->Read(data) Invalid NDArray file format
Traceback (most recent call last):
  File "train_cifar10.py", line 79, in <module>
    train_model.fit(args, net, get_iterator)
  File "/Users/ieee8023/git/mxnet/example/image-classification/train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_cifar10.py", line 64, in get_iterator
    part_index  = kv.rank)
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/io.py", line 508, in creator
    ctypes.byref(iter_handle)))
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:32:38] src/ndarray/ndarray.cc:525: Check failed: fi->Read(data) Invalid NDArray file format

**Comment by piiswrong** [comment]
How did you prepare your cifar10/train.rec? Looks like it's corrupt.

**Comment by ieee8023** [comment]
I used the method built into the script. I get a `Unknown type enum 2054988040` error

```
$ python train_cifar10.py 
OpenCV is unavailable.
2016-01-09 15:10:49,338 Node[0] start with arguments Namespace(batch_size=128, data_dir='cifar10/', gpus='0', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=60000)
--2016-01-09 15:10:49--  http://webdocs.cs.ualberta.ca/~bx3/data/cifar10.zip
Resolving webdocs.cs.ualberta.ca... 129.128.184.6
Connecting to webdocs.cs.ualberta.ca|129.128.184.6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 133801102 (128M) [application/zip]
Saving to: 'cifar10.zip'

cifar10.zip                                       100%[============================================================================================================>] 127.60M  1.18MB/s   in 83s    

2016-01-09 15:12:13 (1.53 MB/s) - 'cifar10.zip' saved [133801102/133801102]

Archive:  cifar10.zip
   creating: cifar/
  inflating: cifar/train.lst         
  inflating: cifar/test.rec          
  inflating: cifar/train.rec         
  inflating: cifar/test.lst          
[15:12:14] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/train.rec, use 1 threads for decoding..
[15:12:14] src/io/./iter_normalize.h:218: Cannot find cifar10/mean.bin: create mean image, this will take some time...
[15:12:15] src/io/./iter_normalize.h:231: 10000 images processed, 0.849488 sec elapsed
[15:12:15] src/io/./iter_normalize.h:231: 20000 images processed, 1.59063 sec elapsed
[15:12:16] src/io/./iter_normalize.h:231: 30000 images processed, 2.3141 sec elapsed
[15:12:17] src/io/./iter_normalize.h:231: 40000 images processed, 2.82893 sec elapsed
[15:12:17] src/io/./iter_normalize.h:231: 50000 images processed, 3.46245 sec elapsed
[15:12:17] ./dmlc-core/include/dmlc/logging.h:208: [15:12:17] include/mxnet/ndarray.h:69: Unknown type enum 2054988040
Traceback (most recent call last):
  File "train_cifar10.py", line 79, in <module>
    train_model.fit(args, net, get_iterator)
  File "/Users/ieee8023/git/mxnet/example/image-classification/train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_cifar10.py", line 64, in get_iterator
    part_index  = kv.rank)
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/io.py", line 508, in creator
    ctypes.byref(iter_handle)))
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:12:17] include/mxnet/ndarray.h:69: Unknown type enum 2054988040
```

Then I run it again
```
$ python train_cifar10.py 
OpenCV is unavailable.
2016-01-09 15:12:29,708 Node[0] start with arguments Namespace(batch_size=128, data_dir='cifar10/', gpus='0', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=60000)
[15:12:29] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: cifar10/train.rec, use 1 threads for decoding..
[15:12:29] src/io/./iter_normalize.h:103: Load mean image from cifar10/mean.bin
[15:12:29] ./dmlc-core/include/dmlc/logging.h:208: [15:12:29] src/ndarray/ndarray.cc:525: Check failed: fi->Read(data) Invalid NDArray file format
Traceback (most recent call last):
  File "train_cifar10.py", line 79, in <module>
    train_model.fit(args, net, get_iterator)
  File "/Users/ieee8023/git/mxnet/example/image-classification/train_model.py", line 44, in fit
    (train, val) = data_loader(args, kv)
  File "train_cifar10.py", line 64, in get_iterator
    part_index  = kv.rank)
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/io.py", line 508, in creator
    ctypes.byref(iter_handle)))
  File "/Users/ieee8023/git/mxnet/example/image-classification/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:12:29] src/ndarray/ndarray.cc:525: Check failed: fi->Read(data) Invalid NDArray file format
```

**Comment by piiswrong** [comment]
please refer to https://github.com/dmlc/mxnet/issues/1224
