### ISSUE TITLE
no libmxnet.so file after building

### ISSUE THREAD

**Issue by JunWorks** [dmlc/mxnet#1234]
Hi,

I am on OS X 10.10.5. I was able to build and install mxnet (both python and R)with USE_CUDA = 0 successfully. However, when I try to build and install mxnet with USE_CUDA = 1 (GPU gtx 960), I got the following error:
```
RuntimeError: Cannot find the files.
List of candidates:
/Users/Jun/mxnet/python/mxnet/libmxnet.so
```
I could not find libmxnet.so in mxnet/python/mxnet/.

Here are some details of compiling:
in config.mk
```
ADD_LDFLAGS = -I/usr/local/opt/openblas/lib -I/Developer/NVIDIA/CUDA-7.5/lib
ADD_CFLAGS = -I/usr/local/opt/openblas/include -I/Developer/NVIDIA/CUDA-7.5/include
USE_CUDA_PATH = /Developer/NVIDIA/CUDA-7.5
```
in terminal:
```
export PATH=/Developer/NVIDIA/CUDA-7.5/bin:$PATH
export DYLD_LIBRARY_PATH=/Developer/NVIDIA/CUDA-7.5/lib:$DYLD_LIBRARY_PATH
```
also used 
```
make clean_all
```
after above modifications, I was able to compile using gpu with no error, but warnings like: warning: 
```
‘dmlc::__make_ParserFactoryReg_uint32_t_csv__’ defined but not used [-Wunused-variable]
   static EntryType & __make_ ## EntryTypeName ## _ ## Name ## __ =      \
```

Then I run python setup.py install, I got:
```
RuntimeError: Cannot find the files.
List of candidates:
/Users/Jun/mxnet/python/mxnet/libmxnet.so
```

Any idea? 

I am sorry for the long post, but I searched web, and tried https://github.com/dmlc/mxnet/issues/1174 with no luck. Thank you very much!

**Comment by piiswrong** [comment]
Looks like your build failed.

**Comment by JunWorks** [comment]
I will check again. Thanks for the suggestion.

**Comment by mndrake** [comment]
I was unable to build in OS X with gnu, but could for cpu. I did not set:
```
ADD_LDFLAGS = -I/usr/local/opt/openblas/lib -I/Developer/NVIDIA/CUDA-7.5/lib
ADD_CFLAGS = -I/usr/local/opt/openblas/include -I/Developer/NVIDIA/CUDA-7.5/include
```
but did set:
```
USE_CUDA = 1
USE_CUDA_PATH=/usr/local/cuda
```
After that I received a warning about `/usr/local/cuda/lib64` missing. This directory does not exist in the OS X installation of the cuda toolkit. For a workaround I created a soft link `/usr/local/cuda/lib64 -> /usr/local/cuda/lib` and then was able to build with gpu enabled.

**Comment by JunWorks** [comment]
@mndrake Thanks for your info.

@piiswrong I build it again, and saw this error (sorry I missed it at the first place):
```
nvcc fatal   : GNU C/C++ compiler is no longer supported as a host compiler on Mac OS X.
```
This problem might be related: https://devtalk.nvidia.com/default/topic/879431/cuda-programming-and-performance/nvcc-amp-clang-7-no-typo-here-/ although I can successfully build cuda samples.

I am downgrading Xcode now to check the solutions and will update this thread. Thank you all.

**Comment by JunWorks** [comment]
Was able to build mxnet after downgrading Xcode to 6.2. However the same issue https://github.com/dmlc/mxnet/issues/570 appears....I will update if I found a fix.

**Comment by JunWorks** [comment]
Sorry for another post, I am quite new with deep learning on gpu.

So I was able to train using gpu in OS X terminal:
```
python train_mnist.py --gpus 0
OpenCV is unavailable.
2016-01-11 19:46:51,725 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus='0', kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
[19:46:54] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[19:46:54] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
2016-01-11 19:46:54,750 Node[0] Start training with [gpu(0)]
2016-01-11 19:47:03,866 Node[0] Epoch[0] Batch [50]	Speed: 141320.50 samples/sec	Train-accuracy=0.700469
2016-01-11 19:47:03,910 Node[0] Epoch[0] Batch [100]	Speed: 145289.52 samples/sec	Train-accuracy=0.796094
2016-01-11 19:47:03,964 Node[0] Epoch[0] Batch [150]	Speed: 120573.08 samples/sec	Train-accuracy=0.837656
2016-01-11 19:47:04,003 Node[0] Epoch[0] Batch [200]	Speed: 164006.17 samples/sec	Train-accuracy=0.863047
2016-01-11 19:47:04,060 Node[0] Epoch[0] Batch [250]	Speed: 111228.93 samples/sec	Train-accuracy=0.878719
2016-01-11 19:47:04,100 Node[0] Epoch[0] Batch [300]	Speed: 163265.02 samples/sec	Train-accuracy=0.889948
2016-01-11 19:47:04,146 Node[0] Epoch[0] Batch [350]	Speed: 139103.03 samples/sec	Train-accuracy=0.899196
2016-01-11 19:47:04,189 Node[0] Epoch[0] Batch [400]	Speed: 148079.44 samples/sec	Train-accuracy=0.905430
2016-01-11 19:47:04,238 Node[0] Epoch[0] Batch [450]	Speed: 132316.34 samples/sec	Train-accuracy=0.910295
2016-01-11 19:47:04,255 Node[0] Epoch[0] Train-accuracy=0.912059
```

However, still got the same error in python IDE. I am using anaconda and spyder. Any idea?

**Comment by sxjscience** [comment]
Maybe there are two python versions installed.

**Comment by JunWorks** [comment]
@sxjscience I also suspect it has something to do with python IDE, but can confirst only one installed on my machine, and one python version as well.

**Comment by qdzx** [comment]
Hi,I am on OS X 10.10.4.I installed mxnet with cpu only(have no gpu),however met the same error with you.Did you meet the same error with USE_CUDA = 0 ? I did not install cuda.

**Comment by wguo68** [comment]
I have the same problem:
ImportError                               Traceback (most recent call last)
<ipython-input-2-36f7894d9f39> in <module>()
----> 1 import mxnet as mx
      2 
      3 def to4d(img):
      4     return img.reshape(img.shape[0], 1, 28, 28).astype(np.float32)/255
      5 

/home/d/mxnet/python/mxnet/__init__.py in <module>()
      5 
      6 from .context import Context, current_context, cpu, gpu
----> 7 from .base import MXNetError
      8 from . import base
      9 from . import ndarray

/home/d/mxnet/python/mxnet/base.py in <module>()
      8 import atexit
      9 import numpy as np
---> 10 from . import libinfo
     11 
     12 __all__ = ['MXNetError']

ImportError: cannot import name libinfo

**Comment by happygds** [comment]
I got a similar problem:
```
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/lustre/home/eefxz/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/lustre/home/eefxz/mxnet/python/mxnet/base.py", line 12, in <module>
    from . import libinfo
ImportError: cannot import name libinfo
```
When I run `make -j2 && cd python && python setup.py install`, there is no error information raised by the machine.
Other information:
```
mxnet (has been updated to the latest)
cuda/8.0
cudnn/5.1
CentOS/7.3.1611
anaconda/2 (python 2.7.12)
mkl/11.3
```

Any ideas ?
