### ISSUE TITLE
Preprocessing.py failed with "ValueError: not enough values to unpack (expected 2, got 0)"

### ISSUE THREAD

**Issue by spimenov** [dmlc/mxnet#1235]
Python 3.5.1 with all related packages were finally successfully installed.
Twice downloaded data (in case if I missed something).
Replaced '/' with '\\' in Preprocessing.py
Preprocessing.py is in the same folder where data is located:

preprocessing.py
data
    train
    validation
    sample_submission_validate.csv
    train.csv

Run python preprocessing.py in cmd-windows in the same folder.
Always have error in about 4-5 seconds:

>python preprocessing.py
Traceback (most recent call last):
  File "preprocessing.py", line 139, in <module>
    train_lst = write_data_csv(".\\train-64x64-data.csv", train_frames, lambda x: crop_resize(x, 64))
  File "preprocessing.py", line 79, in write_data_csv
    data,result = zip(*dr)
ValueError: not enough values to unpack (expected 2, got 0)

'get_frames()' returns an empty list.
'       if all(x in fileset for x in expected):' - never happened.
There are file names in both 'fileset' and 'expected'; the are not the same but have intersections.
I inserted prints before the 'if'
       print("&: ", set(fileset) & set(expected))
       print("^: ", set(fileset) ^ set(expected))
got:

&:  {'IM-2396-0001-0003.dcm', 'IM-2396-0001-0009.dcm', 'IM-2396-0001-0004.dcm', 'IM-2396-0001-0001.dcm', 'IM-2396-0001-0008.dcm'
, 'IM-2396-0001-0007.dcm', 'IM-2396-0001-0006.dcm', 'IM-2396-0001-0005.dcm', 'IM-2396-0001-0002.dcm'}
^:  {'IM-2396-0013-0001.dcm', 'IM-2396-0015-0004.dcm', 'IM-2396-0010-0005.dcm', 'IM-2396-0004-0006.dcm', 'IM-2396-0026-0004.dcm'
, 'IM-2396-0025-0004.dcm', 'IM-2396-0004-0001.dcm', 'IM-2396-0007-0003.dcm', 'IM-2396-0003-0006.dcm', 'IM-2396-0022-0007.dcm', ' . . . 

Sorry, I'm not good in python...

**Comment by spimenov** [comment]
Sorry, it had to be:
"Replaced '/' with '\\\\' in Preprocessing.py"

**Comment by spimenov** [comment]
The fix is here:
https://www.kaggle.com/c/second-annual-data-science-bowl/forums/t/18079/end-to-end-deep-learning-tutorial-0-0392/103854#post103854
Also a fix for the next bug is there...
But never mind... too messy code to fix... :o(
