### ISSUE TITLE
How to enable CUDA

### ISSUE THREAD

**Issue by Shashidhar123** [dmlc/mxnet#1288]
Hi,
Just installed mxnet and tried to run code from example python train.py . Then I got the below error. I am using python 2.7 . Please help

OpenCV is unavailable.
INFO:root:Start training with [gpu(0)]
[23:59:16] ./dmlc-core/include/dmlc/././logging.h:215: [23:59:16] src/storage/storage.cc:44: Please compile with CUDA enabled
Traceback (most recent call last):
  File "train.py", line 97, in <module>
    stytole_model.fit(X=data_train, eval_metric = mx.metric.np(CRPS))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 656, in fit
    logger=logger, work_load_list=work_load_list, monitor=monitor)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 187, in _train_multi_device
    logger=logger)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor.py", line 357, in __init__
    train_exec = symbol.simple_bind(ctx[i], 'write', **data_shapes)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 617, in simple_bind
    arg_shapes)]
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 475, in zeros
    arr = empty(shape, ctx, dtype)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 458, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 62, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:59:16] src/storage/storage.cc:44: Please compile with CUDA enabled

Thanks

**Comment by vchuravy** [comment]
See the documentation [1]. You will have to enable CUDA in the build options. 

[1] http://mxnet.readthedocs.org/en/latest/build.html#customized-building

**Comment by qiaohaijun** [comment]
config.mk

**Comment by Shashidhar123** [comment]
Thanks all will try and will close it once it works.

**Comment by Shashidhar123** [comment]
Hi,
My machine doesn't have NVDIA drivers as I don't have NVDIA graphics card. But will the installation work as the drivers are not present. Please help.
Thanks

**Comment by Gelu74** [comment]
CUDA is propietary to NVIDIA, I don't think it would run in a non-nvidia graphics card

**Comment by phunterlau** [comment]
@Shashidhar123 One can rent an AWS GPU instance and try by following my recent blog for setup MXnet there 
https://no2147483647.wordpress.com/2016/01/16/setup-amazon-aws-gpu-instance-with-mxnet/ 0.07$ per hour is not so expensive.

**Comment by No41Name** [comment]
Why all the documentation pages are not available anymore?
