### ISSUE TITLE
OSError when using Python package:  `GLIBCXX_3.4.20' not found

### ISSUE THREAD

**Issue by peterzcc** [dmlc/mxnet#1297]
I successfully compiled mxnet but failed to use it in python, the output is shown below. I think may be it's because I used GCC 4.9.2 to make mxnet, but the python comes with GCC 4.4.7. I'm using virtualenv, Is there any way to fix it? 
Thanks! It has been so many problems with the requirement of GCC version.

'''
(venv)bash-4.1$ python
Python 2.7.9 (default, Jan 29 2015, 11:26:57)
[GCC 4.4.7 20120313 (Red Hat 4.4.7-11)] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet as mx
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/csproject/dygroup2/czeng/venv/downloads/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/csproject/dygroup2/czeng/venv/downloads/mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/csproject/dygroup2/czeng/venv/downloads/mxnet/python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/local/software/python2/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/local/software/python2/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /usr/lib64/libstdc++.so.6: version `GLIBCXX_3.4.20' not found (required by /csproject/dygroup2/czeng/venv/downloads/mxnet/python/mxnet/../../lib/libmxnet.so)
'''

**Comment by piiswrong** [comment]
Where is your gcc 4.9.2's installed? try adding it's /lib in LD_LIBRARY_PATH before /usr/lib64

**Comment by peterzcc** [comment]
@piiswrong 
Thanks a lot for your suggestion! It worked after I added the the lib64 of gcc-4.9.2.
