### ISSUE TITLE
Problem with Android amalgamation

### ISSUE THREAD

**Issue by yonadavs** [dmlc/mxnet#1355]
After completing the amalgamation, trying to `System.loadLibrary("mxnet_predict")` throws exception: `unable to locate symbol "_Znwj"`
How do I get over this issue?

**Comment by yonadavs** [comment]
Was building with gcc, and not g++.. Sorry, my bad..

**Comment by saustar** [comment]
@yonadavs HI, were you able to launch the Android app with your .so file?
I have doubts which so file I have to use? jni_libmxnet_predict.so or mxnet/lib/libmxnet_predict.so file?
also I am facing issue on app launch #1754

**Comment by yonadavs** [comment]
use the jni_libmxnet_predict.so.
The error you mentioned in your other issue seems like you try to create the predictor with a image shape that is incompatible with the pre-trained net you provided.

**Comment by saustar** [comment]
@yonadavs so how do I chnage tha image shape in predictor? I have a pre trained net using CIFAR 10 dataset describe [here](https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar10-recipe.ipynbl)

**Comment by yonadavs** [comment]
This link is dead.
Anyway, as I understand, this is not the net provided by Leiliana in the Android example.
If so, there are 2 places where change might be in order. 1) predictor creation, change the shape there to match the dimensions used for training, 2) the forwarding method, when casting to float array, change the offsets accordingly.

**Comment by saustar** [comment]
this is the link:

https://github.com/dmlc/mxnet/blob/master/example/notebooks/cifar10-recipe.ipynb

**Comment by yonadavs** [comment]
@saustar  there you have it then. Your NN was trained with an input of 3x28x28, while the MxNet example was trained with 3x224x224. search your project for "224", and change where needed.

**Comment by saustar** [comment]
@yonadavs Thanks !!

Now I am seeing some other issues like `org.dmlc.mxnet.MxnetException: InferShape Error in convolution2: [18:20:17] jni/../mxnet_predict-all.cc:122257`

looks like I have to change some more things!!

**Comment by saustar** [comment]
@yonadavs HI,Anyway, as I understand, this is not the net provided by Leiliana in the Android example.
If so, there are 2 places where change might be in order. 1) predictor creation, change the shape there to match the dimensions used for training, 2) the forwarding method, when casting to float array, change the offsets accordingly.
I dont understand the change you mentioned 

> 

What is 2nd change? I dont understand it. I am geting following error whrn I try to classfify an image on android phone with my CIFAR-10 model:
`04-01 13:08:55.898 19448-19870/com.happen.it.make.whatsthis E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #1
                                                                              Process: com.happen.it.make.whatsthis, PID: 19448
                                                                              java.lang.RuntimeException: An error occured while executing doInBackground()
                                                                                  at android.os.AsyncTask$3.done(AsyncTask.java:300)
                                                                                  at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
                                                                                  at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                  at java.lang.Thread.run(Thread.java:818)
                                                                               Caused by: org.dmlc.mxnet.MxnetException: [13:08:55] jni/../mxnet_predict-all.cc:110446: Check failed: (dshape.Size()) == (size) Memory size do not match
                                                                                  at org.dmlc.mxnet.Predictor.nativeForward(Native Method)
                                                                                  at org.dmlc.mxnet.Predictor.forward(Predictor.java:61)
                                                                                  at com.happen.it.make.whatisit.MxNetUtils.identifyImage(MxNetUtils.java:36)
                                                                                  at com.happen.it.make.whatisit.WhatsActivity$1$1.doInBackground(WhatsActivity.java:67)
                                                                                  at com.happen.it.make.whatisit.WhatsActivity$1$1.doInBackground(WhatsActivity.java:58)
                                                                                  at android.os.AsyncTask$2.call(AsyncTask.java:288)
                                                                                  at java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                  at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112) 
                                                                                  at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587) 
                                                                                  at java.lang.Thread.run(Thread.java:818) `

**Comment by pallashadow** [comment]
Hi, @yonadavs . I met unable to locate symbol "_ZN5mxnet2op16SimpleOpRegistry3GetEv" issue, but I am sure I am using g++
