### ISSUE TITLE
Problem in distributed training on Sun Grid Engine (sge)

### ISSUE THREAD

**Issue by peterzcc** [dmlc/mxnet#1458]
I've encountered the following error when running the train_mnist.py using dmlc_sge.py. I created 2 worker node and 1 server node and submit all of them on a single machine. I tested dmlc_local.py but it worked fin. I don't know where the problem comes from, could anyone help? Thanks a lot!
```

[13:04:31] ./dmlc-core/include/dmlc/logging.h:215: [13:04:31] ./ps-lite/include/ps/internal/van.h:56: Check failed: ready_ call Start() first
Traceback (most recent call last):
  File "train_mnist.py", line 127, in <module>
    train_model.fit(args, net, get_iterator)
  File "mxnet/example/image-classification/train_model.py", line 11, in fit
    head = '%(asctime)-15s Node[' + str(kv.rank) + '] %(message)s'
  File "mxnet/python/mxnet/kvstore.py", line 281, in rank
    check_call(_LIB.MXKVStoreGetRank(self.handle, ctypes.byref(rank)))
  File "mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [13:04:31] ./ps-lite/include/ps/internal/van.h:56: Check failed: ready_ call Start() first
```

**Comment by peterzcc** [comment]
It seems like the problem is due to the KVStore was not correctly created for os.environ['DMLC_ROLE'] = 'server'. The same error would happen if I assign it to a irrelevant string. But setting it to "worker" doesn't cause any problem. Does anyone know if there is a method to get some error message from kvstore.create() function?

**Comment by peterzcc** [comment]
Solved this issue by setting the environment variable before calling the file
