### ISSUE TITLE
train_model var sym_gen make a error 

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#1464]
https://github.com/dmlc/mxnet/blob/master/example/image-classification/train_model.py#L77

Traceback (most recent call last):
  File "train_imagenet.py", line 85, in <module>
    train_model.fit(args, net, get_iterator)
  File "/search/data/user/qhj/github/mxnet/example/image-classification/train_model.py", line 85, in fit
    epoch_end_callback = checkpoint)
  File "/root/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 720, in fit
    **(self.kwargs))
  File "/root/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/optimizer.py", line 52, in create_optimizer
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'sym_gen'

**Comment by qiaohaijun** [comment]
@pluskid

**Comment by piiswrong** [comment]
you need to pull the latest code.

**Comment by pluskid** [comment]
Yes, please git pull update to the latest code. A new keyword argument was added recently.

**Comment by qiaohaijun** [comment]
@pluskid  @piiswrong  Ok
