### ISSUE TITLE
 Invalid NDArray file format   while vgg19.py for neural-style

### ISSUE THREAD

**Issue by lisiminy** [dmlc/mxnet#1534]
`INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
[14:36:59] ./dmlc-core/include/dmlc/logging.h:241: [14:36:59] src/ndarray/ndarray.cc:593: Check failed: fi->Read(data) Invalid NDArray file format
Traceback (most recent call last):
  File "/home/sm/mxnet/example/neural-style/run.py", line 115, in <module>
    model_executor = importlib.import_module('model_' + args.model).get_model(size, dev)
  File "/home/sm/mxnet/example/neural-style/model_vgg19.py", line 53, in get_model
    pretrained = mx.nd.load("./model/vgg19.params")
  File "/home/sm/mxnet/example/neural-style/../../python/mxnet/ndarray.py", line 575, in load
    ctypes.byref(names)))
  File "/home/sm/mxnet/example/neural-style/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:36:59] src/ndarray/ndarray.cc:593: Check failed: fi->Read(data) Invalid NDArray file format`
 
i got this error when i build the run.py
i used gpu = -1 and the default setting.
is there something wrong with the vgg19.params file?

**Comment by lisiminy** [comment]
i download the vgg19.params file again. 
and problem solved......

**Comment by ysh329** [comment]
mark
