### ISSUE TITLE
The error in Python when I try to run with CUDA

### ISSUE THREAD

**Issue by will945945945** [dmlc/mxnet#1575]
I used the ubuntu14.04.

I compiled it successful with the following config.mk:

#================================
export CC = gcc
export CXX = g++
export NVCC = nvcc

DEBUG = 0

ADD_LDFLAGS =

ADD_CFLAGS =

USE_CUDA = 1
USE_CUDA_PATH = /usr/local/cuda  #I check the command 'whereis cuda' in my machine

USE_CUDNN = 0

USE_NVRTC = 0

USE_OPENCV = 1

USE_OPENMP = 1

UNAME_S := $(shell uname -s)
ifeq ($(UNAME_S), Darwin)
USE_BLAS = apple
else
USE_BLAS = atlas
endif

USE_INTEL_PATH = NONE

ifeq ($(USE_BLAS), mkl)
USE_STATIC_MKL = 1
else
USE_STATIC_MKL = NONE
endif

USE_DIST_KVSTORE = 0

USE_HDFS = 0

LIBJVM=$(JAVA_HOME)/jre/lib/amd64/server

USE_S3 = 0

EXTRA_OPERATORS =
#================================================

Next I ran the command "sudo python setup.py install"
and it worked.

After the installation, 
when I try to run the example: "python train_mnist.py" or "python train_mnist.py -- gpu0"

I got this error message:

#========================================================
Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/willchen/Desktop/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: libcudart.so.7.0: cannot open shared object file: No such file or directory
#=============================================================

And if I compile with 'USE_CUDA = 0', it works good.

How can I solve it????

**Comment by Godricly** [comment]
have u setup the LD_LIBRARY_PATH for the CUDA?

**Comment by will945945945** [comment]
OK，It works, thanks!!!!!
