### ISSUE TITLE
seq2seq model encounter a error I donot know how to debug

### ISSUE THREAD

**Issue by 0rchard** [dmlc/mxnet#1615]
Hi, I tried to build a seq2seq model in mxnet using bucketing trick introduced in http://mxnet.readthedocs.org/en/latest/tutorial/bucketing.html?highlight=bucket.

However, I encounter an error in load_data_batch I dont not how to debug or fix.

The error is list as follow.
Can anyone help me to debug what happened, and how to fix it?

Summary of dataset ==============
bucket of len [  5,  5] : 39183 samples
bucket of len [  5, 10] : 29160 samples
bucket of len [ 10, 10] : 17332 samples
bucket of len [ 10, 15] : 7766 samples
bucket of len [ 15, 15] : 4193 samples
bucket of len [ 15, 20] : 1575 samples
bucket of len [ 20, 20] : 791 samples
Summary of dataset ==============
bucket of len [  5,  5] : 4029 samples
bucket of len [  5, 10] : 2768 samples
bucket of len [ 10, 10] : 1743 samples
bucket of len [ 10, 15] : 828 samples
bucket of len [ 15, 15] : 431 samples
bucket of len [ 15, 20] : 137 samples
bucket of len [ 20, 20] : 64 samples
2016-03-10 10:42:34,881 Auto-select kvstore type = local_update_cpu
2016-03-10 10:42:34,882 Start training with [cpu(0), cpu(1)]
Traceback (most recent call last):
  File "lstm_bucketing/lstm_bucketing.py", line 433, in <module>
    train()
  File "lstm_bucketing/lstm_bucketing.py", line 429, in train
    batch_end_callback = mx.callback.Speedometer(args.batch_size, 50),
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 767, in fit
    sym_gen=self.sym_gen)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 221, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 353, in load_data_batch
    shared_group=self.execgrp)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 190, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 127, in _bind_exec
    assert arg_arr.shape == arg_shape[i]
AssertionError

Codes is in the attachment. Please refer it for the source code.
Thank you.

[lstm_bucketing.py.txt](https://github.com/dmlc/mxnet/files/166995/lstm_bucketing.py.txt)

**Comment by pluskid** [comment]
Hi [executor_manager.py:L127](https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L127) is trying to bind a new executor and share parameter with existing executor. The error occurs because the size of the existing parameter is different parameter. Note we have an assumption that in bucketing, the parameter for models in different bucket are the same (and shared). Can you please

- Verify if this assumption is true for your scenario? 
- Check either your data iter is reporting the correct shapes in `provide_data`? Note both the data iter and the batch need to report correct `provide_data` if bucketing is used.
- You can insert some print statement at executor_manager.py:L127 right before the assert to print the `name`, and `arg_arr.shape`, `arg_shape[i]`, which might be able to help to find out what is wrong.

**Comment by 0rchard** [comment]
I dump the data before executor_manager.py:L127.
name : decoder_l0_i2h_weight
arg_arr.shape : (32L,)
arg_shape[i]    : (512L, 128L)

It is really weird, since i2h weight is not in the input provide data. Only the input provide data has the shape (batch_size, ), in which batch_size = 32.

I will follow other suggestion you mentioned and give you feedback if i can find something.
Thank you.

**Comment by 0rchard** [comment]
I checked data iter and batch report same provide_data.

It seems the order in arg_names = sym.list_arguments() is not sorted 
in executor_manager.py:L99 

I dumped arg_names from two buckets, 
the first bucket (encoder_len = 5, decoder_len = 5) initialized the arg_arrays according to the first arg_names from executor_manager.py:L99

after the first bucket initialized, it bind to the base_executor in the order of first arg_names.

However,  arg_names in the second bucket (encoder_len = 10, decoder_len  = 10) does not have the exactly same order with the first bucket. Since some parameter had bind to the base_executor, it goes to second branch in executor_manager.py:L118, in which case it does not check shared_data_arrays, but refer to base_exec.arg_arrays to retrieve the arg_arr. And in my case, two different parameter (encoder_data/5, decoder_l0_i2h_weight) happened to occupy the same slot in base_exec.arg_arrays, thus triggering the shape incompatible error. 

What I find weird is, when I go back to the original example using lstm for ptb language modeling. 
It does not have any trouble in name-arrays alignment.

Does this have anything to do with my bucket setup. Since in seq2seq model, each bucket is a tuple of (encoder_len, decoder_len), while in ptb language model, bucket only contain seq_len?

Looking forwards to your suggestion and help.
Thank you.

**Comment by pluskid** [comment]
@0rchard Thanks for the information. I believe this is a bug! Let me look into it!

**Comment by pluskid** [comment]
@0rchard We have just merged a patch that should have fixed the problem. Can you test if it is working now?

**Comment by 0rchard** [comment]
Great

**Comment by 0rchard** [comment]
@pluskid I tested this new patch.
It seems it still having shape compatible problem.
[12:07:56] ./dmlc-core/include/dmlc/logging.h:241: [12:07:56] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):                                                                                                                   
  File "lstm_bucketing/lstm_bucketing.py", line 449, in <module>
    train()
  File "lstm_bucketing/lstm_bucketing.py", line 445, in train
    batch_end_callback = mx.callback.Speedometer(args.batch_size, 50),
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 767, in fit
    sym_gen=self.sym_gen)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 221, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 373, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 224, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 86, in _load_data
    _load_general(batch.data, targets)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 82, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 424, in copyto
    return NDArray._copyto(self, out=other)
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 765, in unary_ndarray_function
    c_array(ctypes.c_char_p, [])))
  File "/usr/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [12:07:56] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

Could you please have a look at my source code, to see if my bucket setup (a tuple of encoder_len and decoder_len) is OK with your current architecture.

**Comment by pluskid** [comment]
@0rchard I will try to take a look at your example maybe tomorrow. Bucket key could be anything, tuples should be fine. Meanwhile, one more thing that might be worth checking: we require the batch-size to be the same for all buckets.  You can try to insert print statements before [this line](https://github.com/dmlc/mxnet/blob/master/python/mxnet/executor_manager.py#L81) just to see what `d_src[slice_idx].shape` and `d_dst` and this might give us some hint on what potentially went wrong.

**Comment by 0rchard** [comment]
@pluskid I found what is wrong in my code.
As you suggest, the provide data in data iter and batch should be the same.
But in my code, they have the same data, but in different order, result in some input data and parameter mixed up. After reordering the data iter, the error disappear.

Thank you very much for your suggestion and help.

**Comment by pluskid** [comment]
@0rchard Great! I'm closing this issue for now. Feel free to re-open it if you run into any issue! :)
