### ISSUE TITLE
 Error when running the Python example: `example/image-classification/train_mnist.py` 

### ISSUE THREAD

**Issue by EasonD3** [dmlc/mxnet#1717]
I was running python `example/image-classification/train_mnist.py`. There was an error popped up (see below), when creating the `top_k_accuracy` metric layer. However, I couldn’t find any bugs in the related source code.

Can anyone please help check what’s the issue here?

Thanks!

By the way, I also posted this question in the [Google Group](https://groups.google.com/forum/#!forum/mxnet). But it seems the Google Group is not actively used.

```
2016-03-22 23:16:54,569 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000, save_model_prefix=None)
[23:16:55] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[23:16:55] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
Traceback (most recent call last):
  File "/home/lxduan/softwares/pycharm-5.0.3/helpers/pydev/pydevd.py", line 2411, in <module>
    globals = debugger.run(setup['file'], None, None, is_module)
  File "/home/lxduan/softwares/pycharm-5.0.3/helpers/pydev/pydevd.py", line 1802, in run
    launch(file, globals, locals)  # execute the script
  File "/home/lxduan/mxnet/example/image-classification/train_mnist.py", line 132, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "/home/lxduan/mxnet/example/image-classification/train_model.py", line 85, in fit
    eval_metrics.append(mx.metric.create('top_k_accuracy', top_k = top_k))
TypeError: create() got an unexpected keyword argument 'top_k'
```

**Comment by shuokay** [comment]
You should check if there is a folder named ```mxnet``` in ```mxnet/example/image-classification/```
The python wrapper have updated and Python prefer to call methods in the current folder, so If there is a out of time ```mxnet``` folder, you may encounter this problem.

**Comment by haria** [comment]
echo $PYTHONPATH to see whether you have a old version of MXNET installed. remove the path from PYTHONPATH and add new location to PYTHONPATH and try again.

**Comment by Piyush3dB** [comment]
@lxduan have you found a resolution?

You probably have a previous version of the library in `/usr/local/lib/python2.7/dist-packages`].  If so, just do:
```
$ pip uninstall mxnet
$ pwd
/usr/local/lib/python2.7/dist-packages
$ sudo rm -rf ./mxnet-0.5.0-py2.7.egg 
```
then rebuild mxnet and you should be able to run the example after setting up `$PYTHONPATH`.

**Comment by lxduan** [comment]
Sorry about my late update. I used the same solution as you pointed out @Piyush3dB . Thanks for sharing!
