### ISSUE TITLE
fail to continue train the model of "lstm_ptb_bucketing"

### ISSUE THREAD

**Issue by constantineshu** [dmlc/mxnet#1739]
I'm new here. And I meet some problems when running the lstm_ptb_bucketing demo. 
I save the model with "epoch_end_callback = mx.callback.do_checkpoint(prefix = model_prefix)" firstly. Then I load the demo with "model = mx.model.FeedForward.load" and use "model.fit()" to continue train. But here comes the error massage.
"mxnet.base.MXNetError: [21:19:35] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch".
I'm not sure how to fix it.

**Comment by pluskid** [comment]
Can you post the full error message to help us to locate the error? Thanks!

**Comment by constantineshu** [comment]
Traceback (most recent call last):
  File "lstm_ptb_bucketing.py", line 303, in <module>
    batch_end_callback = mx.callback.Speedometer(batch_size, 500))
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 791, in fit
    sym_gen=self.sym_gen)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 221, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 359, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 210, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 85, in _load_data
    _load_general(batch.data, targets)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 81, in _load_general
    d_src[slice_idx].copyto(d_dst)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 424, in copyto
    return NDArray._copyto(self, out=other)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 765, in unary_ndarray_function
    c_array(ctypes.c_char_p, [])))
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:30:01] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

Thanks for your reply.

**Comment by pluskid** [comment]
I think the problem here is that in the case of bucketing, the saved symbol does not contain information to create symbols for other buckets. Can you try this:

```
# AFTER loading checkpoint, BEFORE running fit()
model.symbol = None
model.sym_gen = sym_gen # the sym_gen defined in lstm_ptb_bucketing.py
```

Please let us know if this workaround works, and we will try to come up with a better API to handle model loading and saving in bucketing.

**Comment by constantineshu** [comment]
Thanks for your help. It really works!
However, I meet another problem about model.predict(). 
After I load the model, and set model.symbol = None, model.sym_gen = sym_gen,
I try to do prediction with "probs = model.predict(X = test_iter)". And I got following error message:

Traceback (most recent call last):
  File "predict.py", line 49, in <module>
    probs = model.predict(X = test_iter)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 593, in predict
    self._init_predictor(data_shapes)
  File "/home/qspace/anaconda2/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 523, in _init_predictor
    pred_exec = self.symbol.simple_bind(
AttributeError: 'NoneType' object has no attribute 'simple_bind'

Do I forget anything?

**Comment by pluskid** [comment]
@constantineshu The prediction API is not bucketing-aware yet. The main reason is that typically the prediction of models using bucketing (usually RNNs) need specialized behavior. For the ptb case, for example, "predicting" means doing a sequence sampling. Note you do **not** see the input sequence as in the training case. Instead, you just see the first character. You need to do a step-by-step sampling by feeding your prediction to the next step. A sampler example can be found in [lstm.py](https://github.com/dmlc/mxnet/blob/master/example/rnn/lstm.py)

**Comment by pluskid** [comment]
@tqchen @antinucleon @piiswrong Currently the bucketing API does not work well with model checkpoints. There are two options to handle this

- Option 1: use python pickle to also save the `gen_sym` function. This makes it impossible to load the saved model from a different language binding.
- Option 2: require the user to pass the same `gen_sym` to the function `load_checkpoint`, which will basically ignore the saved JSON file for the symbol.

Any preference / suggestions?

**Comment by tqchen** [comment]
I think we can go with option 2 for now. Since bucketing API is mainly aimed for varying inputs

**Comment by piiswrong** [comment]
I think we can do both. Override when gensym is provided

**Comment by tqchen** [comment]
The main problem of option1 is its makes the checkpt depends on pickle and python. Making other language unable to load the checkpoint, it also requires more effort in code change

**Comment by pluskid** [comment]
Please try the new module API for bucketing.
