### ISSUE TITLE
It will outputs error in lstm_ptb_bucketing.py after one epoch training ends

### ISSUE THREAD

**Issue by tornadomeet** [dmlc/mxnet#1746]
hi, @pluskid , i just run the lstm_ptb_bucketing.py demo, and it outputs the error message as below,
```
2016-03-29 15:16:23,366 Epoch[0] Batch [1700]    Speed: 135.28 samples/sec    Train-accuracy=0.318865
2016-03-29 15:16:27,722 Epoch[0] Resetting Data Iterator
2016-03-29 15:16:27,723 Epoch[0] Train-accuracy=0.318873
2016-03-29 15:16:27,723 Epoch[0] Time cost=410.278
2016-03-29 15:16:56,348 Epoch[0] Validation-accuracy=0.351199
Traceback (most recent call last):
  File "lstm_ptb_bucketing.py", line 312, in <module>
    batch_end_callback=mx.callback.Speedometer(batch_size, 50),)
  File "../../python/mxnet/model.py", line 770, in fit
    sym_gen=self.sym_gen)
  File "../../python/mxnet/model.py", line 220, in _train_multi_device
    for data_batch in train_data:
  File "lstm_ptb_bucketing.py", line 174, in __iter__
    data[:] = self.data[i_bucket][idx]
ValueError: could not broadcast input array from shape (0,20) into shape (32,20)
```
it happend when one epoch finish training, in the line ```data[:] = self.data[i_bucket][idx]```, the data.shape is (32,20), but why the self.data[i_bucket][idx].shape is (0,20) in the second epoch?
i think it may (may) due to that we do nothing in reset of train_data, but how to fixed this? thanks~

**Comment by tornadomeet** [comment]
The recently example is ok
