### ISSUE TITLE
Issue in amalgamation for Android

### ISSUE THREAD

**Issue by saustar** [dmlc/mxnet#1754]
I have followed the following steps:

#Build standalone toolchain
`android-ndk-r10e/build/tools/make-standalone-toolchain.sh --arch=arm --platform=android-19 --install-dir=/tmp/mytoolchain --toolchain=arm-linux-androideabi-4.9`

#built OpenBLAS for Android
```
cd OpenBLAS/
export PATH=/tmp/mytoolchain/bin:$PATH
make HOSTCC=gcc CC=arm-linux-androideabi-gcc NO_LAPACK=1 TARGET=ARMV7
```

#Changes in Makefile
```
vim Makefile
export OPENBLAS_ROOT=/home/ubuntu/OpenBLAS
export CXX=/tmp/mytoolchain/bin/arm-linux-androideabi-g++
export SYS_ROOT=/tmp/mytoolchain/sysroot
export INCLUDE=/tmp/mytoolchain/include/c++/4.9
${CXX} ${CFLAGS} -fPIC -o $@ -c jni/predictor.cc --sysroot=${SYS_ROOT} -I ${INCLUDE}
```

Chnages in  mxnet_predict-all.cc as described [here](https://github.com/dmlc/mxnet/tree/master/amalgamation#android)

Finally When I ran `make ANDROID=1` I can see` jni_libmxnet_predict.so` and `libmxnet_predict.so.` When I use jni_libmxnet_predict.so I get following error on app launch:

```
03-30 16:35:20.893 31548-31548/? E/AndroidRuntime: FATAL EXCEPTION: main
                                                   Process: com.happen.it.make.whatsthis, PID: 31548
                                                   java.lang.RuntimeException: Unable to create application com.happen.it.make.whatisit.WhatsApplication: org.dmlc.mxnet.MxnetException: [16:35:20] jni/../mxnet_predict-all.cc:110063: Check failed: from.shape() == to->shape() operands shape mismatch
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5125)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:177)
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510)
                                                       at android.os.Handler.dispatchMessage(Handler.java:102)
                                                       at android.os.Looper.loop(Looper.java:145)
                                                       at android.app.ActivityThread.main(ActivityThread.java:5951)
                                                       at java.lang.reflect.Method.invoke(Native Method)
                                                       at java.lang.reflect.Method.invoke(Method.java:372)
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
                                                    Caused by: org.dmlc.mxnet.MxnetException: [16:35:20] jni/../mxnet_predict-all.cc:110063: Check failed: from.shape() == to->shape() operands shape mismatch
                                                       at org.dmlc.mxnet.Predictor.createPredictor(Native Method)
                                                       at org.dmlc.mxnet.Predictor.<init>(Predictor.java:43)
                                                       at com.happen.it.make.whatisit.WhatsApplication.onCreate(WhatsApplication.java:53)
                                                       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1020)
                                                       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5122)
                                                       at android.app.ActivityThread.access$1600(ActivityThread.java:177) 
                                                       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1510) 
                                                       at android.os.Handler.dispatchMessage(Handler.java:102) 
                                                       at android.os.Looper.loop(Looper.java:145) 
                                                       at android.app.ActivityThread.main(ActivityThread.java:5951) 
                                                       at java.lang.reflect.Method.invoke(Native Method) 
                                                       at java.lang.reflect.Method.invoke(Method.java:372) 
                                                       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400) 
                                                       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
``` 

What is this error? Also I am not able to understand after maxing changes in mxnext_predict-all.cc instructions says to add removed part again. How does that going to affect anything because build is already done!

**Comment by xiadeye** [comment]
what does '${CXX} ${CFLAGS} -fPIC -o $@ -c jni/predictor.cc --sysroot=${SYS_ROOT} -I ${INCLUDE}' mean?Is it added in makefile?But I get error:
'Makefile:7: *** missing separator'
