### ISSUE TITLE
Error when running mxnet with openmp disabled

### ISSUE THREAD

**Issue by gengyifeng** [dmlc/mxnet#1769]
With USE_OPENMP and USE_OPENCV disabled,  I got errors when running "python train_mnist.py.

Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "/home/yifeng/mxnet/example/image-classification/find_mxnet.py", line 2, in <module>
    import mxnet as mx
  File "/home/yifeng/mxnet/python/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/home/yifeng/mxnet/python/mxnet/base.py", line 43, in <module>
    _LIB = _load_lib()
  File "/home/yifeng/mxnet/python/mxnet/base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 438, in LoadLibrary
    return self._dlltype(name)
  File "/usr/lib64/python2.7/ctypes/__init__.py", line 360, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /home/yifeng/mxnet/python/mxnet/../../lib/libmxnet.so: undefined symbol: omp_get_thread_num

Any ideas?

**Comment by gengyifeng** [comment]
It can be fixed by removing flags in dmlc-core/make/dmlc.mk line 14 and 15
