### ISSUE TITLE
Managed to compile libmxnet.dll on Windows 10 but unable to import

### ISSUE THREAD

**Issue by freddycct** [dmlc/mxnet#1871]
Setup all the paths, compiled without error. Already included all the lib directories in PATH. The libmxnet.dll file is sitting right there but python is just unable to import it.

I compiled in VS 2013 under x64 build. If i use the prebuilt library, it works. 
my system.... cuda 7.5, cudnn v3, vs2013 with update 5, windows 10, openblas

But I would like to use my own libmxnet.dll instead of the prebuilt, can anyone tell me what's wrong?
```
C:\Users\chuaf\Downloads\mxnet\example\image-classification>python train_mnist.py
Traceback (most recent call last):
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\find_mxnet.py", line 2, in <module>
    import mxnet as mx
ImportError: No module named 'mxnet'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "train_mnist.py", line 1, in <module>
    import find_mxnet
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\find_mxnet.py", line 7, in <module>
    import mxnet as mx
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\../../python\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\../../python\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\../../python\mxnet\base.py", line 34, in _load_lib
    lib_path = libinfo.find_lib_path()
  File "C:\Users\chuaf\Downloads\mxnet\example\image-classification\../../python\mxnet\libinfo.py", line 35, in find_lib_path
    'List of candidates:\n' + str('\n'.join(dll_path)))
RuntimeError: Cannot find the files.
List of candidates:
C:\Users\chuaf\Downloads\mxnet\python\mxnet\libmxnet.dll
C:\Users\chuaf\Downloads\mxnet\python\mxnet\../../lib/libmxnet.dll
C:\Users\chuaf\Downloads\mxnet\python\mxnet\../../build\Release\libmxnet.dll
C:\Users\chuaf\Downloads\mxnet\python\mxnet\../../windows/x64\Release\libmxnet.dll
```

**Comment by freddycct** [comment]
nvm, i did something wrong...

**Comment by andrewjylee** [comment]
@freddycct  I'm having the same problem: What did you do wrong? I believe I built mxnet correctly using Visual Studios

**Comment by freddycct** [comment]
hey, use dumpbin.exe /DEPENDENTS  to check which DLL file libmxnet.dll needs to have.

dumpbin.exe is in one of your visual studio folders

**Comment by freddycct** [comment]
@andrewjylee does it work?

**Comment by andrewjylee** [comment]
I made a silly mistake of building in visual studio to DEBUG while the python script seems to be looking for RELEASE. I've moved on to a different problem now. Thanks!
