### ISSUE TITLE
run example/rnn/char-rnn.ipynb failed

### ISSUE THREAD

**Issue by wachaong** [dmlc/mxnet#1875]
i am new, i got this error here

07:33:45 INFO:Start training with [gpu(0)]
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
[19:36:00] src/symbol/static_graph.cc:383: Memory efficient gradient aggregation on... to disable, set MXNET_EXEC_INPLACE_GRAD_SUM_CAP to big number
Traceback (most recent call last):
  File "char-rnn.py", line 120, in <module>
    epoch_end_callback=mx.callback.do_checkpoint("obama"))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 774, in fit
    sym_gen=self.sym_gen)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 244, in _train_multi_device
    executor_manager.update_metric(eval_metric, data_batch.label)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 406, in update_metric
    self.curr_execgrp.update_metric(metric, labels)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor_manager.py", line 262, in update_metric
    metric.update(labels_slice, texec.outputs)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/metric.py", line 338, in update
    self.sum_metric += self._feval(label, pred)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/metric.py", line 355, in feval
    return numpy_feval(label, pred)
  File "char-rnn.py", line 50, in Perplexity
    loss += -np.log(max(1e-10, pred[i][int(label[i])]))
TypeError: only length-1 arrays can be converted to Python scalars

**Comment by pluskid** [comment]
This must be due to a recent refactoring of lstm example. I will try to fix it.

**Comment by wachaong** [comment]
3q. it's been fixed. can this program support chinese language now？i want to try run a chinese languate data.

**Comment by wachaong** [comment]
when i run a chinese language data,seems ok? but it failed as follows: 

08:22:20 INFO:Epoch[0] Batch [50]	Speed: 95.20 samples/sec	Train-Perplexity=26.682578
08:22:37 INFO:Epoch[0] Batch [100]	Speed: 93.06 samples/sec	Train-Perplexity=17.048589
08:22:52 INFO:Epoch[0] Resetting Data Iterator
08:22:52 INFO:Epoch[0] Train-Perplexity=13.995063
08:22:52 INFO:Epoch[0] Time cost=49.586
08:22:52 INFO:Saved checkpoint to "obama-0001.params"
08:23:09 INFO:Epoch[1] Batch [50]	Speed: 95.04 samples/sec	Train-Perplexity=7.092565
08:23:27 INFO:Epoch[1] Batch [100]	Speed: 93.18 samples/sec	Train-Perplexity=6.897969
08:23:42 INFO:Epoch[1] Resetting Data Iterator
08:23:42 INFO:Epoch[1] Train-Perplexity=6.883966
08:23:42 INFO:Epoch[1] Time cost=49.628
08:23:42 INFO:Saved checkpoint to "obama-0002.params"
[20:23:42] /home/chao/dnn/mxnet/dmlc-core/include/dmlc/logging.h:235: [20:23:42] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "char-rnn.py", line 268, in <module>
    num_label=len(vocab) + 1, arg_params=arg_params, ctx=mx.gpu(), dropout=0.2)
  File "/home/chao/dnn/mxnet/example/rnn/rnn_model.py", line 40, in __init__
    arg_params[key].copyto(self.executor.arg_dict[key])
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 434, in copyto
    return NDArray._copyto(self, out=other)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 1081, in unary_ndarray_function
    c_array(ctypes.c_char_p, [])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [20:23:42] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

**Comment by wachaong** [comment]
when i change checkpoint 75 in the code to checkpoint2 , there is no this error.
but i can't handle chinese file now , can this code support it? 3q.

**Comment by wachaong** [comment]
3ks. support unicode is done. ＾＿＾
