### ISSUE TITLE
build and installation failed

### ISSUE THREAD

**Issue by wanghaisheng** [dmlc/mxnet#189]
error encounter  when run 
```
Traceback (most recent call last):
  File "example/mnist/mlp.py", line 2, in <module>
    from data import mnist_iterator
  File "/mxnet/example/mnist/data.py", line 6, in <module>
    import get_data
ImportError: No module named get_data

```
```
cd ..; python example/mnist/mlp.py
```

**Comment by antinucleon** [comment]
same to https://github.com/dmlc/mxnet/issues/188

**Comment by wanghaisheng** [comment]
pls update the doc part

**Comment by tqchen** [comment]
After #191  You should be able to run the basic example from any directory
