### ISSUE TITLE
Run failed on multiple machines 

### ISSUE THREAD

**Issue by tjuzhao111** [dmlc/mxnet#1988]
Hi,
Thank you for all the contributors of mxnet.

I modified the mnist example a little. I changed the original MNISTIter into the NDArrayIter because I have used a numpy data. Then I tried to run it on two machines. However, it failed and  throw an error as following:

Can anyone help me please?

```
[21:21:28] /env/mxnet/dmlc-core/include/dmlc/logging.h:235: 
[21:21:28] /env/mxnet/ps-lite/include/ps/kv_app.h:574: Check failed: (vals->size()) == (total_val) 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [21:21:28] /env/mxnet/ps-lite/include/ps/kv_app.h:574: Check failed: (vals->size()) == (total_val) 
--------------------------------------------------------------------------
mpirun noticed that process rank 0 with PID 26987 on node rb4e03252.cm8 exited on signal 6 (Aborted).
--------------------------------------------------------------------------
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/local/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/env/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/mpi.py", line 37, in run
    subprocess.check_call(prog, shell=True)
  File "/usr/local/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'mpirun -n 2  -x DMLC_PS_ROOT_URI=192.168.100.4 -x DMLC_ROLE=worker -x DMLC_JOB_CLUSTER=mpi -x DMLC_PS_ROOT_PORT=9093 -x DMLC_NUM_WORKER=2 -x DMLC_NUM_SERVER=2 --hostfile hosts  python train_mlp.py --kv-store dist_sync --indata /works/data/train_data_shuffled.npy --batch-size 3000 --lr 1e-4 --model-prefix 0426/mlp --num-epochs 10' returned non-zero exit status 134
```

**Comment by piiswrong** [comment]
@mli

**Comment by mli** [comment]
does the original MNISTIter work? it seems a problem due to wrong data shape

**Comment by tjuzhao111** [comment]
@mli Thank you for your response. :) 

The original MNISTIter works well.
I'm sorry for that I made a mistake. This exception was raised because the codes saved on two machines were inconsistent.

**Comment by jeejeeli** [comment]
Can you tell me how configure mulitple machines for train，this problem have troubled me for a long time，Thanks~~~
