### ISSUE TITLE
cuda out of memory?

### ISSUE THREAD

**Issue by joyivan** [dmlc/mxnet#2025]
### I think the core code in symbol_inception-bn-28-small.py  is 

 data = mx.symbol.Variable(name="data")
    conv1 = ConvFactory(data=data, kernel=(3,3), pad=(1,1), num_filter=96, act_type="relu", mirror_attr=attr)
    in3a = SimpleFactory(conv1, 32, 32, mirror_attr=attr)
    in3b = SimpleFactory(in3a, 32, 48, mirror_attr=attr)
    in3c = DownsampleFactory(in3b, 80, mirror_attr=attr)
    in4a = SimpleFactory(in3c, 112, 48, mirror_attr=attr)
    in4b = SimpleFactory(in4a, 96, 64, mirror_attr=attr)
    in4c = SimpleFactory(in4b, 80, 80, mirror_attr=attr)
    in4d = SimpleFactory(in4c, 48, 96, mirror_attr=attr)
    in4e = DownsampleFactory(in4d, 96, mirror_attr=attr)
    in5a = SimpleFactory(in4e, 176, 160, mirror_attr=attr)
    in5b = SimpleFactory(in5a, 176, 160, mirror_attr=attr)
    pool = mx.symbol.Pooling(data=in5b, pool_type="avg", kernel=(7,7), name="global_pool", attr=attr)
    flatten = mx.symbol.Flatten(data=pool, name="flatten1", attr=attr)
    fc = mx.symbol.FullyConnected(data=flatten, num_hidden=num_classes, name="fc1")
    softmax = mx.symbol.SoftmaxOutput(data=fc, name="softmax")

### when I run  "sudo python train_lung_mxnet.py --gpus 0,1"  it shows " out of memory" 
 detail is start with arguments Namespace(batch_size=32, data_dir='/home/joyivan/downloads/', gpus='0,1', kv_store='local', load_epoch=None, lr=0.05, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='inception-bn-28-small', num_epochs=20, num_examples=224, save_model_prefix=None)
[11:53:39] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: /home/joyivan/downloads/train.rec, use 4 threads for decoding..
[11:53:39] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: /home/joyivan/downloads/test.rec, use 4 threads for decoding..
2016-05-04 11:53:39,571 Node[0] Start training with [gpu(0), gpu(1)]
[11:53:39] /home/joyivan/mxnet/dmlc-core/include/dmlc/./logging.h:235: [11:53:39] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
Traceback (most recent call last):
  File "train_lung_mxnet.py", line 75, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/joyivan/mxnet/example/image-classification/train_model.py", line 100, in fit
    epoch_end_callback = checkpoint)
  File "/home/joyivan/mxnet/python/mxnet/model.py", line 784, in fit
    sym_gen=self.sym_gen)
  File "/home/joyivan/mxnet/python/mxnet/model.py", line 192, in _train_multi_device
    logger=logger)
  File "/home/joyivan/mxnet/python/mxnet/executor_manager.py", line 311, in __init__
    self.slices, train_data)
  File "/home/joyivan/mxnet/python/mxnet/executor_manager.py", line 224, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/home/joyivan/mxnet/python/mxnet/executor_manager.py", line 177, in _bind_exec
    grad_req=grad_req, shared_exec=base_exec)
  File "/home/joyivan/mxnet/python/mxnet/symbol.py", line 800, in bind
    ctypes.byref(handle)))
  File "/home/joyivan/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:53:39] src/storage/./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
[[11:53:40] /home/joyivan/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:53:40] /home/joyivan/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
11:53:40] /home/joyivan/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:53:40] /home/joyivan/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
terminate called recursively
terminate called after throwing an instance of 'dmlc::Error'
 
### why ? `I` really I need the more cards ? or the parameter does exceed 24G thanks for answers me  ..

**Comment by Godricly** [comment]
Maybe you can use the get_cost function in memonger to have an estimation of your memory cost. check memonger example for how to use it.

**Comment by piiswrong** [comment]
reduce batchsize to 16 or 32
