### ISSUE TITLE
solving Poisson regression task - with ReLu

### ISSUE THREAD

**Issue by gugatr0n1c** [dmlc/mxnet#2042]
Hi,

I am solving Poisson regression task (with big average), so it can be treatet as task with continius target.
But values are only positive.

So I would like to use rmse for training with last layer just: one neuron with ReLu transformation.

I tried to do this with this code:

batch_size = 100
train_iter = mx.io.NDArrayIter(matrix_learn, target_learn, batch_size=batch_size)
test_iter = mx.io.NDArrayIter(matrix_test, target_test, batch_size=batch_size)

data = mx.symbol.Variable('data')
		
fc1  = mx.symbol.FullyConnected(data = data, name='fc1', num_hidden = 200)
act1 = mx.symbol.Activation(data = fc1, name='tanh1', act_type='tanh')

fc2  = mx.symbol.FullyConnected(data = act1, name = 'fc2', num_hidden = 100)
act2 = mx.symbol.Activation(data = fc2, name='tanh2', act_type='tanh')

fc3  = mx.symbol.FullyConnected(data = act2, name='fc3', num_hidden = 1 )
net = mx.symbol.Activation(data = fc3, name='relu1', act_type='relu')

model = mx.model.FeedForward(
							symbol = net,
							num_epoch = 10,
							learning_rate = 0.1,
							momentum = 0.9,
							wd = 0.00001)
										
model.fit(X=train_iter, eval_data=test_iter, batch_end_callback = mx.callback.Speedometer(batch_size,200))
		

But getting this error:

[15:02:13] /home/gugatr0n1c/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:02:13] src/symbol/symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias

Traceback (most recent call last):
  File "dat17_mxnet.py", line 110, in <module>
    model.fit(X=train_iter, eval_data=test_iter, batch_end_callback = mx.callback.Speedometer(batch_size,200))
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/symbol.py", line 439, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/symbol.py", line 499, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:02:13] src/symbol/symbol.cc:121: Symbol.InferShapeKeyword argument name softmax_label not found.
Candidate arguments:
	[0]data
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias

Something about softmax. I am new to this library, thanx for help!

**Comment by gugatr0n1c** [comment]
Can anyone pls help, how to code this properly?

**Comment by antinucleon** [comment]
If you want to use high level API, you must have a ```Output``` layer and indicate name for it, eg "softmax". Please refer ```Custom Training Loop``` chapter in https://github.com/dmlc/mxnet-gtc-tutorial/blob/master/tutorial.ipynb

If there is no suitable Output symbol, you can calculate gradient in numpy, and set back in custom training loop while calling backward, eg: ```exe.backward([top_grad])```

**Comment by tqchen** [comment]
If you want to use RMSE as objective, you will want to add a LinearRegressionOutput on top of your final layer
