### ISSUE TITLE
TypeError: create() got an unexpected keyword argument 'top_k' ?

### ISSUE THREAD

**Issue by phunterlau** [dmlc/mxnet#2125]
I am using today's github latest commit (up to b5a369384e566490211cfb458bc9936d6c2a5678 ) but I had the following error. Seems like `metric.py` `create()` function is damaged?

```
cd mxnet/example/image-classification
python train_mnist.py
```
gives
```
[22:22:51] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[22:22:52] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
Traceback (most recent call last):
  File "train_mnist.py", line 132, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "/home/liuh/github/mxnet/example/image-classification/train_model.py", line 85, in fit
    eval_metrics.append(mx.metric.create('top_k_accuracy', top_k = top_k))
TypeError: create() got an unexpected keyword argument 'top_k'
```

**Comment by phunterlau** [comment]
Oops, sorry my bad: I updated the package but forgot to update python pack. After updating the python package, it works. Sorry for confusions.
