### ISSUE TITLE
Problem with image classification examples

### ISSUE THREAD

**Issue by zmonoid** [dmlc/mxnet#2588]
Hi,
I am currently using the examples given by default.
I tried the train_imagenet.py file to train on a small dataset.
The problem is that, when I use **the network Inception-bn and Inception-bn-full**, the network converges very fast, but when I change the network to **VGG, Alexnet and Googlenet**, the network does not converge at all even after 10 epoch, may I know what would be the reason?

Another problem is  the **inception-v3** network, it will report error if I use this network.

This is inception-bn network, converges very fast:

```
2016-07-01 13:51:21,565 Node[0] start with arguments Namespace(batch_size=32, clip_gradient=5.0, data_dir='../imgs/', data_shape=224, gpus='2', kv_store='local', load_epoch=None, log_dir='./logs/', log_file='inception-bn.log', lr=0.01, lr_factor=0.9, lr_factor_epoch=1.0, model_prefix=None, network='inception-bn', num_classes=10, num_epochs=50, num_examples=20000, save_model_prefix='save/inception-bn', train_dataset='train.rec', val_dataset='val.rec')
2016-07-01 13:51:23,120 Node[0] Start training with [gpu(2)]
2016-07-01 13:51:39,659 Node[0] Epoch[0] Batch [50] Speed: 111.66 samples/sec   Train-accuracy=0.107500
2016-07-01 13:51:54,043 Node[0] Epoch[0] Batch [100]    Speed: 111.24 samples/sec   Train-accuracy=0.108125
2016-07-01 13:52:08,380 Node[0] Epoch[0] Batch [150]    Speed: 111.61 samples/sec   Train-accuracy=0.132500
2016-07-01 13:52:22,748 Node[0] Epoch[0] Batch [200]    Speed: 111.36 samples/sec   Train-accuracy=0.131250
2016-07-01 13:52:37,100 Node[0] Epoch[0] Batch [250]    Speed: 111.49 samples/sec   Train-accuracy=0.158125
2016-07-01 13:52:51,446 Node[0] Epoch[0] Batch [300]    Speed: 111.53 samples/sec   Train-accuracy=0.156875
2016-07-01 13:53:05,877 Node[0] Epoch[0] Batch [350]    Speed: 110.87 samples/sec   Train-accuracy=0.180000
2016-07-01 13:53:20,244 Node[0] Epoch[0] Batch [400]    Speed: 111.37 samples/sec   Train-accuracy=0.197500
2016-07-01 13:53:34,587 Node[0] Epoch[0] Batch [450]    Speed: 111.56 samples/sec   Train-accuracy=0.217500
2016-07-01 13:53:48,995 Node[0] Epoch[0] Batch [500]    Speed: 111.05 samples/sec   Train-accuracy=0.205000
2016-07-01 13:54:03,377 Node[0] Epoch[0] Batch [550]    Speed: 111.26 samples/sec   Train-accuracy=0.218125
2016-07-01 13:54:16,609 Node[0] Epoch[0] Resetting Data Iterator
2016-07-01 13:54:16,610 Node[0] Epoch[0] Time cost=172.072
2016-07-01 13:54:16,970 Node[0] Saved checkpoint to "save/inception-bn-0001.params"
2016-07-01 13:54:25,289 Node[0] Epoch[0] Validation-accuracy=0.243219
2016-07-01 13:54:33,448 Node[0] Update[626]: Change learning rate to 9.00000e-03
```

This is the vgg network, does not converge:

```
2016-07-01 14:32:15,550 Node[0] start with arguments Namespace(batch_size=32, clip_gradient=5.0, data_dir='../imgs/', data_shape=224, gpus='1', kv_store='local', load_epoch=None, log_dir='./logs/', log_file='vgg.log', lr=0.01, lr_factor=0.9, lr_factor_epoch=1.0, model_prefix=None, network='vgg', num_classes=10, num_epochs=50, num_examples=20000, save_model_prefix='save/vgg', train_dataset='train.rec', val_dataset='val.rec')
2016-07-01 14:32:17,232 Node[0] Start training with [gpu(1)]
2016-07-01 14:32:40,067 Node[0] Epoch[0] Batch [50] Speed: 75.09 samples/sec    Train-accuracy=0.109375
2016-07-01 14:33:01,560 Node[0] Epoch[0] Batch [100]    Speed: 74.45 samples/sec    Train-accuracy=0.088125
2016-07-01 14:33:23,166 Node[0] Epoch[0] Batch [150]    Speed: 74.06 samples/sec    Train-accuracy=0.097500
2016-07-01 14:33:44,657 Node[0] Epoch[0] Batch [200]    Speed: 74.45 samples/sec    Train-accuracy=0.103125
2016-07-01 14:34:06,110 Node[0] Epoch[0] Batch [250]    Speed: 74.58 samples/sec    Train-accuracy=0.108750
2016-07-01 14:34:27,590 Node[0] Epoch[0] Batch [300]    Speed: 74.49 samples/sec    Train-accuracy=0.116875
2016-07-01 14:34:49,049 Node[0] Epoch[0] Batch [350]    Speed: 74.56 samples/sec    Train-accuracy=0.102500
2016-07-01 14:35:10,531 Node[0] Epoch[0] Batch [400]    Speed: 74.48 samples/sec    Train-accuracy=0.106875
2016-07-01 14:35:32,053 Node[0] Epoch[0] Batch [450]    Speed: 74.34 samples/sec    Train-accuracy=0.105000
2016-07-01 14:35:53,513 Node[0] Epoch[0] Batch [500]    Speed: 74.56 samples/sec    Train-accuracy=0.113750
2016-07-01 14:36:14,966 Node[0] Epoch[0] Batch [550]    Speed: 74.59 samples/sec    Train-accuracy=0.103750
2016-07-01 14:36:34,737 Node[0] Epoch[0] Resetting Data Iterator
2016-07-01 14:36:34,738 Node[0] Epoch[0] Time cost=256.817
2016-07-01 14:36:35,674 Node[0] Saved checkpoint to "save/vgg-0001.params"
2016-07-01 14:36:49,611 Node[0] Epoch[0] Validation-accuracy=0.100236
2016-07-01 14:37:01,814 Node[0] Update[626]: Change learning rate to 9.00000e-03

```

This is the bash script to run all network:

```
net="googlenet"
gpus="0"
echo "network:$net"
echo "gpus:$gpus"

if [ -e "./logs/$net.log" ]; then
    echo "Log file exists"
    rm ./logs/$net.log
else
    echo "Log file does not exist"
fi

python train_imagenet.py \
  --data-dir='../imgs/' \
  --log-dir='./logs/' \
  --num-classes=10 \
  --num-examples=20000 \
  --lr=0.01 \
  --lr-factor=0.9 \
  --lr-factor-epoch=1 \
  --num-epochs=50 \
  --batch-size=32 \
  --network=$net \
  --save-model-prefix="save/$net" \
  --log-file="$net.log" \
  --gpus=$gpus
```

This is the error information when running inception-v3:

```
[14:58:59] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: ../imgs/train.rec, use 4 threads for decoding..
[14:58:59] src/io/./iter_normalize.h:103: Load mean image from ../imgs/mean.bin
[14:59:00] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: ../imgs/val.rec, use 4 threads for decoding..
[14:59:00] src/io/./iter_normalize.h:103: Load mean image from ../imgs/mean.bin
[14:59:01] /home/ubuntu/mxnet-0.7.0/dmlc-core/include/dmlc/logging.h:235: [14:59:01] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (32,288,13,13). (first input shape: (32,768,12,12))
Traceback (most recent call last):
  File "train_imagenet.py", line 85, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/ubuntu/Kaggle/image-classification/train_model.py", line 100, in fit
    epoch_end_callback = checkpoint)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 745, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 485, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/ubuntu/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in ch_concat_mixed_3_chconcat: [14:59:01] src/operator/./concat-inl.h:152: Check failed: (dshape[j]) == (tmp[j]) Incorrect shape[2]: (32,288,13,13). (first input shape: (32,768,12,12))
```

**Comment by piiswrong** [comment]
You need to tune your learning rate. Also training these big networks on small dataset may not make sense

The last issue should be fixed by this https://github.com/dmlc/mxnet/pull/2585

**Comment by zmonoid** [comment]
@piiswrong  Thank you, but why inception can work but Alexnet and VGG cannot with all same parameters?

**Comment by zmonoid** [comment]
Thanks, the problem is input data size for inception-v3 should be 299.

It seems that larger network is more capable to generalize for input data, but also easier to overfit. GoogleNet at last converges. Network size Alexnet <VGG<Google < Inception
