### ISSUE TITLE
import mxnet error

### ISSUE THREAD

**Issue by SJTUzhanglj** [dmlc/mxnet#2601]
I wanna test a faster rcnn demo and re-compiled a MXNet for detection version. I have compiled out the libs and dlls, but I set the python interface and meet the following error:

>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()
  File "D:\Anaconda2\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.cdll.LoadLibrary(lib_path[0])
  File "D:\Anaconda2\lib\ctypes\__init__.py", line 443, in LoadLibrary
    return self._dlltype(name)
  File "D:\Anaconda2\lib\ctypes\__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
WindowsError: [Error 126]

I think it's a environment-path error but i don't know how to fix it. The official instructor is only for linux.

**Comment by piiswrong** [comment]
@hjk41

**Comment by sxjscience** [comment]
Sometimes it's caused by OpenCV. Remember to add the OpenCV library to the environment variable.

**Comment by cjfan** [comment]
WindowsError: [Error 126]
This is usually because the dependent dll not find.So, you can:
1.use the 'Depends' tools open the libmxnet.dll, see which dll is missing.
2.make sure the u have the dll in your machine, and add the environment-path.

**Comment by SJTUzhanglj** [comment]
Thank you for solving my trouble @cjfan

**Comment by sunbinbin1991** [comment]
I have same problem, actually, my project is work yesterday,and I can't find the reason.
