### ISSUE TITLE
issue in example warpctc/lstm_ocr.py

### ISSUE THREAD

**Issue by sinmaystar** [dmlc/mxnet#2696]
I want to run example/warpctc/lstm_ocr.py but it occur a problem, I install mxnet without CUDA my computer use amd graphics card,so I want to use cpu to run this example

mxnet.base.MXNetError: [14:15:36] src/storage/storage.cc:43: Please compile with CUDA enabled

how can i use cpu run this example?

**Comment by arestorres** [comment]
Have you changed the device setting to  'contexts = mx.cpu()'?

**Comment by xlvector** [comment]
I have tested it under CPU, it should works.
If @arestorres 's answer does not work, please let me know.

**Comment by sinmaystar** [comment]
thanks for solving my problem，where can I catch Xero.ttf？
            在2016年07月14日 14:28，arestorres 写道:Have you changed the device setting to  'contexts = mx.cpu()'?

**Comment by xlvector** [comment]
You can download it from http://www.webpagepublicity.com/free-fonts/x/Xerox%20Sans%20Serif%20Narrow.ttf  and save it under ./data/ folder

**Comment by sinmaystar** [comment]
@xlvector I have download .ttf file put it into data directory and modify source code line 142 'contexts = [mx.context.gpu(1)]' to 'contexts = [mx.context.cpu()]' and then run this code it occurs a problem

illusion@illusion:~/mxnet/example/warpctc$ python toy_ctc.py 
begin fit
2016-07-14 15:09:32,765 Start training with [cpu(0)]
[15:09:32] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:09:32] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
[15:09:32] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:09:32] src/engine/./threaded_engine.h:306: [15:09:32] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [15:09:32] src/engine/./threaded_engine.h:306: [15:09:32] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)


how can I solve this proble? thanks for your time

**Comment by sinmaystar** [comment]
@xlvector I have download .ttf file and put it into data directory, then I run python lstm_ocr.py it occurs a problem

illusion@illusion:~/mxnet/example/warpctc$ python lstm_ocr.py 
begin fit
2016-07-14 15:14:29,809 Start training with [cpu(1)]
iter
Traceback (most recent call last):
File "lstm_ocr.py", line 174, in 
batch_end_callback=mx.callback.Speedometer(BATCH_SIZE, 50),)
File "../../python/mxnet/model.py", line 789, in fit
sym_gen=self.sym_gen)
File "../../python/mxnet/model.py", line 221, in train_multi_device
for data_batch in train_data:
File "lstm_ocr.py", line 67, in __iter_
img = self.captcha.generate(num)
File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 40, in generate
im = self.generate_image(chars)
File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 220, in generate_image
self.create_noise_curve(im, color)
File "/usr/local/lib/python2.7/dist-packages/captcha/image.py", line 132, in create_noise_curve
Draw(image).arc(points, start, end, fill=color)
File "/usr/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 164, in arc
self.draw.draw_arc(xy, start, end, ink)
TypeError: must be sequence of length 4, not 2

How can I solve this problem ? thanks for your time

**Comment by sinmaystar** [comment]
@xlvector  It seems like captcha's problem, I try to use ImageCaptcha to generate a captcha also occurs this problem, do u have any method to solve this problem?

**Comment by xlvector** [comment]
Seems someone else also meet this problem.
You can write an test script to fix python-captcha problem.

**Comment by sinmaystar** [comment]
@xlvector I have solved Pillow problem, but it occurs another problem... 
in toy_ctc.py i have change code 129 line from 
'contexts = [mx.context.gpu(0)]' to 'contexts = [mx.context.cpu()]' 
and in lstm_ocr.py i have change code 142 line  from
 'contexts = [mx.context.gpu(0)]' to 'contexts = [mx.context.cpu()]' 

both cannot run, it occurs a problem as below:

illusion@illusion:~/mxnet/example/warpctc$ python toy_ctc.py 
begin fit
2016-07-14 18:12:08,391 Start training with [cpu(0)]
[18:12:08] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:12:08] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
[18:12:08] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:12:08] src/engine/./threaded_engine.h:306: [18:12:08] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:12:08] src/engine/./threaded_engine.h:306: [18:12:08] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)


illusion@illusion:~/mxnet/example/warpctc$ python lstm_ocr.py 
begin fit
2016-07-14 18:15:53,637 Start training with [cpu(1)]
iter
[18:15:53] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:15:53] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
[18:15:53] /home/illusion/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:15:53] src/engine/./threaded_engine.h:306: [18:15:53] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:15:53] src/engine/./threaded_engine.h:306: [18:15:53] plugin/warpctc/./warpctc-inl.h:159: Unknown device type 1
An fatal error occurred in asynchronous engine operation. If you do not know what caused this error, you can try set environment variable MXNET_ENGINE_TYPE to NaiveEngine and run with debugger (i.e. gdb). This will force all operations to be synchronous and backtrace will give you the series of calls that lead to this error. Remember to set MXNET_ENGINE_TYPE back to empty after debugging.
Aborted (core dumped)


how can I solve this problem?

sorry to interrupt a day, thanks very much for sovling my problem

**Comment by xlvector** [comment]
contexts = mx.context.cpu()

without array

**Comment by sinmaystar** [comment]
@xlvector still have this problem, do you have ever met this problem?

**Comment by sinmaystar** [comment]
@xlvector Can u help me to solve this problem?

**Comment by xlvector** [comment]
I have review the code and find a bug which make warpctc can not work with CPU now.

I will fix it in next week.

**Comment by arestorres** [comment]
@xlvector Can u please tell me what the bug u mentioned above is it?  I run lstm_ocr.py  using cpu, but the train_accuracy is always 0.00 after 10 epochs. Does this bug you mentioned above cause this?

**Comment by xlvector** [comment]
@arestorres The bug is between L149 and L161 in https://github.com/dmlc/mxnet/blob/master/plugin/warpctc/warpctc-inl.h#L149

Here, if the device is not GPU, it will LOG(FATAL) << "Unknown device type " << data.dev_mask_;

For convergence, the lstm_ocr will converge after 7000 iterations. You can see my log in 
https://github.com/dmlc/mxnet/pull/2326
.

**Comment by arestorres** [comment]
@xlvector many thanks!

**Comment by anxingle** [comment]
@xlvector    can u notice us in this issue after u fix this problem? I also meet the same problem .

**Comment by sinmaystar** [comment]
I have installed baidu warp-ctc and do as your readme introduction to rebuild mxnet but when I run lstm_ocr.py it occurs an error, module object has no attribute 'WarpCTC'how can I solve this problem, I run on Mac OS X 
            在2016年07月19日 15:28，Xiang Liang 写道:@arestorres The bug is between L149 and L161 in https://github.com/dmlc/mxnet/blob/master/plugin/warpctc/warpctc-inl.h#L149

Here, if the device is not GPU, it will LOG(FATAL) << "Unknown device type " << data.dev_mask_;

For convergence, the lstm_ocr will converge after 7000 iterations. You can see my log in 
#2326
.

**Comment by sinmaystar** [comment]
@xlvector I have installed baidu warp-ctc and do as your readme introduction to rebuild mxnet but when I run lstm_ocr.py it occurs an error, module object has no attribute 'WarpCTC' how can I solve this problem, I run on Mac OS X

**Comment by jinxuan777** [comment]
@arestorres @xlvector  ,Have you fix your problem? my train_accuracy is always 0.00 after 3 epochs
2016-11-23 14:40:32,621 Epoch[3] Batch [3500]   Speed: 55.98 samples/sec        Train-Accuracy=0.001250
2016-11-23 14:41:01,146 Epoch[3] Batch [3550]   Speed: 56.09 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:41:29,825 Epoch[3] Batch [3600]   Speed: 55.79 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:41:58,528 Epoch[3] Batch [3650]   Speed: 55.74 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:42:26,973 Epoch[3] Batch [3700]   Speed: 56.25 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:42:55,580 Epoch[3] Batch [3750]   Speed: 55.93 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:43:24,107 Epoch[3] Batch [3800]   Speed: 56.09 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:43:52,701 Epoch[3] Batch [3850]   Speed: 55.96 samples/sec        Train-Accuracy=0.001250
2016-11-23 14:44:21,255 Epoch[3] Batch [3900]   Speed: 56.03 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:44:49,779 Epoch[3] Batch [3950]   Speed: 56.09 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:45:18,298 Epoch[3] Batch [4000]   Speed: 56.10 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:45:46,874 Epoch[3] Batch [4050]   Speed: 55.99 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:46:15,494 Epoch[3] Batch [4100]   Speed: 55.91 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:46:44,205 Epoch[3] Batch [4150]   Speed: 55.73 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:47:12,823 Epoch[3] Batch [4200]   Speed: 55.91 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:47:41,378 Epoch[3] Batch [4250]   Speed: 56.03 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:48:09,894 Epoch[3] Batch [4300]   Speed: 56.11 samples/sec        Train-Accuracy=0.001250
2016-11-23 14:48:38,412 Epoch[3] Batch [4350]   Speed: 56.11 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:49:06,909 Epoch[3] Batch [4400]   Speed: 56.15 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:49:35,364 Epoch[3] Batch [4450]   Speed: 56.23 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:50:03,852 Epoch[3] Batch [4500]   Speed: 56.17 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:50:32,402 Epoch[3] Batch [4550]   Speed: 56.04 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:51:00,885 Epoch[3] Batch [4600]   Speed: 56.17 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:51:29,423 Epoch[3] Batch [4650]   Speed: 56.07 samples/sec        Train-Accuracy=0.001250
2016-11-23 14:51:57,967 Epoch[3] Batch [4700]   Speed: 56.05 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:52:26,422 Epoch[3] Batch [4750]   Speed: 56.23 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:52:54,879 Epoch[3] Batch [4800]   Speed: 56.23 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:53:23,418 Epoch[3] Batch [4850]   Speed: 56.06 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:53:51,931 Epoch[3] Batch [4900]   Speed: 56.12 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:54:20,406 Epoch[3] Batch [4950]   Speed: 56.19 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:54:48,918 Epoch[3] Batch [5000]   Speed: 56.12 samples/sec        Train-Accuracy=0.000625
2016-11-23 14:55:17,374 Epoch[3] Batch [5050]   Speed: 56.23 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:55:45,912 Epoch[3] Batch [5100]   Speed: 56.07 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:56:14,399 Epoch[3] Batch [5150]   Speed: 56.17 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:56:42,872 Epoch[3] Batch [5200]   Speed: 56.19 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:57:11,339 Epoch[3] Batch [5250]   Speed: 56.21 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:57:39,813 Epoch[3] Batch [5300]   Speed: 56.19 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:58:08,275 Epoch[3] Batch [5350]   Speed: 56.22 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:58:36,762 Epoch[3] Batch [5400]   Speed: 56.17 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:59:05,240 Epoch[3] Batch [5450]   Speed: 56.19 samples/sec        Train-Accuracy=0.000000
2016-11-23 14:59:33,717 Epoch[3] Batch [5500]   Speed: 56.19 samples/sec        Train-Accuracy=0.000000

**Comment by anxingle** [comment]
@jinxuan777   Just 3 epochs?  You need about one or more days to convergent  if you run the program on CPU . you can try set the batch_size more bigger( 1000 or more bigger ).

**Comment by sunspring320** [comment]
@jinxuan777  when i run the demo of lstm_ocr.py with mxnet, i am also meet this problem  self.draw.draw_arc(xy, start, end, ink), TypeError: must be sequence of length 4, not 2 
i try all the ways in this content, but i do not slove this problem, would you help me fix this problem? thanks

**Comment by sunspring320** [comment]
@sinmaystar when i run the demo of lstm_ocr.py with mxnet, i am also meet this problem self.draw.draw_arc(xy, start, end, ink), TypeError: must be sequence of length 4, not 2
i try all the ways in this content, but i do not slove this problem, would you help me fix this problem? thanks

**Comment by sunspring320** [comment]
@anxingle when i run the demo of lstm_ocr.py with mxnet, i am also meet this problem self.draw.draw_arc(xy, start, end, ink), TypeError: must be sequence of length 4, not 2
i try all the ways in this content, but i do not slove this problem, would you help me fix this problem? thanks
