### ISSUE TITLE
GPU out of memory error

### ISSUE THREAD

**Issue by magic282** [dmlc/mxnet#2778]
Hi,

I found that if two mxnet programs run on the same GPU and one of them cause out of memory error, I will never run any mxnet programs anymore. I found that the solution is to reboot... I am using K40.
The error detail:
```
19:06:42 INFO:Start training with [gpu(0)]
[19:06:43] D:\users\a\tmp\mxnet\dmlc-core\include\dmlc/logging.h:235: [19:06:43] d:\users\a\tmp\mxnet\src\storage\./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
Traceback (most recent call last):
  File "D:/users/a/Projects/mxnet_learn/s2s_example/trainer.py", line 505, in <module>
    epoch_end_callback=[mx.callback.do_checkpoint(model_save_name),
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\model.py", line 788, in fit
    sym_gen=self.sym_gen)
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\model.py", line 192, in _train_multi_device
    logger=logger)
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\executor_manager.py", line 311, in __init__
    self.slices, train_data)
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\executor_manager.py", line 224, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\executor_manager.py", line 145, in _bind_exec
    arg_arr = nd.zeros(arg_shape[i], ctx, dtype=arg_types[i])
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\ndarray.py", line 801, in zeros
    arr = empty(shape, ctx, dtype)
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\ndarray.py", line 537, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\ndarray.py", line 68, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "C:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:06:43] d:\users\a\tmp\mxnet\src\storage\./gpu_device_storage.h:39: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: out of memory
```

**Comment by piiswrong** [comment]
Running two GPU program on the same GPU is usually a bad idea.
TF explicitly bans. MXNet allows it so that it doesn't crash other program but you shouldn't run two mxnet on the same GPU nontheless

**Comment by magic282** [comment]
I see. Thank you for the reply.
