### ISSUE TITLE
An error about train_mnist.py example on Mac

### ISSUE THREAD

**Issue by kkunn** [dmlc/mxnet#2799]
```
MacBook-Air:mxnet kun$ python example/image-classification/train_mnist.py
2016-07-22 02:58:02,718 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000, save_model_prefix=None)
sh: wget: command not found
unzip:  cannot find or open mnist.zip, mnist.zip.zip or mnist.zip.ZIP.
rm: mnist.zip: No such file or directory
[02:58:02] /Users/user/mxnet/dmlc-core/include/dmlc/logging.h:235: [02:58:02] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "mnist/train-images-idx3-ubyte"
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 153, in <module>
    train_model.fit(args, net, get_iterator(data_shape))
  File "/Users/user/mxnet/example/image-classification/train_model.py", line 47, in fit
    (train, val) = data_loader(args, kv)
  File "example/image-classification/train_mnist.py", line 92, in get_iterator_impl
    part_index  = kv.rank)
  File "/Users/user/mxnet/example/image-classification/../../python/mxnet/io.py", line 582, in creator
    ctypes.byref(iter_handle)))
  File "/Users/user/mxnet/example/image-classification/../../python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [02:58:02] src/io/local_filesys.cc:149: Check failed: allow_null  LocalFileSystem: fail to open "mnist/train-images-idx3-ubyte"
```

看不懂…… what should I do.....

**Comment by StuJia** [comment]
wget，下载mnist的dataset吧，wget是linux下的指令吧
