### ISSUE TITLE
'bool' object has no attribute 'sum'

### ISSUE THREAD

**Issue by yechaochen** [dmlc/mxnet#2907]
I don't know which reason causes this error.
```
[10:46:24] src/io/iter_image_recordio.cc:68: Loaded ImageList from /home/deeper/6W-project/ye_train.lst 50000 Image records
[10:46:24] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: /home/deeper/6W-project/ye_train.rec, use 4 threads for decoding..
[10:46:26] src/io/iter_image_recordio.cc:68: Loaded ImageList from /home/deeper/6W-project/ye_val.lst 10000 Image records
[10:46:26] src/io/iter_image_recordio.cc:211: ImageRecordIOParser: /home/deeper/6W-project/ye_val.rec, use 4 threads for decoding..
Traceback (most recent call last):
  File "train_mynet.py", line 90, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/deeper/6W-project/net/train_model.py", line 100, in fit
    epoch_end_callback = checkpoint)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 789, in fit
    sym_gen=self.sym_gen)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 245, in _train_multi_device
    executor_manager.update_metric(eval_metric, data_batch.label)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 406, in update_metric
    self.curr_execgrp.update_metric(metric, labels)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 262, in update_metric
    metric.update(labels_slice, texec.outputs)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/metric.py", line 105, in update
    metric.update(labels, preds)
  File "/home/deeper/anaconda/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/metric.py", line 142, in update
    self.sum_metric += (pred_label.flat == label.flat).sum()
AttributeError: 'bool' object has no attribute 'sum'
```

Does the label type in the lst file is wrong?
The details of lst file show in my terminal are like:
```
0       -1.1895 1.7383  1169743180/20090909_033109.jpg
1       -1.226  1.7133  1169743180/20090909_034115.jpg
2       -1.0627 0.5873  1169743180/20090909_035131.jpg
3       -1.0975 0.1597  1169743180/20090909_040120.jpg
4       -1.0672 1.5973  1169743180/20090909_042113.jpg
5       -1.4038 1.5722  1169743180/20090909_043144.jpg
6       -1.4372 0.5505  1169743180/20090909_044122.jpg
```
The "-" ".0""0." in the second and third column are shown in white color. But the other contents is red.Does this causes the error?

----------update-------------
Does this code`self.sum_metric += (pred_label.flat == label.flat).sum()` shown in the last raw of error information has some problem? The value of code`pred_label.flat == label.flat` is only true and false.This value is bool type.

**Comment by antinucleon** [comment]
Repeat to https://github.com/dmlc/mxnet/issues/2915
