### ISSUE TITLE
mx.io.ImageRecordIter operands shape mismatch issue 

### ISSUE THREAD

**Issue by swaak** [dmlc/mxnet#2990]
Hi
I am working on grey scale images of size 28x28. But creating recordIter gives shape mismatch error. I am using following code to create recorditer:

train_iter = mx.io.ImageRecordIter(
...     shuffle=True,
...     path_imgrec="../Path/to/training/file/train.rec",
...     mean_r = 128,
...     mean_g = 128,
...     mean_b = 128,
...     scale = 0.0078125,
...     rand_crop=False,
...     rand_mirror=False,
...     data_shape=(1, 28, 28),
...     batch_size=batch_size,
...     prefetch_buffer=4,
...     preprocess_threads=2)

And the error i am getting is as below:

use 1 threads for decoding..
[15:56:29] /home/waqas/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:56:29] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "stl_normal_grey.py", line 517, in <module>
    arg_map["data"][:] = data
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 201, in __setitem__
    value.copyto(self)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 434, in copyto
    return NDArray._copyto(self, out=other)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 1081, in unary_ndarray_function
    c_array(ctypes.c_char_p, [])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:56:29] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

Further analyzing the issue i found that size of samples in recorditer was wrong
b2=train_iter.getdata()
>>> b2.shape
(200L, 3L, 28L, 28L)

Its shape should have been (200L, 1L, 28L, 28L) since i am using grey scale images

Can someone suggest what is the reason and how to rectify the issue ?

**Comment by tornadomeet** [comment]
your train.rec is generate by color image.

**Comment by swaak** [comment]
No Sir i have generated it using grey scale images. The other two dimensions ( 200, 2,28,28) and  (200,3,28,28) contains exact copies of 1st dimension which contains actual grey scale samples. I don't know why its creating two additional copies !!

**Comment by tornadomeet** [comment]
it maybe that when useing im2rec, shoud set color=0 or -1, or it will force your gray image as rbg image.

**Comment by swaak** [comment]
Yes that was indeed the problem. setting color to unchanged (-1) solved the issue. Thanks alot for your support.
