### ISSUE TITLE
Gdk-CRITICAL

### ISSUE THREAD

**Issue by anatolfilin** [dmlc/mxnet#3107]
Got this error trying to run  examples/neural-style demo with GPU (python run.py)
MNIST works with GPU just fine. What's wrong?

(run.py:11781): Gdk-CRITICAL **: gdk_cursor_new_for_display: assertion 'GDK_IS_DISPLAY (display)' failed
Traceback (most recent call last):
  File "run.py", line 8, in <module>
    from skimage import io, transform
  File "/usr/lib64/python2.7/site-packages/skimage/io/__init__.py", line 15, in <module>
    reset_plugins()
  File "/usr/lib64/python2.7/site-packages/skimage/io/manage_plugins.py", line 89, in reset_plugins
    _load_preferred_plugins()
  File "/usr/lib64/python2.7/site-packages/skimage/io/manage_plugins.py", line 69, in _load_preferred_plugins
    _set_plugin(p_type, preferred_plugins['all'])
  File "/usr/lib64/python2.7/site-packages/skimage/io/manage_plugins.py", line 81,

**Comment by piiswrong** [comment]
your skimage package isn't working. see if python -c "from skimage import io" works. If not, it's a skimage problem

**Comment by anatolfilin** [comment]
@piiswrong thanks a lot! You were right. X-forwarding has solved the problem.
