### ISSUE TITLE
ImportError: No module named captcha.image

### ISSUE THREAD

**Issue by SDASDASA** [dmlc/mxnet#3205]
I compiled warp-ctc and mxnet successful.
I add warp-ctc in config.mk，and compiled mxnet，
but when I run lstm_ocr.py, the problem disappear

>>> from captcha.image import ImageCaptcha
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: No module named captcha.image

Did you have idea about this?

**Comment by piiswrong** [comment]
you have not installed the python package captcha

**Comment by SDASDASA** [comment]
Thanks your answer。i did not install the  python package captcha really。
After installed the python package captcha，but i encounter a new error:

plugin/sframe/iter_sframe.cc:16:36: fatal error: unity/lib/image_util.hpp: No such file or directory
#include <unity/lib/image_util.hpp>

Did you have idea about this？Thanks  again.

**Comment by Yang507** [comment]
@SDASDASA  How do you install the python package captcha? I install it and still find `No module named captcha.image`

**Comment by SDASDASA** [comment]
i just do as this : "sudo pip install captcha"

**Comment by chyang2015** [comment]
I meet the same problem as you, do you find the method to solve it ?

**Comment by gongjiaqiang** [comment]
I also meet this same problem, how to solve it?

**Comment by KingfaLuis** [comment]
C:\Users\my\Desktop\Python\Django\onlineEducation\Mxonline3>python manage.py runserver 8002
Unhandled exception in thread started by <function check_errors.<locals>.wrapper at 0x0000000003E17400>
Traceback (most recent call last):
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\core\management\commands\runserver.py", line 113, in inner_run
    autoreload.raise_last_exception()
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 248, in raise_last_exception
    raise _exception[1]
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\core\management\__init__.py", line 327, in execute
    autoreload.check_errors(django.setup)()
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\utils\autoreload.py", line 225, in wrapper
    fn(*args, **kwargs)
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\__init__.py", line 24, in setup
    apps.populate(settings.INSTALLED_APPS)
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\apps\registry.py", line 89, in populate
    app_config = AppConfig.create(entry)
  File "g:\ProgramData\Anaconda3\lib\site-packages\django\apps\config.py", line 90, in create
    module = import_module(entry)
  File "g:\ProgramData\Anaconda3\lib\importlib\__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 994, in _gcd_import
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 953, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'captcha'

I'm try pip install captcha

**Comment by HauWong** [comment]
I have met the same problem now! so how do you solve it?

**Comment by willshion** [comment]
fukk the same

**Comment by Silence4Allen** [comment]
same as me

**Comment by HauWong** [comment]
Finally I have found the origin of my problem. That's the same name with the package I have given to my directory file. They are both named "captcha". So I guess some conflict occured between them.

**Comment by shshaoqqi** [comment]
haha  I think they have made the same problem as you
it's so awkward

**Comment by Schneey** [comment]
Maybe you've created a new python file named captach？
Just rename！

**Comment by ankitpatidar1** [comment]
i am facing same problem 
run command : `pip install  django-simple-captcha`
then add url in rout urls
`urlpatterns = [
    path('captcha/', `include('captcha.urls')),`
]`
then apply migrations
`python manage.py migrate`

**Comment by Akimaru666** [comment]
I was experiencing the same issue, turn out I was calling my file captcha.py xD third time I do this error.

**Comment by Nida-Canpolat** [comment]
Change the py filename

**Comment by ValeryKorobov** [comment]
I had the same problem, because the file with my script was called "captha.py" and conflicted with the package - captcha, which I imported in this file.

Just renamed to main.py file
