### ISSUE TITLE
Reshape error when using multi-cpu/gpu while single cpu/gpu is work.

### ISSUE THREAD

**Issue by zihaolucky** [dmlc/mxnet#3223]
Hi, I got a error message about `Reshape` Op when changing `ctx = mx.cpu()` to `ctx = [mx.cpu(i) for i in range(12)]`:

```
2016-09-05 17:06:40,815 Auto-select kvstore type = local_allreduce_cpu
2016-09-05 17:06:40,815 Start training with [cpu(0), cpu(1), cpu(2), cpu(3), cpu(4), cpu(5), cpu(6), cpu(7), cpu(8), cpu(9), cpu(10), cpu(11)]
[17:06:40] /home/xxx/packages/mxnet/dmlc-core/include/dmlc/logging.h:235: [17:06:40] src/operator/./reshape-inl.h:226: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided.
Traceback (most recent call last):
  File "text_cnn.py", line 399, in <module>
    main()
  File "text_cnn.py", line 395, in main
    epoch_end_callback = mx.callback.do_checkpoint(model_prefix, 1))  # save model every 10 epoch.
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 789, in fit
    sym_gen=self.sym_gen)
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 192, in _train_multi_device
    logger=logger)
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 311, in __init__
    self.slices, train_data)
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 224, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 97, in _bind_exec
    arg_shape, _, aux_shape = sym.infer_shape(**input_shapes)
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/zihao.zzh/anaconda2/envs/mxnet/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in reshape0: [17:06:40] src/operator/./reshape-inl.h:226: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided.
```

```python
 24     # embedding layer. static
 25     word_embed_static = mx.symbol.Embedding(data=data, input_dim=vocab_size,
 26                                             output_dim=embedding_size,
 27                                             name='word_embedding_static',
 28                                             attr={'lr_mult':'0.00'})  # control per-layer learning rate here.
 29     word_embed_static = mx.symbol.Reshape(data=word_embed_static,
 30                                           shape=(batch_size, 1, sentence_size, embedding_size))  # convolution layer needs 4D input.
```

```python
373     # model definition.
374     model = mx.model.FeedForward(ctx = mx.cpu(),
375                                  symbol = cnn,
376                                  num_epoch = num_epoch,
377                                  learning_rate = 0.0001,
378                                  optimizer   = 'rmsprop',
379                                  wd          = 0.00001,
380                                  initializer = initializer)  # now we have a simple custom initializer.
381
```

**Comment by piiswrong** [comment]
num cpu > batch_size?

**Comment by zihaolucky** [comment]
@piiswrong Nope.

```
2016-09-05 23:46:21,150 data shape: (184, 1, 20, 128)
2016-09-05 23:46:21,150 batch size: 128
2016-09-05 23:46:21,151 vocab size: 1002034
2016-09-05 23:46:21,151 with pretrained embedding.
2016-09-05 23:46:21,152 use dropout.
2016-09-05 23:46:21,152 num_domain_classes: 1
2016-09-05 23:46:21,153 num_intent_classes: 7
[23:46:21] src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
2016-09-05 23:46:21,158 Auto-select kvstore type = local_update_cpu
2016-09-05 23:46:21,158 Start training with [cpu(0), cpu(1), cpu(2), cpu(3), cpu(4), cpu(5)]
[23:46:21] src/operator/./reshape-inl.h:249: Using target_shape will be deprecated.
[23:46:21] /home/zihao.zzh/github/mxnet/dmlc-core/include/dmlc/logging.h:235: [23:46:21] src/operator/./reshape-inl.h:268: Check failed: oshape.Size() == dshape.Size() Target shape size is different to source. Target: 25600
Source: 4200
```

**Comment by zihaolucky** [comment]
@piiswrong I tested on some examples and haven't got such error. So I would check my code at first. thanks~

**Comment by zihaolucky** [comment]
Hi @piiswrong 

I add some code into `reshape-inl.h` to debug.

```c++
224         } else {
225           // great than 0, new shape
226           LOG(INFO) << "new_size:" << new_size << " proposed_dim:" << proposed_dim;
227           CHECK_EQ(new_size % proposed_dim, 0) << "Illegal dim setting, can't be divided. new_size:" << new_size << " proposed_dim:" << proposed_dim;
228           tmp.push_back(proposed_dim);
229           new_size /= proposed_dim;
230           // after set manual shape, can't keep same
231           if (param_.shape.info.size() != dshape.ndim()) {
232             keep = false;
233           } else {
234             src_idx++;
235           }
236         }
237       }
```

And I got these message, it seems that when we train in multi-devices, I guess MXNet would separate data into `num_cpu` chunks(where I can find these model parallel code?). But when we reshape these data, error happen. My `provide_data` shape is (32, 1, 20, 128)

```
[11:56:53] src/operator/./reshape-inl.h:226: new_size:81920 proposed_dim:32
[11:56:53] src/operator/./reshape-inl.h:226: new_size:2560 proposed_dim:1
[11:56:53] src/operator/./reshape-inl.h:226: new_size:2560 proposed_dim:20
[11:56:53] src/operator/./reshape-inl.h:226: new_size:128 proposed_dim:128
[11:56:53] src/operator/./reshape-inl.h:226: new_size:9600 proposed_dim:32
[11:56:53] src/operator/./reshape-inl.h:226: new_size:300 proposed_dim:300
2016-09-06 11:56:53,445 Auto-select kvstore type = local_allreduce_cpu
2016-09-06 11:56:53,445 Start training with [cpu(0), cpu(1)]
[11:56:53] src/operator/./reshape-inl.h:226: new_size:40960 proposed_dim:32
[11:56:53] src/operator/./reshape-inl.h:226: new_size:1280 proposed_dim:1
[11:56:53] src/operator/./reshape-inl.h:226: new_size:1280 proposed_dim:20
[11:56:53] src/operator/./reshape-inl.h:226: new_size:64 proposed_dim:128
[11:56:53] /home/zihao.zzh/github/mxnet/dmlc-core/include/dmlc/logging.h:235: [11:56:53] src/operator/./reshape-inl.h:227: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided. new_size:64 proposed_dim:128
Traceback (most recent call last):
  File "text_cnn.py", line 399, in <module>
    main()
  File "text_cnn.py", line 395, in main
    epoch_end_callback = mx.callback.do_checkpoint(model_prefix))  # save model every 10 epoch.
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 796, in fit
    sym_gen=self.sym_gen)
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 200, in _train_multi_device
    max_data_shape=max_data_shape)
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 343, in __init__
    self.slices, train_data, max_data_shape)
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 248, in __init__
    shared_data_arrays=self.shared_data_arrays[i])
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 102, in _bind_exec
    arg_shape, _, aux_shape = sym.infer_shape(**input_shapes)
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 453, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 513, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/home/zihao.zzh/packages/anaconda2/envs/cs224d/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferShape Error in reshape_for_embedding: [11:56:53] src/operator/./reshape-inl.h:227: Check failed: (new_size % proposed_dim) == (0) Illegal dim setting, can't be divided. new_size:64 proposed_dim:128
```

**Comment by zihaolucky** [comment]
So maybe I should check my DataIter and batch_size and my network definition, in which the batch_size is passed into, so it's static.

**Comment by zihaolucky** [comment]
I solve the problem, I should use -1 to replace batch_size in Reshape operation. :)
