### ISSUE TITLE
[Python]model.fit() doesn't work for input mx.io.NDArray, numpy.ndarray and mx.ndarray

### ISSUE THREAD

**Issue by bowenYu** [dmlc/mxnet#325]
The problem has bother me a few days, but I cannot find out how to fix it.

Here's the input_1:

data_numpy.shape = (3607, 1500)
label_numpy.shape = (3607,)

When I run the model.fit:

	model.fit(X = data_numpy, y = label_numpy)

It displayed:

[22:59:03] ./dmlc-core/include/dmlc/logging.h:208: [22:59:03] src/symbol/symbol.cc:103: Symbol.InterShapeKeyword argument name data not found.
Candidate arguments:
	[0]datelev
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]mlp_label

Traceback (most recent call last):
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 36, in <module>
    test1()
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 34, in test1
    model.fit(X = data_numpy, y = label_numpy)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 727, in fit
    self._init_params(input_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 558, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(data=input_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 306, in infer_shape
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 72, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:59:03] src/symbol/symbol.cc:103: Symbol.InterShapeKeyword argument name data not found.
Candidate arguments:
	[0]datelev
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]mlp_label

So I transform the input data as mx.ndarray, the run the fit() as:

    model.fit(X = mx.nd.array(data_numpy), y = label_numpy)

It reported:

Traceback (most recent call last):
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 36, in <module>
    test1()
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 34, in test1
    model.fit(X = mx.nd.array(data_numpy), y = label_numpy)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 718, in fit
    X = self._init_iter(X, y, is_train=True)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 611, in _init_iter
    if X.ndim != 2:
AttributeError: 'NDArray' object has no attribute 'ndim'

It still did not work, but it seems that the function model._init_iter(self, X, y, is_train) will check the 'ndim' attribute, but the mx.ndarray doesn't have.

Then I make a NDArrayIter as input:

	data_iter = mx.io.NDArrayIter(data_numpy, label_numpy, batch_size = 10)

and fit():

	model.fit(data_iter)

still:

[23:06:37] ./dmlc-core/include/dmlc/logging.h:208: [23:06:37] src/symbol/symbol.cc:103: Symbol.InterShapeKeyword argument name data not found.
Candidate arguments:
	[0]datelev
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]mlp_label

Traceback (most recent call last):
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 36, in <module>
    test1()
  File "/home/inkeyes/workspace/mxnet_test/test1/testMXNet.py", line 34, in test1
    model.fit(data_iter)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 727, in fit
    self._init_params(input_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 558, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(data=input_shape)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/symbol.py", line 306, in infer_shape
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 72, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:06:37] src/symbol/symbol.cc:103: Symbol.InterShapeKeyword argument name data not found.
Candidate arguments:
	[0]datelev
	[1]fc1_weight
	[2]fc1_bias
	[3]fc2_weight
	[4]fc2_bias
	[5]fc3_weight
	[6]fc3_bias
	[7]mlp_label

I am really need some help, thanks.

**Comment by tqchen** [comment]
The input variable have to be data, instead of datalev

**Comment by bowenYu** [comment]
@tqchen Thank you! It works!

**Comment by tqchen** [comment]
@bowenYu Do you think if you want to open a PR to improve the docstring and error message? So that others can benefit from you and do not get the error you have
