### ISSUE TITLE
Bucket iterator how to set bucket key and default_bucket_key

### ISSUE THREAD

**Issue by zhangjiulong** [dmlc/mxnet#3318]
I write an iterator using bucket and I want to transform seqlen and label len 
I set bucket_key and default_bucket_key as follows:
```
self.default_bucket_key =  [seq_len, label_num]
self.bucket_key = [seq_len, label_num]
```
then I got error like this:
```
Traceback (most recent call last):
  File "asr_bucket_ctc.py", line 313, in <module>
    batch_end_callback=mx.callback.Speedometer(batch_size, 5),epoch_end_callback = mx.callback.do_checkpoint(prefix))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 789, in fit
    sym_gen=self.sym_gen)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 192, in _train_multi_device
    logger=logger)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor_manager.py", line 317, in __init__
    self.execgrp_bucket = {train_data.default_bucket_key: self.execgrp}
TypeError: unhashable type: 'list'
```
But in the help of mxnet bucket is descripted that the key could be any thing
```
But in general, a bucket key could be anything. For example, in neural translation, since different combination of input-output sequence lengths correspond to different unrolling, the bucket key could be a pair of lengths
```
how could I do if I want to sed the key to combination of seq len and label len?

**Comment by zhangjiulong** [comment]
tuple could do it.

**Comment by R1ncy** [comment]
Hi, did you set them like this? 
```
self.default_bucket_key =  (seq_len, label_num)
self.bucket_key = (seq_len, label_num)
```

**Comment by zhangjiulong** [comment]
yes

**Comment by R1ncy** [comment]
Oh,  thanks. I set them like this but throws another error. I'll try to fix it.
