### ISSUE TITLE
how to extract the features of the entire image dataset (using model.predict)

### ISSUE THREAD

**Issue by chenboheng** [dmlc/mxnet#3358]
I want to extract the features of all the images in the entire image dataset.
And I use the following codes:

---------------------------------------------------------------------------------------------------------------------------------
import mxnet as mx
import numpy as np
import logging
import argparse
import os

parser = argparse.ArgumentParser(description='train an image classifer on imagenet')
parser.add_argument('--data-dir', type=str, default='/media/ResearchProject/deeplearning/code/mxnet-experiments/data/caltech101/',
                    help='the input data directory')
parser.add_argument('--batch-size', type=int, default=1,
                    help='the batch size')
parser.add_argument('--gpus', type=str,default='0',
                    help='the gpus will be used, e.g "0,1,2,3"')
parser.add_argument('--kv-store', type=str, default='device',
                    help='the kvstore type')
parser.add_argument('--num-examples', type=int, default=3657,
                    help='the number of training examples')
parser.add_argument('--num-classes', type=int, default=102,
                    help='the number of classes')
parser.add_argument('--train-dataset', type=str, default="train.rec",
                    help='train dataset name')
parser.add_argument('--val-dataset', type=str, default="test.rec",
                    help="validation dataset name")
parser.add_argument('--data-shape', type=int, default=256,
                    help='set image\'s shape')
args = parser.parse_args()

def get_iterator(args, kv):
    data_shape = (3, args.data_shape, args.data_shape)

    test = mx.io.ImageRecordIter(
        path_imgrec = os.path.join(args.data_dir, args.val_dataset),
        mean_img=args.data_dir + 'mean.bin',
        rand_crop   = False,
        rand_mirror = False,
        data_shape  = data_shape,
        batch_size  = args.batch_size,
        num_parts   = kv.num_workers,
        part_index  = kv.rank)

    return test

kv = mx.kvstore.create(args.kv_store)

(test) = get_iterator(args, kv)
devs = mx.cpu() if args.gpus is None else [
    mx.gpu(int(i)) for i in args.gpus.split(',')]

prefix='models/vgg16'
numround=1
model=mx.model.FeedForward.load(prefix=prefix,epoch=numround)

prob=model.predict(X=test)
---------------------------------------------------------------------------------------------------------------------------------

But some errors happen:
---------------------------------------------------------------------------------------------------------------------------------
/usr/bin/python2.7 /media/ResearchProject/deeplearning/code/mxnet-experiments/model_predict.py
[15:59:59] src/io/iter_image_recordio.cc:209: ImageRecordIOParser: /media/ResearchProject/deeplearning/code/mxnet-experiments/data/caltech101/test.rec, use 3 threads for decoding..
[15:59:59] src/io/./iter_normalize.h:103: Load mean image from /media/ResearchProject/deeplearning/code/mxnet-experiments/data/caltech101/mean.bin
[16:00:00] /media/ResearchProject/deeplearning/software/mxnet/dmlc-core/include/dmlc/logging.h:235: [16:00:00] src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "/media/ResearchProject/deeplearning/code/mxnet-experiments/model_predict.py", line 56, in <module>
    prob=model.predict(X=test)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 597, in predict
    self._init_predictor(data_shapes)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 529, in _init_predictor
    pred_exec.copy_params_from(self.arg_params, self.aux_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/executor.py", line 235, in copy_params_from
    array.astype(dst.dtype).copyto(dst)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 499, in copyto
    return _internal._copyto(self, out=other)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 1174, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [16:00:00] src/ndarray/ndarray.cc:291: Check failed: from.shape() == to->shape() operands shape mismatch

Process finished with exit code 1

---------------------------------------------------------------------------------------------------------------------------------

All the test images of the entire image dataset are converted to test.rec. How can I solve this problem or how I can find the correct way to extract the features of all the images in an entire image dataset?

**Comment by chenboheng** [comment]
when the above test.rec is the cifar10.zip downloaded from the dmlc, the above code run correctly. When I use my own dataset. The error will be existed. How can I solve this problem?
