### ISSUE TITLE
[document] Python Symbol APIs disappeared again

### ISSUE THREAD

**Issue by minazou** [dmlc/mxnet#3446]
Hi,
The doc of Symbol APIs on [http://mxnet.io/packages/python/symbol.html](http://mxnet.io/packages/python/symbol.html) disappeared again.
It might be overwritten by some autogeneration tool.
Could you help fixing it?
Thank you.

**Comment by antinucleon** [comment]
Thank you for letting us know. We are investigating this issue.

**Comment by mli** [comment]
it is broken since http://mxnet.io:8080/job/mxnet/55/console

it's due to #3429 @sxjscience can you fix it? 

```
/var/lib/jenkins/workspace/mxnet/docs/packages/python/symbol.md:1: WARNING: autodoc: failed to import module u'mxnet.symbol'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/var/lib/jenkins/workspace/mxnet/docs/../python/mxnet/__init__.py", line 50, in <module>
    from . import test_utils
  File "/var/lib/jenkins/workspace/mxnet/docs/../python/mxnet/test_utils.py", line 7, in <module>
    from numpy.testing import assert_allclose, build_err_msg
ImportError: No module named testing
/var/lib/jenkins/workspace/mxnet/docs/packages/python/symbol.md:1: WARNING: autodoc: failed to import module u'mxnet.executor'; the following exception was raised:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/sphinx/ext/autodoc.py", line 385, in import_object
    __import__(self.modname)
  File "/var/lib/jenkins/workspace/mxnet/docs/../python/mxnet/__init__.py", line 8, in <module>
    from . import base
ImportError: cannot import name base
```

**Comment by sxjscience** [comment]
@minazou The doc is fixed.

**Comment by minazou** [comment]
@sxjscience thank you so much. :)
