### ISSUE TITLE
training on multiple machines error

### ISSUE THREAD

**Issue by zhonghh** [dmlc/mxnet#3448]
try to train on 2 machines using command: 
../../tools/launch.py -n 2 -H hosts --sync-dst-dir /tmp/mxnet python /tmp/mxnet/train_mnist.py --network lenet --kv-store dist_sync

And I was asked to input ssh password multiple times and eventually it shows error msg:
2016-10-04 20:00:07,614 INFO rsync /media/ucar/3a6142db-a49f-45b3-bdf4-27766e3ec89e/huazhong/mxnet/example/image-classification/ -> 10.110.0.211:/tmp/mxnet
ucar@10.110.0.211's password:
2016-10-04 20:00:13,823 INFO rsync /media/ucar/3a6142db-a49f-45b3-bdf4-27766e3ec89e/huazhong/mxnet/example/image-classification/ -> 10.110.0.212:/tmp/mxnet
ucar@10.110.0.212's password:
ucar@10.110.0.211's password: ucar@10.110.0.212's password: ucar@10.110.0.212's password: ucar@10.110.0.211's password:
Permission denied, please try again.
ucar@10.110.0.211's password:
Permission denied, please try again.
ucar@10.110.0.212's password:
Permission denied, please try again.
ucar@10.110.0.212's password:

Permission denied, please try again.
ucar@10.110.0.211's password:

Permission denied, please try again.
ucar@10.110.0.212's password:

Permission denied (publickey,password).
Exception in thread Thread-2:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/ucar/3a6142db-a49f-45b3-bdf4-27766e3ec89e/huazhong/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.110.0.211 -p 22 'export LD_LIBRARY_PATH=/usr/local/lib/python2.7/dist-packages/tensorflow/core/user_ops:/usr/local/cuda/lib64; export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9091; export DMLC_PS_ROOT_URI=10.110.0.211; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /tmp/mxnet; python /tmp/mxnet/train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 255

Permission denied (publickey,password).
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/media/ucar/3a6142db-a49f-45b3-bdf4-27766e3ec89e/huazhong/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.110.0.212 -p 22 'export LD_LIBRARY_PATH=/usr/local/lib/python2.7/dist-packages/tensorflow/core/user_ops:/usr/local/cuda/lib64; export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9091; export DMLC_PS_ROOT_URI=10.110.0.211; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /tmp/mxnet; python /tmp/mxnet/train_mnist.py --network lenet --kv-store dist_sync'' returned non-zero exit status 255

I can see in the two machines, the /tmp/mxnet/ folder is copied correctly. And in ps, there are multiple "python /tmp/mxnet/train_mnist.py" processes, actually 13 on each machine. But seems they are all zombie processes. 

Anyone know what's wrong?

**Comment by piiswrong** [comment]
you need to setup ssh keys first

**Comment by zhonghh** [comment]
so username/password doesn't work? I have to set public/private key for ssh connection, is that right?

**Comment by zhonghh** [comment]
I can use username/password to remotely start a training process. I suspect it is PS server that requires key-based authentication for SSH, is that right?

**Comment by zhonghh** [comment]
Ok, after setting up the key-based authentication for ssh among all the machines in the cluster (default id_rsa key file), now it works.

**Comment by jeejeeli** [comment]
I have 2 machines too, same problem,can you tell me how solver this problem detailed ？thank you very much
