### ISSUE TITLE
NDArray error after install mxnet

### ISSUE THREAD

**Issue by FreemanX** [dmlc/mxnet#3553]
Hi, I installed mxnet with the latest commit(cf00ca064d5f6e46b062c2027ae2905c6147a04c) in our server and the code works fine before can't run now.
Error message:
Start training...
Traceback (most recent call last):
  File "train_rnn.py", line 155, in <module>
    optimizer_params={'learning_rate': learning_rate, 'momentum': momentum, 'wd': 0.00001})
  File "/home/comp/pengfeixu/.local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 358, in fit
    self.update_metric(eval_metric, data_batch.label)
  File "/home/comp/pengfeixu/.local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 453, in update_metric
    self._exec_group.update_metric(eval_metric, labels)
  File "/home/comp/pengfeixu/.local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 391, in update_metric
    labels_slice.append(label.copy_slice_to(axis, islice.start,
AttributeError: 'NDArray' object has no attribute 'copy_slice_to'

**Comment by piiswrong** [comment]
@pluskid

**Comment by pluskid** [comment]
Thanks for reporting this! Should be fixed after #3564 is merged.
