### ISSUE TITLE
Why resnet params have GPU specific but not generic?

### ISSUE THREAD

**Issue by zhenlinluo** [dmlc/mxnet#3562]
I am using resnet pretrained model to test resnet on CPU. http://data.dmlc.ml/mxnet/models/imagenet/resnet/ 

However, it will report error like below:

Traceback (most recent call last): 
  File "train_imagenet_scoring.py", line 87, in <module> 
    loaded = mx.model.FeedForward.load(args.model_params, 1) 
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 835, in load 
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch) 
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 361, in load_checkpoint 
    save_dict = nd.load('%s-%04d.params' % (prefix, epoch)) 
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 983, in load 
    ctypes.byref(names))) 
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call 
    raise MXNetError(py_str(_LIB.MXGetLastError())) 
mxnet.base.MXNetError: [00:35:20] src/ndarray/ndarray.cc:347: GPU is not enabled

**Comment by piiswrong** [comment]
@winstywang Please update model to convert to cpu before saving

**Comment by mli** [comment]
an easy fix is 

```python
ctx = mx.cpu()
new_args = dict()
new_auxs = dict()
for k, v in arg_params.items():
    new_args[k] = v.as_in_context(ctx)
for k, v in aux_params.items():
    new_auxs[k] = v.as_in_context(ctx)
```

**Comment by tornadomeet** [comment]
@zhenlinluo all the resnet model saved to cpu now, please check it~
