### ISSUE TITLE
Deepmark not working for current change

### ISSUE THREAD

**Issue by zhenlinluo** [dmlc/mxnet#3605]
[13:16:23] /home/zhenlin/Mxnet/upstream/mxnet/mxnet/dmlc-core/include/dmlc/logging.h:235: [13:16:23] src/operator/./convolution-inl.h:433: Check failed: (dtype) != (-1) First input must have specified type
Traceback (most recent call last):
  File "benchmark.py", line 91, in <module>
    kvstore=args.kv_store, batch_size=args.batch_size)
  File "benchmark.py", line 31, in get_module
    mod.bind(data_shapes=provide_data, label_shapes=provide_label, for_training=True, inputs_need_grad=False)
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 265, in bind
    grad_req=grad_req)
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 173, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 213, in bind_exec
    self.execs.append(self._bind_ith_exec(i, data_shapes, label_shapes, shared_group))
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/executor_group.py", line 442, in _bind_ith_exec
    arg_types, _, aux_types = self.symbol.infer_type(**input_types)
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 417, in infer_type
    ctypes.byref(complete)))
  File "/root/anaconda2/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: InferType Error in convolution0: [13:16:23] src/operator/./convolution-inl.h:433: Check failed: (dtype) != (-1) First input must have specified type

**Comment by piiswrong** [comment]
should be fixed by https://github.com/dmlc/mxnet/pull/3606
