### ISSUE TITLE
convert model from caffe failed

### ISSUE THREAD

**Issue by FlyingZXC** [dmlc/mxnet#3627]
When I convert the vgg16 net, an error happened, as follows:
python convert_model.py VGG_ILSVRC_16_layers_deploy.prototxt VGG_ILSVRC_16_layers.caffemodel vgg16
Traceback (most recent call last):
  File "convert_model.py", line 110, in <module>
    main()
  File "convert_model.py", line 37, in main
    prob, input_dim = proto2symbol(args.caffe_prototxt)
  File "D:\git-checkout\mxnet\tools\caffe_converter\convert_symbol.py", line 198, in proto2symbol
    exec(sym)
  File "<string>", line 7, in <module>
  File "E:\Programs\Anaconda3\envs\py27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\symbol.py", line 1062, in creator
    ctypes.byref(sym_handle)))
  File "E:\Programs\Anaconda3\envs\py27\lib\site-packages\mxnet-0.7.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Cannot find argument 'pooling_convention', Possible Arguments:
----------------
global_pool : boolean, optional, default=False
    Ignore kernel size, do global pooling based on current input feature map. This is useful for input with different shape
kernel : Shape(tuple), required
    pooling kernel size: (y, x)
pool_type : {'avg', 'max', 'sum'}, required
    Pooling type to be applied.
stride : Shape(tuple), optional, default=(1,1)
    stride: for pooling (y, x)
pad : Shape(tuple), optional, default=(0,0)
    pad for pooling: (y, x)

In ReadMe.md, it is said that "The user needs to add padding to stride-2 pooling to make this work right now."

Anyone know how to add that padding?

**Comment by FlyingZXC** [comment]
I used the caffe_convert.py from an older version(0.5) and the process ran well, though with few warnings.
