### ISSUE TITLE
[R] Error with multi device training with GPUs in R

### ISSUE THREAD

**Issue by miguelgfierro** [dmlc/mxnet#3633]
There is an error when training in multi device in R. The same in python works well. The behavior is different if training with 1 GPU or with several.
- When training with 1 GPU:
  All the load goes to only one of the hosts. It trains correctly but I see 2 processes in `nvidia-smi` in one host and 0 precesses in the other. Also the processes are not eliminated after the computation is finished. I had to kill them manually.
- When training with several GPUs:
  It is not working, I tried with different batch sizes and with synchronous and asynchronous distribution. I get the following error:

``` bash
 *** caught segfault ***
address 0x38, cause 'memory not mapped'
Traceback:
 1: .External(list(name = "CppMethod__invoke_void", address = <pointer: 0xe69890>,     dll = list(name = "Rcpp", path = "/usr/lib64/microsoft-r/8.0/lib64/R/library/Rcpp/libs/Rcpp.so",         dynamicLookup = TRUE, handle = <pointer: 0x1bb0180>,         info = <pointer: 0x7f37b0d6e4c0>), numParameters = -1L),     <pointer: 0x3849900>, <pointer: 0x384af10>, .pointer, ...)
 2: kvstore$set.optimizer(optimizer)
 3: mx.model.train(symbol, ctx, input.shape, params$arg.params, params$aux.params,     begin.round, num.round, optimizer = optimizer, train.data = X,     eval.data = eval.data, metric = eval.metric, epoch.end.callback = epoch.end.callback,     batch.end.callback = batch.end.callback, kvstore = kvstore,     verbose = verbose)
 4: mx.model.FeedForward.create(X = train, eval.data = val, ctx = devs,     symbol = network, eval.metric = mx.metric.accuracy, num.round = args$num_round,     learning.rate = args$lr, momentum = 0.9, wd = 1e-05, kvstore = args$kv_store,     array.batch.size = args$batch_size, epoch.end.callback = checkpoint,     batch.end.callback = mx.callback.log.train.metric(50))
 5: train_model.fit(args, net, get_iterator(data_shape))
aborting ...
sh: line 1: 36432 Segmentation fault      (core dumped)
[18:21:34] /home/hoaphumanoid/repo/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:21:34] /home/hoaphumanoid/repo/mxnet/ps-lite/include/ps/internal/van.h:55: Check failed: ready_ call Start() first
Error in eval(substitute(expr), envir, enclos) :
  [18:21:34] /home/hoaphumanoid/repo/mxnet/ps-lite/include/ps/internal/van.h:55: Check failed: ready_ call Start() first
Calls: train_model.fit ... mx.model.FeedForward.create -> mx.model.train -> <Anonymous> -> .External
Execution halted
[18:21:34] /home/hoaphumanoid/repo/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:21:34] /home/hoaphumanoid/repo/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
[[18:21:34[18:21:34] /home/hoaphumanoid/repo/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:21:34] /home/hoaphumanoid/repo/mxnet/mshadow/mshadow/./stream_gpu-inl.h:98: Check failed: (err) == (CUBLAS_STATUS_SUCCESS) Create cublas handle failed
terminate called after throwing an instance of 'dmlc::Error'
] /home/hoaphumanoid/repo/mxnet/dmlc-core/include/dmlc/logging.h:235: [18:21:34] /home/hoaphumanoid/repo/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
  what():  [18:21:34] /home/hoaphumanoid/repo/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: (err) == (CUDNN_STATUS_SUCCESS) CUDNN_STATUS_INTERNAL_ERROR
terminate called recursively
terminate called recursively
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/hoaphumanoid/repo/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 363, in <lambda>
    target=(lambda: subprocess.check_call(self.cmd, env=env, shell=True)), args=())
  File "/usr/lib/python2.7/subprocess.py", line 541, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'Rscript train_mnist.R --model-prefix mnist_test --kv-store dist_async --gpus 0,1 --batch-size 1' returned non-zero exit status -6
```

**Comment by miguelgfierro** [comment]
I think this is solved https://github.com/Azure/batch-shipyard/tree/master/recipes/MXNet-GPU

Feel free to open again if needed
