### ISSUE TITLE
Python 3 encoding error in operator.CustomOpPropInfo.creator

### ISSUE THREAD

**Issue by peterzcc** [dmlc/mxnet#3683]
I've encountered the following error using python 3
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 234, in 'calling callback function'
  File "/home/data/czeng/mxnet/python/mxnet/operator.py", line 602, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() keywords must be strings
```

The following modification seems to bypass the error:
```
        def creator(op_type, argc, keys, vals, ret):
            """internal function"""
            assert py_str(op_type) == reg_name
            kwargs = dict([(keys[i].decode("utf-8"), vals[i].decode("utf-8")) for i in range(argc)]) #changed this line
```

**Comment by piiswrong** [comment]
The python2/3 compatible way of doing this is to use `mx.base.py_str(keys[i])`
Thanks for catching this. Would you like to submit a fix

**Comment by peterzcc** [comment]
OK sure. I will try to submit a pull request.

**Comment by peterzcc** [comment]
#3694
