### ISSUE TITLE
Problem with Finetune

### ISSUE THREAD

**Issue by GMarzinotto** [dmlc/mxnet#3812]
Good Evening,

I need to fine-tune a network, for the moment I'm trying to finetune VGG16 model changing the last layer to adapt it to my case with 3 output classes. 

To do so, I try to use the finetune-api from a forked repo from @taoari : 
[https://github.com/taoari/mxnet](https://github.com/taoari/mxnet)

I clone it recursively and install it as done with standard mxnet. using CUDA and CUDNN lastest versions.
I create a yml file similar to the examples.

But it fails due to a shape verification error.
The full stacktrace is given bellow.

I would really appreciate some insight in the issue. 
I am also interested if somebody could explain me other ways of performing fine-tuning in MXnet

Thank you very much in advance!

YML FILE

`
network: vgg16

data_dir: /media/Datarecords/size224
dataset: size224
#data_shape: 300
num_classes: 3
num_examples: 3060
batch_size: 25

lr: 0.0005
lr_factor: 0.1
lr_factor_epoch: 320
momentum: 0.9
wd: 0.0005

num_epochs: 800
kv_store: local

model_prefix: finetune_clothes_inception
finetune_from: /home/gabriel/MXNet/mxnet/pretrained_models/VGG16/VGG_FC_ILSVRC_16_layers-0074.params
checkpoint_epoch: 80
eval_epoch: 16
`

The I run ~/MXNet/mxnet_finetune_api/example/finetune-api$ python ./train_imagenet.py --solver finetuneconfig.yml --gpus 0 

and I get the following output

Namespace(gpus='0', load_epoch=None, log_file='auto', solver='finetuneconfig.yml')
2016-11-13 19:51:17,733 Node[0] Start with arguments:
2016-11-13 19:51:17,733 Node[0]     batch_size: 25
2016-11-13 19:51:17,733 Node[0]     checkpoint_epoch: 80
2016-11-13 19:51:17,733 Node[0]     clip_gradient: 5.0
2016-11-13 19:51:17,733 Node[0]     data_dir: /media/Datarecords/size224
2016-11-13 19:51:17,733 Node[0]     data_shape: 224
2016-11-13 19:51:17,733 Node[0]     dataset: size224
2016-11-13 19:51:17,733 Node[0]     display: 50
2016-11-13 19:51:17,733 Node[0]     encoding: .jpg
2016-11-13 19:51:17,733 Node[0]     epoch_size: None
2016-11-13 19:51:17,733 Node[0]     eval_epoch: 16
2016-11-13 19:51:17,733 Node[0]     eval_initialization: True
2016-11-13 19:51:17,733 Node[0]     eval_metric: acc,ce
2016-11-13 19:51:17,733 Node[0]     finetune_from: /home/gabriel/MXNet/mxnet_finetune_api/pretrained_models/VGG16/VGG_FC_ILSVRC_16_layers-0074.params
2016-11-13 19:51:17,733 Node[0]     gpus: 0
2016-11-13 19:51:17,734 Node[0]     initializer: default
2016-11-13 19:51:17,734 Node[0]     kv_store: local
2016-11-13 19:51:17,734 Node[0]     load_epoch: None
2016-11-13 19:51:17,734 Node[0]     log_file: auto
2016-11-13 19:51:17,734 Node[0]     lr: 0.0005
2016-11-13 19:51:17,734 Node[0]     lr_factor: 0.1
2016-11-13 19:51:17,734 Node[0]     lr_factor_epoch: 320
2016-11-13 19:51:17,734 Node[0]     max_size: 0
2016-11-13 19:51:17,734 Node[0]     mean_values: None
2016-11-13 19:51:17,734 Node[0]     min_size: 0
2016-11-13 19:51:17,734 Node[0]     model_prefix: finetune_vgg
2016-11-13 19:51:17,734 Node[0]     momentum: 0.9
2016-11-13 19:51:17,734 Node[0]     monitor: None
2016-11-13 19:51:17,734 Node[0]     network: vgg16
2016-11-13 19:51:17,734 Node[0]     network_kwargs: {}
2016-11-13 19:51:17,734 Node[0]     num_classes: 3
2016-11-13 19:51:17,734 Node[0]     num_epochs: 800
2016-11-13 19:51:17,734 Node[0]     num_examples: 3060
2016-11-13 19:51:17,734 Node[0]     pad: 0
2016-11-13 19:51:17,734 Node[0]     random_skip_ratio: 0
2016-11-13 19:51:17,734 Node[0]     scale: 1.0
2016-11-13 19:51:17,734 Node[0]     train_dataset: train.rec
2016-11-13 19:51:17,735 Node[0]     val_dataset: val.rec
2016-11-13 19:51:17,735 Node[0]     wd: 0.0005
2016-11-13 19:51:17,737 Node[0] Running on machine: gabriel-N751JX
2016-11-13 19:51:17,737 Node[0] finetuning from /home/gabriel/MXNet/mxnet_finetune_api/pretrained_models/VGG16/VGG_FC_ILSVRC_16_layers-0074.params
2016-11-13 19:51:18,228 Node[0] Reinitialize parameter arg:prob_label
[19:51:18] src/io/iter_image_recordio.cc:209: ImageRecordIOParser: /media/Datarecords/size224/train.rec, use 3 threads for decoding..
[19:51:20] src/io/iter_image_recordio.cc:209: ImageRecordIOParser: /media/Datarecords/size224/val.rec, use 3 threads for decoding..
2016-11-13 19:51:23,095 Node[0] Skip parameter arg:fc8_weight
2016-11-13 19:51:23,096 Node[0] Skip parameter arg:fc8_bias
2016-11-13 19:51:23,096 Node[0] Reinitialize parameter arg:fc8_size224_weight
2016-11-13 19:51:23,096 Node[0] Reinitialize parameter arg:fc8_size224_bias
[19:51:23] /home/gabriel/MXNet/mxnet_finetune_api/dmlc-core/include/dmlc/logging.h:235: [19:51:23] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "./train_imagenet.py", line 77, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/gabriel/MXNet/mxnet_finetune_api/example/finetune-api/train_model.py", line 189, in fit
    epoch_end_callback = [checkpoint])
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/model.py", line 799, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/model.py", line 548, in _init_params
    arg_params[k][:] = self.arg_params[k][:]
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/ndarray.py", line 221, in __setitem__
    value.copyto(self)
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/ndarray.py", line 472, in copyto
    return _internal._copyto(self, out=other)
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/ndarray.py", line 1147, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/home/gabriel/MXNet/mxnet_finetune_api/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:51:23] src/ndarray/ndarray.cc:227: Check failed: from.shape() == to->shape() operands shape mismatch

**Comment by piiswrong** [comment]
https://github.com/dmlc/mxnet-notebooks/blob/master/python/how_to/finetune.ipynb

**Comment by taoari** [comment]
@GMarzinotto https://github.com/dmlc/mxnet-notebooks/blob/master/python/how_to/finetune.ipynb is a good example, but if you do not want to write code. Please use this branch:

https://github.com/taoari/mxnet/tree/finetune-api-20160726-round2

You may also need to first merge https://github.com/taoari/mxnet/tree/src-dev-20160726-round2 if you are using Inception-BN model, there are certain fixes for BatchNorm. But if you are happy with VGG, the merge is not necessary.

I am not rebasing on a newer version of MXNet, because I find that it is actually much slower than the old version (not sure if this is fixed on current latest).

I assume you converted the .rec files correctly, then here is a tested `solver.yml`:

```
network: vgg16
model_prefix: caltech101_finetune_vgg16
finetune_from: ../share/vgg/vgg16-0001.params

dataset: caltech101
data_dir: ../data/caltech101
train_dataset: train_ori.rec
val_dataset: val_ori.rec

data_shape: 3,224,224
num_classes: 102
num_examples: 3060
batch_size: 25

mean_values: 123,117,104
min_size: 256

lr: 0.0005
lr_factor: 0.1
lr_factor_epoch: 160
momentum: 0.9
wd: 0.0005

display: 50
eval_epoch: 8
checkpoint_epoch: 80
num_epochs: 400 # 2.5x lr_factor_epoch

kv_store: local
initializer: msra
```

Then use the following command to train:

```
python train_rec.py --solver solver.yml --gpus 0
```

**Comment by GMarzinotto** [comment]
Perfect now it works, thank now I'm able to use finetuning using the example on the notebook!

**Comment by mli** [comment]
also added https://github.com/dmlc/mxnet/blob/master/example/image-classification/fine-tune.py
