### ISSUE TITLE
Error running Profiler in NNVM branch

### ISSUE THREAD

**Issue by Luo-Liang** [dmlc/mxnet#3972]
Hey! 

I'm checking out the new profiler in the NNVM branch, however when I run python profiler_executor.py, I get the following error. I had compiled with USE_PROFILER=1 flag.

````
Traceback (most recent call last):
  File "profiler_executor.py", line 141, in <module>
    executor_time = executor(args.iter_num)
  File "profiler_executor.py", line 131, in executor
    mod = get_module(ctx, sym, provide_data, provide_label, batch_size=128)
  File "profiler_executor.py", line 90, in get_module
    'wd': 0.0
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/module/module.py", line 339, in init_optimizer
    **optimizer_params)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 51, in create_optimizer
    **kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 391, in __init__
    super(ccSGD, self).__init__(*args, **kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 222, in __init__
    super(SGD, self).__init__(**kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 79, in __init__
    self.set_lr_mult({})
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 106, in set_lr_mult
    attr = self.sym.attr_dict()
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/symbol.py", line 293, in attr_dict
    name, key = py_str(pairs[i*2]).split('$')
ValueError: need more than 1 value to unpack
````

**Comment by ZihengJiang** [comment]
Thank you! I'll take a look

**Comment by piiswrong** [comment]
try git submodule update

**Comment by Luo-Liang** [comment]
Thanks for replying, but I did that and am still seeing the same problem :/

````
ubuntu@ip-172-31-30-187:~/mxnet-nnvm/mxnet$ git submodule init
ubuntu@ip-172-31-30-187:~/mxnet-nnvm/mxnet$ git submodule update
ubuntu@ip-172-31-30-187:~/mxnet-nnvm/mxnet$ git pull
Already up-to-date.
ubuntu@ip-172-31-30-187:~/mxnet-nnvm/mxnet$ cd example/profiler/
ubuntu@ip-172-31-30-187:~/mxnet-nnvm/mxnet/example/profiler$ python profiler_executor.py
libdc1394 error: Failed to initialize libdc1394
profile file save to profile_executor_5iter.json
executor num_iteration: 5
Traceback (most recent call last):
  File "profiler_executor.py", line 141, in <module>
    executor_time = executor(args.iter_num)
  File "profiler_executor.py", line 131, in executor
    mod = get_module(ctx, sym, provide_data, provide_label, batch_size=128)
  File "profiler_executor.py", line 90, in get_module
    'wd': 0.0
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/module/module.py", line 339, in init_optimizer
    **optimizer_params)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 51, in create_optimizer
    **kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 391, in __init__
    super(ccSGD, self).__init__(*args, **kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 222, in __init__
    super(SGD, self).__init__(**kwargs)
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 79, in __init__
    self.set_lr_mult({})
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/optimizer.py", line 106, in set_lr_mult
    attr = self.sym.attr_dict()
  File "/home/ubuntu/mxnet-nnvm/mxnet/python/mxnet/symbol.py", line 293, in attr_dict
    name, key = py_str(pairs[i*2]).split('$')
ValueError: need more than 1 value to unpack
````

**Comment by ZihengJiang** [comment]
I just tried the newest commit, and it works on my machine also. Could you paste the result of `git status`? And have you tried `make clean; make -j8; cd python; python setup.py install --force`?
