### ISSUE TITLE
TypeError: unhashable type: 'list'

### ISSUE THREAD

**Issue by R1ncy** [dmlc/mxnet#4059]
Hi, I build a multi input and output model and write a data iterator for it.
For the inputs and outputs in the model, I define them like this:
```
data1 = mx.sym.Variable('data1')
data2 = mx.sym.Variable('data2')
label1 = mx.sym.Variable('softmax_label1')
label2 = mx.sym.Variable('softmax_label2')
...
fc1 = mx.symbol.FullyConnected(data=dp_out, num_hidden=2, name='fc1', attr={'wd_mult': '0.00005'})
sm1 = mx.symbol.SoftmaxOutput(data=fc1, name='softmax1', label = label1)
fc2 = mx.symbol.FullyConnected(data=dp_out, num_hidden=2, name='fc2', attr={'wd_mult': '0.00005'})
sm2 = mx.symbol.SoftmaxOutput(data=fc2, name='softmax2', label = label2)
return mx.sym.Group([sm1,sm2])
```

And the dataiter is here.
https://github.com/R1ncy/MxnetStudy/blob/master/monolingual_multiinput_iter.py
But when I run it, throw this error.
```
Traceback (most recent call last):
  File "F:/shiryo/cross-lingual/experiment/mxnet/Multi_Input_Model_Test/multi_input_dcnn.py", line 206, in <module>
    train_dcnn(args, ctx)
  File "F:/shiryo/cross-lingual/experiment/mxnet/Multi_Input_Model_Test/multi_input_dcnn.py", line 170, in train_dcnn
    num_epoch=args.num_epoch)
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\module\base_module.py", line 333, in fit
    for_training=True, force_rebind=force_rebind)
  File "D:\Anaconda3\lib\site-packages\mxnet-0.7.0-py3.5.egg\mxnet\module\bucketing_module.py", line 183, in bind
    self._buckets[self._default_bucket_key] = module
TypeError: unhashable type: 'list'
```
Is there something wrong with my dataiter? How to fix it? 
Thanks a lot.

**Comment by Mandiramurthy** [comment]
How u can install this software there is an error while downloading

**Comment by R1ncy** [comment]
downloading? I didn't download anything

**Comment by R1ncy** [comment]
solve it

**Comment by bkwwangjie** [comment]
> solve it

Hello, I have also encountered this problem.I want to ask you how to solve it? Can you send me the code?
