### ISSUE TITLE
neural-style example run error without gpu

### ISSUE THREAD

**Issue by M2shad0w** [dmlc/mxnet#4112]
```
neural-style git:(master) ✗ python run.py --content-image input/IMG_4343.jpg --style-image input/starry_night.jpg --gpu 0
/Users/m2shad0w/miniconda2/lib/python2.7/site-packages/matplotlib/font_manager.py:273: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
[14:22:06] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
[14:22:06] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
[14:22:06] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
[14:22:06] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
[14:22:06] src/operator/./reshape-inl.h:311: Using target_shape will be deprecated.
[14:22:06] /Users/m2shad0w/Documents/gitdoc/mxnet/dmlc-core/include/dmlc/logging.h:235: [14:22:06] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
Traceback (most recent call last):
  File "run.py", line 152, in <module>
    model_executor = model_module.get_executor(gram, content, size, dev)
  File "/Users/m2shad0w/Documents/gitdoc/mxnet/example/neural-style/model_vgg19.py", line 53, in get_executor
    arg_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=ctx) for shape in arg_shapes]))
  File "/Users/m2shad0w/Documents/gitdoc/mxnet/python/mxnet/ndarray.py", line 876, in zeros
    arr = empty(shape, ctx, dtype)
  File "/Users/m2shad0w/Documents/gitdoc/mxnet/python/mxnet/ndarray.py", line 612, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False, dtype))
  File "/Users/m2shad0w/Documents/gitdoc/mxnet/python/mxnet/ndarray.py", line 69, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/Users/m2shad0w/Documents/gitdoc/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:22:06] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage
```

my os is ei `10.11.6` and no N card, so install mxnet without gpu enabled, how can i fix it?
![image](https://cloud.githubusercontent.com/assets/3387446/20915296/f83a51a4-bbbf-11e6-8262-96cdf400790b.png)

**Comment by M2shad0w** [comment]
sorry run 
```
python run.py --content-image input/IMG_4343.jpg --style-image input/starry_night.jpg --gpu -1
```
fix
