### ISSUE TITLE
Example train_mnist.py failed to run

### ISSUE THREAD

**Issue by geraint0923** [dmlc/mxnet#4149]
When I run
```
python example/image-classification/train_mnist.py --network lenet --gpus 0                                                                                                 
```
I got
```
Traceback (most recent call last):
  File "example/image-classification/train_mnist.py", line 73, in <module>
    sym = net.get_symbol(**vars(args))
  File "/home/tester/mxnet/example/image-classification/symbol/lenet.py", line 10, in get_symbol
    if(add_stn):
NameError: global name 'add_stn' is not defined
```
I remember this worked three weeks ago. And I saw there is a large refactor in `train_mnist.py`, is that related? Thanks.

**Comment by jostep** [comment]
This has been fixed by PR #4148
