### ISSUE TITLE
src/./zmq_van.h:122: there is no socket to node 9 

### ISSUE THREAD

**Issue by wsybupt** [dmlc/mxnet#4156]
For bugs or installation issues, please provide the following information.
The more information you provide, the more likely people will be able to help you.

## Environment info
Operating System:Ubuntu 14.04

Compiler: gcc

Package used (Python/R/Scala/Julia):python  python2.7

MXNet commit hash (`git rev-parse HEAD`):e036c24632fa6ed66b0f152df8902e3e2d997293

## Error Message:
Please paste the full error message, including stack trace.
```
spark@sparkMachine1:~/mxnet/example/HCL2000$ ../../tools/launch.py -n 3 -H hosts python train_hcl.py --kv-store dist_sync
[20:57:18] src/./zmq_van.h:122: there is no socket to node 9
[20:57:18] /home/spark/mxnet/dmlc-core/include/dmlc/logging.h:235: [20:57:18] src/van.cc:126: Check failed: (send_bytes) != (-1) 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [20:57:18] src/van.cc:126: Check failed: (send_bytes) != (-1) 
Aborted (core dumped)
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 763, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/spark/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 363, in <lambda>
    target=(lambda: subprocess.check_call(self.cmd, env=env, shell=True)), args=())
  File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'python train_hcl.py --kv-store dist_sync' returned non-zero exit status 134
```

## Steps to reproduce
or if you are running standard examples, please provide the commands you have run that lead to the error.

I use 3 computer to train my example. I reboot the 3 computer and train it again , the error occur.

## What have you tried to solve it?
1. I make clean_all the mxnet.
2. cd into the ps-lite and use the command make.

**Comment by mli** [comment]
it happens sometimes, probably due to zmq bug?

one easy fix is restarting the job again.

**Comment by wsybupt** [comment]
@mli 
I run the command on another node which is listed in the hosts file, the message didn't show up...
