### ISSUE TITLE
The argument 'num_round' should be 'num_epoch'

### ISSUE THREAD

**Issue by codegank** [dmlc/mxnet#420]
python example/mnist/mlp.py

Traceback (most recent call last):
  File "mlp.py", line 28, in <module>
    model.fit(X=train, eval_data=val)
  File "/home/liwei/Documents/mxnet-master/python/mxnet/model.py", line 743, in fit
    **(self.kwargs))
  File "/home/liwei/Documents/mxnet-master/python/mxnet/optimizer.py", line 47, in create_optimizer
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_round'

**Comment by antinucleon** [comment]
Sorry I will fix the example today. Recently we decide to change the
convention, we rename epoch to batch, and round/iteration to epoch. So
num_epoch will work.
