### ISSUE TITLE
"GPU is not enabled" error on mac bookPro when load  faster RCNN model

### ISSUE THREAD

**Issue by universewill** [dmlc/mxnet#4243]
I follow the rcnn tutorial and run "python demo.py --prefix final --epoch 0 --image myimage.jpg --gpu 0" command on my mac bookPro. Then i encountered GPU not enabled error. 

I notice that maybe this model needs the mxnet built with gpu. However, mac bookPro didn't have a NVIDA card. Is that means that there is no way I can use the pre-trained model on my macbook?

----

The tutorial link:
http://mxnet.io/tutorials/computer_vision/detection.html

The error:

> ➜  rcnn git:(master) python demo.py --prefix final --epoch 0 --image myimage.jpg --gpu 0
[15:53:17] /Users/universe/Program/mxnet/dmlc-core/include/dmlc/logging.h:235: [15:53:17] src/ndarray/ndarray.cc:287: GPU is not enabled
Traceback (most recent call last):
  File "demo.py", line 81, in <module>
    detector = get_net(args.prefix, args.epoch, ctx)
  File "demo.py", line 16, in get_net
    args, auxs, num_class = load_param(prefix, epoch, convert=True, ctx=ctx)
  File "/Users/universe/Program/mxnet/example/rcnn/utils/load_model.py", line 92, in load_param
    arg_params = convert_context(arg_params, ctx)
  File "/Users/universe/Program/mxnet/example/rcnn/utils/load_model.py", line 64, in convert_context
    new_params[k] = v.as_in_context(ctx)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 568, in as_in_context
    return self.copyto(context)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 536, in copyto
    return _internal._copyto(self, out=hret)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/ndarray.py", line 1225, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [15:53:17] src/ndarray/ndarray.cc:287: GPU is not enabled

**Comment by universewill** [comment]
I solved this problem by modify the demo.py:
Change line 85 from "ctx = mx.gpu(args.gpu_id)" to "ctx = mx.cpu()"
