### ISSUE TITLE
digit recognition dataset test failed

### ISSUE THREAD

**Issue by topepo** [dmlc/mxnet#427]
My goal is to get the R package installed. I compiled the `mxnet` library but got a failure during R package install. 

Looking at the other issue, you suggested seeing if the python install worked. It appears to:

```
$ cd python; python setup.py install
running install
/Users/kuhna03/anaconda/lib/python2.7/site-packages/setuptools-14.3-py2.7.egg/pkg_resources/__init__.py:2512: PEP440Warning: 'llvmlite (0.2.2-1-gbcb15be)' is being parsed as a legacy, non PEP 440, version. You may find odd behavior and sort order. In particular it will be sorted as less than 0.0. It is recommend to migrate to PEP 440 compatible versions.
running bdist_egg
running egg_info
creating mxnet.egg-info
writing requirements to mxnet.egg-info/requires.txt
writing mxnet.egg-info/PKG-INFO
writing top-level names to mxnet.egg-info/top_level.txt
writing dependency_links to mxnet.egg-info/dependency_links.txt
writing manifest file 'mxnet.egg-info/SOURCES.txt'
reading manifest file 'mxnet.egg-info/SOURCES.txt'
writing manifest file 'mxnet.egg-info/SOURCES.txt'
installing library code to build/bdist.macosx-10.5-x86_64/egg
running install_lib
running build_py
creating build
creating build/lib
creating build/lib/mxnet
copying mxnet/__init__.py -> build/lib/mxnet
copying mxnet/base.py -> build/lib/mxnet
copying mxnet/callback.py -> build/lib/mxnet
copying mxnet/context.py -> build/lib/mxnet
copying mxnet/executor.py -> build/lib/mxnet
copying mxnet/initializer.py -> build/lib/mxnet
copying mxnet/io.py -> build/lib/mxnet
copying mxnet/kvstore.py -> build/lib/mxnet
copying mxnet/kvstore_server.py -> build/lib/mxnet
copying mxnet/libinfo.py -> build/lib/mxnet
copying mxnet/metric.py -> build/lib/mxnet
copying mxnet/misc.py -> build/lib/mxnet
copying mxnet/model.py -> build/lib/mxnet
copying mxnet/name.py -> build/lib/mxnet
copying mxnet/ndarray.py -> build/lib/mxnet
copying mxnet/optimizer.py -> build/lib/mxnet
copying mxnet/random.py -> build/lib/mxnet
copying mxnet/recordio.py -> build/lib/mxnet
copying mxnet/symbol.py -> build/lib/mxnet
copying mxnet/visualization.py -> build/lib/mxnet
creating build/bdist.macosx-10.5-x86_64
creating build/bdist.macosx-10.5-x86_64/egg
creating build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/__init__.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/base.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/callback.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/context.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/executor.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/initializer.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/io.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/kvstore.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/kvstore_server.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/libinfo.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/metric.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/misc.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/model.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/name.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/ndarray.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/optimizer.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/random.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/recordio.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/symbol.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
copying build/lib/mxnet/visualization.py -> build/bdist.macosx-10.5-x86_64/egg/mxnet
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/__init__.py to __init__.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/base.py to base.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/callback.py to callback.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/context.py to context.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/executor.py to executor.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/initializer.py to initializer.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/io.py to io.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/kvstore.py to kvstore.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/kvstore_server.py to kvstore_server.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/libinfo.py to libinfo.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/metric.py to metric.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/misc.py to misc.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/model.py to model.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/name.py to name.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/ndarray.py to ndarray.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/optimizer.py to optimizer.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/random.py to random.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/recordio.py to recordio.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/symbol.py to symbol.pyc
byte-compiling build/bdist.macosx-10.5-x86_64/egg/mxnet/visualization.py to visualization.pyc
installing package data to build/bdist.macosx-10.5-x86_64/egg
running install_data
copying /Users/kuhna03/Code/github/mxnet/python/mxnet/../../lib/libmxnet.so -> build/bdist.macosx-10.5-x86_64/egg/mxnet
creating build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/PKG-INFO -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/SOURCES.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/dependency_links.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/not-zip-safe -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/requires.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
copying mxnet.egg-info/top_level.txt -> build/bdist.macosx-10.5-x86_64/egg/EGG-INFO
creating dist
creating 'dist/mxnet-0.5.0-py2.7.egg' and adding 'build/bdist.macosx-10.5-x86_64/egg' to it
removing 'build/bdist.macosx-10.5-x86_64/egg' (and everything under it)
Processing mxnet-0.5.0-py2.7.egg
creating /Users/kuhna03/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg
Extracting mxnet-0.5.0-py2.7.egg to /Users/kuhna03/anaconda/lib/python2.7/site-packages
Adding mxnet 0.5.0 to easy-install.pth file

Installed /Users/kuhna03/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg
Processing dependencies for mxnet==0.5.0
Searching for numpy==1.9.2
Best match: numpy 1.9.2
Adding numpy 1.9.2 to easy-install.pth file

Using /Users/kuhna03/anaconda/lib/python2.7/site-packages
Finished processing dependencies for mxnet==0.5.0
```

However, the test on the digit recognition dataset failed:

```
$ cd ..; python example/mnist/mlp.py
--2015-10-29 14:22:00--  http://webdocs.cs.ualberta.ca/~bx3/data/mnist.zip
Resolving webdocs.cs.ualberta.ca... 129.128.184.6
Connecting to webdocs.cs.ualberta.ca|129.128.184.6|:80... connected.
HTTP request sent, awaiting response... 200 OK
Length: 11595270 (11M) [application/zip]
Saving to: 'data/mnist.zip'

100%[====================================================================================================================>] 11,595,270   405KB/s   in 29s    

2015-10-29 14:22:29 (390 KB/s) - 'data/mnist.zip' saved [11595270/11595270]

Archive:  mnist.zip
  inflating: t10k-images-idx3-ubyte  
  inflating: t10k-labels-idx1-ubyte  
  inflating: train-images-idx3-ubyte  
  inflating: train-labels-idx1-ubyte  
[14:22:33] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[14:22:33] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
Traceback (most recent call last):
  File "example/mnist/mlp.py", line 28, in <module>
    model.fit(X=train, eval_data=val)
  File "/Users/kuhna03/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 743, in fit
    **(self.kwargs))
  File "/Users/kuhna03/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/optimizer.py", line 47, in create_optimizer
    **kwargs)
TypeError: __init__() got an unexpected keyword argument 'num_round'
```

Any ideas? I don't really care about the python bindings. Here is the R package failure:

```
$ R CMD INSTALL R-package
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’
* installing *source* package ‘mxnet’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c executor.cc -o executor.o
In file included from executor.cc:11:
././ndarray.h:97:17: error: no member named 'get' in 'Rcpp::XPtr<mxnet::R::NDBlob, PreserveStorage, &Rcpp::standard_delete_finalizer>'
    return ptr_.get();
           ~~~~ ^
././ndarray.h:100:17: error: no member named 'get' in 'Rcpp::XPtr<mxnet::R::NDBlob, PreserveStorage, &Rcpp::standard_delete_finalizer>'
    return ptr_.get();
           ~~~~ ^
executor.cc:38:15: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
      if (to->at(i) != R_NilValue) {
          ~~  ^
executor.cc:40:50: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
          NDArray dst = NDArray::FromRObject(to->at(i));
                                             ~~  ^
executor.cc:62:15: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
      if (to->at(index) != R_NilValue) {
          ~~  ^
executor.cc:64:50: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
          NDArray dst = NDArray::FromRObject(to->at(index));
                                             ~~  ^
executor.cc:121:12: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
      ret->at(i) = NDArray::Empty(src.dim(), ctx);
      ~~~  ^
executor.cc:122:47: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
      NDArray dst = NDArray::FromRObject(ret->at(i));
                                         ~~~  ^
executor.cc:149:14: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
        ret->at(i) = NDArray::Empty(NDArray::FromRObject(source_array[i]).dim(), ctx);
        ~~~  ^
executor.cc:150:52: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
        handles->at(i) = NDArray::FromRObject(ret->at(i))->handle;
                                              ~~~  ^
executor.cc:168:12: error: no member named 'at' in 'Rcpp::Vector<19, PreserveStorage>'
      ret->at(i) = NDArray::RObject(out_arr[i], false);
      ~~~  ^
11 errors generated.
make: *** [executor.o] Error 1
ERROR: compilation failed for package ‘mxnet’
* removing ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet’
```

Using 

```
> sessionInfo()
R version 3.2.2 Patched (2015-10-19 r69547)
Platform: x86_64-apple-darwin13.4.0 (64-bit)
Running under: OS X 10.9.5 (Mavericks)

locale:
[1] en_US.US-ASCII/en_US.US-ASCII/en_US.US-ASCII/C/en_US.US-ASCII/en_US.US-ASCII

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] Rcpp_0.11.3
```

Thanks,

Max

**Comment by shengwa** [comment]
I think it will be fixed soon. https://github.com/dmlc/mxnet/issues/420

**Comment by tqchen** [comment]
Guess was due to version of Rcpp, try upgrade it to most recent version.

**Comment by topepo** [comment]
Solved! 

Thanks

```
$ R CMD INSTALL R-package
* installing to library ‘/Library/Frameworks/R.framework/Versions/3.2/Resources/library’
* installing *source* package ‘mxnet’ ...
** libs
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c executor.cc -o executor.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c export.cc -o export.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c io.cc -o io.o
io.cc:154:15: warning: unused variable 'key_var_num_args' [-Wunused-variable]
  const char *key_var_num_args;
              ^
1 warning generated.
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c kvstore.cc -o kvstore.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c mxnet.cc -o mxnet.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c ndarray.cc -o ndarray.o
clang++ -I/Library/Frameworks/R.framework/Resources/include -DNDEBUG -I../..//include -I../..//dmlc-core/include -I/usr/local/include -I/usr/local/include/freetype2 -I/opt/X11/include -I"/Library/Frameworks/R.framework/Versions/3.2/Resources/library/Rcpp/include"   -fPIC  -Wall -mtune=core2 -g -O2  -c symbol.cc -o symbol.o
cd ../../; make CXX="clang++"; cd -
make[1]: Nothing to be done for `all'.
/Users/kuhna03/Code/github/mxnet/R-package/src
mkdir -p ../inst
mkdir -p ../inst/libs
cp ../..//lib/libmxnet.so ../inst/libs/libmxnet.so
clang++ -dynamiclib -Wl,-headerpad_max_install_names -undefined dynamic_lookup -single_module -multiply_defined suppress -L/Library/Frameworks/R.framework/Resources/lib -L/usr/local/lib -o mxnet.so executor.o export.o io.o kvstore.o mxnet.o ndarray.o symbol.o -L/Library/Frameworks/R.framework/Resources/lib -lRlapack -L/Library/Frameworks/R.framework/Resources/lib -lRblas -L/usr/local/lib/gcc/x86_64-apple-darwin13.0.0/4.8.2 -lgfortran -lquadmath -lm -F/Library/Frameworks/R.framework/.. -framework R -Wl,-framework -Wl,CoreFoundation
installing to /Library/Frameworks/R.framework/Versions/3.2/Resources/library/mxnet/libs
** R
** demo
** inst
** preparing package for lazy loading
** help
*** installing help indices
** building package indices
** installing vignettes
** testing if installed package can be loaded
* DONE (mxnet)
```

**Comment by hetong007** [comment]
Seems we need to check the version requirement of dependencies.
