### ISSUE TITLE
Distributed computation requires CUDA for non-CUDA MxNet version

### ISSUE THREAD

**Issue by mcxkarakoc** [dmlc/mxnet#4548]
## Environment info
Operating System: Debian Jessie x64
---
Hi,

I have not examined the issue deeply yet but maybe some contributors may notice the problem easily. When I submit a command similar to below:

`launch.py -n X --launcher ssh -H hosts python myexperiment.py --kv-store dist_sync`

the error below is raised. However, I've compiled MxNet with USE_CUDA=0 and don't use any GPU in my code. Why does it try to find GPU?
I've tried dist_async, still the same problem. I've tried removing nodes with GPU, still the same problem. I've tried removing nodes with GPU and decreasing the number of the nodes(X). This time, it worked without any problem. However, when I increase X, again the same problem. What should I do? 

As a note, when I do not use launch.py, my code works without any problem.

Error:
NVIDIA: no NVIDIA devices found

Stack trace:
/home/mkarakoc/private/frameworks/mxnet/dmlc-core/include/dmlc/./logging.h:235: [21:34:52] src/storage/storage.cc:38: Check failed: e == cudaSuccess || e == cudaErrorCudartUnloading CUDA: unknown error
Traceback (most recent call last):
  File "RunDeepAutoencoder.py", line 179, in <module>
    main();
  File "RunDeepAutoencoder.py", line 153, in main
    ae_model.layerwise_pretrain()
  File "autoencoder.py", line 315, in layerwise_pretrain
  File ".local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/base_module.py", line 362, in fit
  File ".local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/module/module.py", line 356, in init_optimizer
  File ".local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 82, in _initialize_kvstore
    kvstore.init(idx, arg_params[param_names[idx]])
  File ".local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/kvstore.py", line 100, in init
    self.handle, mx_uint(len(ckeys)), ckeys, cvals))
  File ".local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError:

**Comment by mli** [comment]
should be fixed by #4550

**Comment by mcxkarakoc** [comment]
Confirmed
