### ISSUE TITLE
Bucketing error after upgrade from v0.8.0

### ISSUE THREAD

**Issue by wellecks** [dmlc/mxnet#4564]
I have a model using a bucketing module that worked in v0.8.0 but now crashes after updating MXNet - it's isolated in the script below, which runs fine on the `v0.8.0` tag, but results in the error below on latest (`16d0cde9633ebaf846745b9d12ccc1f25aa1e1a9`). I'm not sure from the error message and wonder which features changed since v0.8.0 that result in the error. Thanks!

## Environment info
Package used (Python/R/Scala/Julia): Python

MXNet commit hash (`git rev-parse HEAD`): 16d0cde9633ebaf846745b9d12ccc1f25aa1e1a9

Python version and distribution: 2.7.10

## Error Message:
```bash
Traceback (most recent call last):
  File "bucketing.py", line 26, in <module>
    provide_data=[('input', (data.shape[0], input_size))]), is_train=False)
  File "mxnet/python/mxnet/module/bucketing_module.py", line 262, in forward
    self._curr_module.forward(data_batch, is_train=is_train)
  File "mxnet/python/mxnet/module/module.py", line 452, in forward
    self._exec_group.forward(data_batch, is_train)
  File "mxnet/python/mxnet/module/executor_group.py", line 313, in forward
    _load_data(data_batch, self.data_arrays, self.data_layouts)
  File "mxnet/python/mxnet/module/executor_group.py", line 43, in _load_data
    _load_general(batch.data, targets, major_axis)
  File "mxnet/python/mxnet/module/executor_group.py", line 17, in _load_general
    for d_src, d_targets, axis in zip(data, targets, major_axis):
  File "mxnet/python/mxnet/ndarray.py", line 315, in __getitem__
    return self._at(in_slice)
  File "mxnet/python/mxnet/ndarray.py", line 374, in _at
    self.handle, idx, ctypes.byref(handle)))
  File "mxnet/python/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [19:08:30] include/mxnet/ndarray.h:276: Check failed: shape_[0] > idx (1 vs. 1) index out of range

Stack trace returned 5 entries:
[bt] (0) 0   libmxnet.so                         0x00000001031326ac _ZN4dmlc15LogMessageFatalD2Ev + 44
[bt] (1) 1   libmxnet.so                         0x000000010371b339 _ZNK5mxnet7NDArray2AtEj + 1769
[bt] (2) 2   libmxnet.so                         0x0000000103716a4a MXNDArrayAt + 90
[bt] (3) 3   libffi.dylib                        0x00007fff8aed1f14 ffi_call_unix64 + 76
[bt] (4) 4   ???                                 0x00007fff5d900a20 0x0 + 140734763108896
```
## Minimum reproducible example
```python
import mxnet as mx
import numpy as np

def sym_gen(bucket_key):
    input = mx.sym.Variable('input')
    label = mx.sym.Variable('label')
    net = mx.sym.FullyConnected(data=input, num_hidden=output_size, name='output')
    net = mx.sym.SoftmaxActivation(data=net, name='softmax')
    loss = -mx.sym.sum(label*net)
    return mx.sym.Group([net, mx.sym.MakeLoss(loss)]), ['input'], ['label']

data = np.zeros((1, 5), dtype=np.float)

input_size = data.shape[1]
output_size = 2
key = 1

mod = mx.mod.bucketing_module.BucketingModule(sym_gen, default_bucket_key=key, context=mx.cpu())
mod.bind(data_shapes=[('input', [key, input_size])], label_shapes=[('label', [key, output_size])])
mod.init_params(mx.initializer.Uniform())
mod.init_optimizer(optimizer=mx.optimizer.Adam())

mod.forward(mx.io.DataBatch(data=mx.nd.array([data], ctx=mx.cpu()),
                            label=None,
                            bucket_key=key,
                            provide_data=[('input', (data.shape[0], input_size))]), is_train=False)

p = mod.get_outputs()[0]
print p.asnumpy()
```

**Comment by piiswrong** [comment]
this wasn't supposed to work. you should use:
mod.forward(mx.io.DataBatch(data=[mx.nd.array(data, ctx=mx.cpu())],
                            label=None,
                            bucket_key=key,
                            provide_data=[('input', (data.shape[0], input_size))]), is_train=False)

**Comment by wellecks** [comment]
I see, that makes sense - thanks!
