### ISSUE TITLE
GAN example guide.

### ISSUE THREAD

**Issue by hyichao** [dmlc/mxnet#4631]
Hello,

I'm interested in example/gan but the only script I found was a `dcgan.py`.
Is there anyone could bring a README for this example? Several hard codes are found in the `dcgan.py` script and I found it hard to run with.
Thanks very much.

**Comment by hbkunn** [comment]
That sample has already been simple and clear as far as I am concerned...
If you could point out where you feel confused maybe I could help~

**Comment by hyichao** [comment]
As I was trying to simply run the script and hope to see something, I got an error like below
```
Traceback (most recent call last):
  File "dcgan.py", line 152, in <module>
    X_train, X_test = get_mnist()
  File "dcgan.py", line 56, in get_mnist
    mnist = fetch_mldata('MNIST original')
  File "/usr/lib/python2.7/dist-packages/sklearn/datasets/mldata.py", line 157, in fetch_mldata
    matlab_dict = io.loadmat(matlab_file, struct_as_record=True)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio.py", line 126, in loadmat
    matfile_dict = MR.get_variables(variable_names)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 288, in get_variables
    res = self.read_var_array(hdr, process)
  File "/usr/lib/python2.7/dist-packages/scipy/io/matlab/mio5.py", line 248, in read_var_array
    return self._matrix_reader.array_from_header(header, process)
  File "mio5_utils.pyx", line 616, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:6021)
  File "mio5_utils.pyx", line 645, in scipy.io.matlab.mio5_utils.VarReader5.array_from_header (scipy/io/matlab/mio5_utils.c:5448)
  File "mio5_utils.pyx", line 713, in scipy.io.matlab.mio5_utils.VarReader5.read_real_complex (scipy/io/matlab/mio5_utils.c:6445)
  File "mio5_utils.pyx", line 417, in scipy.io.matlab.mio5_utils.VarReader5.read_numeric (scipy/io/matlab/mio5_utils.c:3949)
  File "mio5_utils.pyx", line 353, in scipy.io.matlab.mio5_utils.VarReader5.read_element (scipy/io/matlab/mio5_utils.c:3657)
  File "streams.pyx", line 324, in scipy.io.matlab.streams.FileStream.read_string (scipy/io/matlab/streams.c:4453)
IOError: could not read bytes
```

It seems like getting data is not correct. 
Fortunately there are some useful codes in `image-classification/train_mnist.py` and I have to change some codes in `dcgan,py` so as to read mnist correctly. It's working fine now and I could see amazing visualization. Thanks a lot.
