### ISSUE TITLE
help! when i use the bucket_io.py define my train_iter i get this error:Check failed: from.shape() == to->shape() operands shape mismatch

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#4653]
2017-01-13 08:36:14,767 Start training with [cpu(0)]
Traceback (most recent call last):

  File "<ipython-input-6-3b63cb5d1170>", line 16, in <module>
    batch_end_callback=mx.callback.Speedometer(batch_size, 1),)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\model.py", line 811, in fit
    sym_gen=self.sym_gen)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\model.py", line 236, in _train_multi_device
    executor_manager.load_data_batch(data_batch)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\executor_manager.py", line 410, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\executor_manager.py", line 257, in load_data_batch
    _load_data(data_batch, self.data_arrays)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\executor_manager.py", line 93, in _load_data
    _load_general(batch.data, targets)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\executor_manager.py", line 89, in _load_general
    d_src[slice_idx].copyto(d_dst)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\ndarray.py", line 533, in copyto
    return _internal._copyto(self, out=other)

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\ndarray.py", line 1225, in unary_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.8.0-py2.7.egg\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))

MXNetError: [08:36:14] D:\Mxnet\windows\mxnet-master\src\ndarray\ndarray.cc:231: Check failed: from.shape() == to->shape() operands shape mismatch

**Comment by janelu9** [comment]
these are my data shape:
self.provide_data : [('data', (32, 6729))]

self.provide_label: [('softmax_label', (32,))]

**Comment by janelu9** [comment]
I use the class BucketSentenceIter to define my data iter. 
Different from the original lstm demo , I apply the lstm model on   text classification, so I just have tow labels 0 and 1. while the original lstm demo has as many labels as the vocab. How can i modify the bucket_io.py to fit my data

**Comment by piiswrong** [comment]
This is usually because you used DataBatch(data=NDArray) instead of the correct DataBatch(data=[NDArray]) format

**Comment by janelu9** [comment]
@piiswrong 
                data_all = [mx.nd.array(data)]
                label_all =[mx.nd.array(label)]
                data_names = ['data'] 
                label_names = ['softmax_label']

                data_batch = SimpleBatch(data_names, data_all, label_names, label_all,self.buckets[i_bucket])

as above , I gave them "[]", it still throws a same error
this is my test model:

    data = mx.sym.Variable('data')
    embed_layer = mx.sym.Embedding(data=data, input_dim=vocab_size, output_dim=num_embed, name='vocab_embed')
    input1 = mx.sym.Reshape(data=embed_layer, target_shape=(batch_size, vocab_size*num_embed))
    fc1  = mx.sym.FullyConnected(data=input1, name='fc1', num_hidden =2)
    mlp  = mx.sym.SoftmaxOutput(data=fc1, name='softmax')

**Comment by janelu9** [comment]
@piiswrong 
I catch  a glimpse of the train_iter as follows:
 T=iter(data_train)

W=T.next()

W.label
Out[21]: [<NDArray 32 @cpu(0)>]

W.data
Out[22]: [<NDArray 32x45 @cpu(0)>]

W.bucket_key
Out[23]: 45

W.provide_label
Out[24]: [('softmax_label', (32L,))]

W.provide_data
Out[25]: [('data', (32L, 45L))]

i didn't find any faults

**Comment by janelu9** [comment]
is it the model that leads to the error

**Comment by janelu9** [comment]
I also test my iteration programs by the model：
![image](https://cloud.githubusercontent.com/assets/24219258/21922005/e69b7f40-d9a6-11e6-88ff-48e022f2b131.png)

as：
 fc1  = mx.sym.FullyConnected(data=data, name='fc1', num_hidden =2)
    mlp  = mx.sym.SoftmaxOutput(data=fc1, name='softmax')

it errors again , I think that maybe the batch's varied shape cause this problem . different batch has a different bucket

**Comment by janelu9** [comment]
oh it works normally when I set the batch 's shap unchanged but it errors again after the train is end

**Comment by janelu9** [comment]
I have solved my problem by fixing the train and test data‘s width unchanged though they  are in different buckets. the reason why it throws a error after train is that the test data's width is  not equal to the train's
