### ISSUE TITLE
[Scala] fail to run the example ExampleCustomOpWithRtc.scala

### ISSUE THREAD

**Issue by Ldpe2G** [dmlc/mxnet#4699]
## Environment info
Operating System: Ubuntu 14.04

Compiler: gcc 4.8

Package used (Python/R/Scala/Julia): Scala

MXNet version: v0.9

Or if installed from source:

MXNet commit hash (`git rev-parse HEAD`): 6d05979cce53041f356204b17db2effb09371328

## Error Message:
```bash
SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/ldpe2g/Mxnet/mxnet_Scala/mxnet/scala-package/assembly/linux-x86_64-gpu/target/mxnet-full_2.11-linux-x86_64-gpu-0.1.2-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/ldpe2g/Mxnet/mxnet_Scala/mxnet/scala-package/examples/target/classes/lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2017-01-17 18:21:35,123 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala from native path.
2017-01-17 18:21:35,124 [main] [MXNetJVM] [WARN] - Failed to load from native path. Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:76)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:45)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Operator$.register(Operator.scala:217)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<init>(ExampleCustomOpWithRtc.scala:104)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<clinit>(ExampleCustomOpWithRtc.scala)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc.main(ExampleCustomOpWithRtc.scala)
2017-01-17 18:21:35,125 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-gpu from native path.
2017-01-17 18:21:35,125 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-cpu from native path.
2017-01-17 18:21:35,125 [main] [MXNetJVM] [WARN] - MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala-linux-x86_64-cpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryXPU(Base.scala:102)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:83)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:45)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Operator$.register(Operator.scala:217)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<init>(ExampleCustomOpWithRtc.scala:104)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<clinit>(ExampleCustomOpWithRtc.scala)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc.main(ExampleCustomOpWithRtc.scala)
2017-01-17 18:21:35,136 [main] [ml.dmlc.mxnet.util.NativeLibraryLoader] [INFO] - Loading libmxnet-scala.so from /lib/native/ copying to mxnet-scala
[18:21:37] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[18:21:37] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
[18:21:38] ./include/dmlc/logging.h:208: [18:21:38] src/common/mxrtc.cc:46: Check failed: err = cuModuleLoadDataEx(&module, ptx_, 0, 0, 0) == CUDA_SUCCESS (201 vs. 0) CudaError: 201
ml.dmlc.mxnet.MXNetError: [18:21:38] src/common/mxrtc.cc:46: Check failed: err = cuModuleLoadDataEx(&module, ptx_, 0, 0, 0) == CUDA_SUCCESS (201 vs. 0) CudaError: 201
	at ml.dmlc.mxnet.Base$.checkCall(Base.scala:116)
	at ml.dmlc.mxnet.Rtc.push(Rtc.scala:62)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$Softmax.forward(ExampleCustomOpWithRtc.scala:60)
	at ml.dmlc.mxnet.CustomOp.forwardEntry(Operator.scala:65)
[18:21:38] ./include/dmlc/logging.h:208: [18:21:38] src/operator/custom.cc:81: Check failed: op_info_->forward(ptrs.size(), ptrs.data(), tags.data(), reqs.data(), ctx.is_train, op_info_->p_forward) 
terminate called after throwing an instance of 'dmlc::Error'
  what():  [18:21:38] src/operator/custom.cc:81: Check failed: op_info_->forward(ptrs.size(), ptrs.data(), tags.data(), reqs.data(), ctx.is_train, op_info_->p_forward) 
```

## Steps to reproduce
1. compile mxnet with CUDA & NVRTC and then compile the scalapkg
```bash
make -j4 && make scalapkg
```

2.
```bash 
cd scala-package/examples/scripts/customop
```

3.
```bash
 bash run_customopwithrtc.sh path_to_mnist_data
```

## What have you tried to solve it?

I have locate the commit which cause the problem, it's the pr #4528 
after I roll back to the commit 50a3a3184e3034a98b2d4ad82f186d035803ab9b before #4528 
the problem have solved.

And I also check the CUDA doc, error code 201 means:

CUDA_ERROR_INVALID_CONTEXT = 201
This most frequently indicates that there is no context bound to the current thread. This can also be returned if the context passed to an API call is not a valid handle (such as a context that has had cuCtxDestroy() invoked on it). This can also be returned if a user mixes different API versions (i.e. 3010 context with 3020 API calls). See cuCtxGetApiVersion() for more details.

@javelinjs @piiswrong

**Comment by yxzf** [comment]
@Ldpe2G I also have this problem and I use CPU. I roll back to the commit, but still have the problem.

SLF4J: Class path contains multiple SLF4J bindings.
SLF4J: Found binding in [jar:file:/home/yxzf/mxnet/scala-package/assembly/linux-x86_64-cpu/target/mxnet-full_2.11-linux-x86_64-cpu-0.1.2-SNAPSHOT.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: Found binding in [jar:file:/home/yxzf/mxnet/scala-package/examples/target/classes/lib/slf4j-log4j12-1.7.7.jar!/org/slf4j/impl/StaticLoggerBinder.class]
SLF4J: See http://www.slf4j.org/codes.html#multiple_bindings for an explanation.
SLF4J: Actual binding is of type [org.slf4j.impl.Log4jLoggerFactory]
2017-01-18 07:52:50,198 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala from native path.
2017-01-18 07:52:50,200 [main] [MXNetJVM] [WARN] - Failed to load from native path. Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:76)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:45)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Operator$.register(Operator.scala:217)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<init>(ExampleCustomOpWithRtc.scala:104)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<clinit>(ExampleCustomOpWithRtc.scala)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc.main(ExampleCustomOpWithRtc.scala)
2017-01-18 07:52:50,202 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-gpu from native path.
2017-01-18 07:52:50,202 [main] [MXNetJVM] [INFO] - Try loading mxnet-scala-linux-x86_64-cpu from native path.
2017-01-18 07:52:50,203 [main] [MXNetJVM] [WARN] - MXNet Scala native library not found in path. Copying native library from the archive. Consider installing the library somewhere in the path (for Windows: PATH, for Linux: LD_LIBRARY_PATH), or specifying by Java cmd option -Djava.library.path=[lib path].Exception:
java.lang.UnsatisfiedLinkError: no mxnet-scala-linux-x86_64-cpu in java.library.path
	at java.lang.ClassLoader.loadLibrary(ClassLoader.java:1867)
	at java.lang.Runtime.loadLibrary0(Runtime.java:870)
	at java.lang.System.loadLibrary(System.java:1122)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryXPU(Base.scala:102)
	at ml.dmlc.mxnet.Base$.tryLoadLibraryOS(Base.scala:83)
	at ml.dmlc.mxnet.Base$.<init>(Base.scala:45)
	at ml.dmlc.mxnet.Base$.<clinit>(Base.scala)
	at ml.dmlc.mxnet.Operator$.register(Operator.scala:217)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<init>(ExampleCustomOpWithRtc.scala:104)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc$.<clinit>(ExampleCustomOpWithRtc.scala)
	at ml.dmlc.mxnet.examples.customop.ExampleCustomOpWithRtc.main(ExampleCustomOpWithRtc.scala)
2017-01-18 07:52:50,219 [main] [ml.dmlc.mxnet.util.NativeLibraryLoader] [INFO] - Loading libmxnet-scala.so from /lib/native/ copying to mxnet-scala
[20:52:52] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(100,784)
[20:52:52] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(100,784)
[20:52:52] include/dmlc/./logging.h:300: [20:52:52] src/storage/storage.cc:78: Compile with USE_CUDA=1 to enable GPU usage

**Comment by Ldpe2G** [comment]
@yxzf if you want to run the example ExampleCustomOpWithRtc.scala you must use gpu.

**Comment by yxzf** [comment]
@Ldpe2G I use run_gan_mnist.sh, also have this problem

**Comment by Ldpe2G** [comment]
@yxzf compile the mxnet with cuda and try again

**Comment by Ldpe2G** [comment]
@yxzf if you compile the mxnet without cuda, try to modify the 

CLASS_PATH=$MXNET_ROOT/scala-package/assembly/linux-x86_64-gpu/target/* ...
to
CLASS_PATH=$MXNET_ROOT/scala-package/assembly/linux-x86_64-cpu/target/* ...

in the script

**Comment by yxzf** [comment]
@Ldpe2G I had modified it to cpu and the same errors raised...

**Comment by Ldpe2G** [comment]
@yxzf how did you run the script, could you provide the full command?

**Comment by yxzf** [comment]
@Ldpe2G 
<img width="571" alt="2017-01-19 8 08 38" src="https://cloud.githubusercontent.com/assets/9815568/22106311/2084ba88-de83-11e6-91a4-94ddf95056cc.png">

<img width="1123" alt="2017-01-19 8 08 24" src="https://cloud.githubusercontent.com/assets/9815568/22106316/29544d0e-de83-11e6-8c97-a7d1612b8202.png">

#!/bin/bash

MXNET_ROOT=$(cd "$(dirname $0)/../../.."; pwd)
CLASS_PATH=$MXNET_ROOT/scala-package/assembly/linux-x86_64-cpu/target/*:$MXNET_ROOT/scala-package/examples/target/*:$MXNET_ROOT/scala-package/examples/target/classes/lib/*

# which gpu card to use, -1 means cpu
GPU=$1

# the mnist data path
# you can get the mnist data using the script core/scripts/get_mnist_data.sh
MNIST_DATA_PATH=$2

# the path to save the generated results
OUTPUT_PATH=$3

java -Xmx4G -cp $CLASS_PATH \
        ml.dmlc.mxnet.examples.gan.GanMnist \
        --mnist-data-path $MNIST_DATA_PATH \
        --gpu $GPU \
        --output-path $OUTPUT_PATH

**Comment by Ldpe2G** [comment]
@yxzf I mean how did you run this script, did you run it like the following?
```bash
bash run_gan_mnist.sh -1 path_to_mnist_data output_path
```
