### ISSUE TITLE
ssd example evaluate.py problem

### ISSUE THREAD

**Issue by xinghedyc** [dmlc/mxnet#4719]
## Environment info
Operating System: ubuntu 14.04

Compiler: gcc 4.8

Package used (Python/R/Scala/Julia): python

MXNet version:0.9.1 latest

Python version and distribution: anaconda 2.7.11

## Error Message:
```
~/mxnet/example/ssd$ python evaluate.py --gpus 0,1 --batch-size 128 --epoch 100
```
error trace:
```
Traceback (most recent call last):
  File "evaluate.py", line 55, in <module>
    nms_thresh=args.nms_thresh, force_nms=args.force_nms)
  File "/home/onlyou/mxnet/example/ssd/evaluate/evaluate_net.py", line 53, in evaluate_net
    rand_samplers=[], rand_mirror=False, is_train=False, shuffle=False)
  File "/home/onlyou/mxnet/example/ssd/dataset/iterator.py", line 74, in __init__
    self._get_batch()
  File "/home/onlyou/mxnet/example/ssd/dataset/iterator.py", line 134, in _get_batch
    data, label = self._data_augmentation(img, gt)
  File "/home/onlyou/mxnet/example/ssd/dataset/iterator.py", line 191, in _data_augmentation
    data = data - self._mean_pixels
  File "/home/onlyou/mxnet/python/mxnet/ndarray.py", line 125, in __sub__
    return subtract(self, other)
  File "/home/onlyou/mxnet/python/mxnet/ndarray.py", line 737, in subtract
    _internal._rminus_scalar)
  File "/home/onlyou/mxnet/python/mxnet/ndarray.py", line 685, in _ufunc_helper
    raise TypeError('type %s not supported' % str(type(rhs)))
TypeError: type <type 'tuple'> not supported
```
## Minimum reproducible example
if you are using your own code, please provide a short script that reproduces the error.

## Steps to reproduce

1.~/mxnet/example/ssd$ python evaluate.py --gpus 0,1 --batch-size 128 --epoch 100

## What have you tried to solve it?

1. update to the latest mxnet

**Comment by piiswrong** [comment]
this should have been fixed. Please update
