### ISSUE TITLE
mlp example bug

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#477]
When I tried mlp_numpy.py in example/mnist with the latest mxnet, I got this error:
```python
Traceback (most recent call last):
  File "mlp_numpy.py", line 35, in <module>
    train_iter = mx.io.NDArrayIter(data=train_data, label=train_label, batch_size=batch_size, shuffle=True)
  File "xxx/mxnet/python/mxnet/io.py", line 124, in __init__
    if isinstance(args[0], list) or isinstance(args[0], tuple):
IndexError: tuple index out of range 
```
Is this a bug?

**Comment by tornadomeet** [comment]
Please update the newest version of mxnet, there is not bug for this example here, the output is like this:


```r
[wuwei@localhost mxnet]$ python example/mnist/mlp_numpy.py
INFO:root:Start training with [cpu(0)]
INFO:root:Epoch[0] Train-accuracy=0.643970
INFO:root:Epoch[0] Time cost=0.962
INFO:root:Epoch[1] Train-accuracy=0.949768
...
```

**Comment by wangg12** [comment]
I've already update to the newest mxnet, but I still get the same bug. @tornadomeet 
```
Traceback (most recent call last):
  File "mlp_numpy.py", line 35, in <module>
    train_iter = mx.io.NDArrayIter(data=train_data, label=train_label, batch_size=batch_size, shuffle=True)
  File "/home/wangg12/anaconda/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/io.py", line 124, in __init__
    if isinstance(args[0], list) or isinstance(args[0], tuple):
IndexError: tuple index out of range
```

**Comment by piiswrong** [comment]
This is a bug due to recent dataiterator interface change.
Will be fixed after https://github.com/dmlc/mxnet/pull/505 is merged
