### ISSUE TITLE
No module named bbox when running faster-cnn exampl

### ISSUE THREAD

**Issue by Gelu74** [dmlc/mxnet#4841]
trying to reproduce the faster-rcnn tutorial as in http://mxnet.io/tutorials/computer_vision/detection.html
running 
python train_alternate.py --gpus 0

yields this error:
Traceback (most recent call last):
  File "train_alternate.py", line 7, in <module>
    from rcnn.tools.train_rpn import train_rpn
  File "/mnt/gelu/mxnet/example/rcnn/rcnn/tools/train_rpn.py", line 7, in <module>
    from ..symbol import *
  File "/mnt/gelu/mxnet/example/rcnn/rcnn/symbol/__init__.py", line 1, in <module>
    from symbol_vgg import *
  File "/mnt/gelu/mxnet/example/rcnn/rcnn/symbol/symbol_vgg.py", line 2, in <module>
    import proposal
  File "/mnt/gelu/mxnet/example/rcnn/rcnn/symbol/proposal.py", line 11, in <module>
    from rcnn.processing.bbox_transform import bbox_pred, clip_boxes
  File "/mnt/gelu/mxnet/example/rcnn/rcnn/processing/bbox_transform.py", line 2, in <module>
    from ..cython.bbox import bbox_overlaps_cython
ImportError: No module named bbox

I've tried searching on bbox module but could not find it anywhere. My mxnet is compiled in ubuntu 16 with cuda and cdnn support

**Comment by piiswrong** [comment]
Please follow the readme you need to compile extra operators

**Comment by Gelu74** [comment]
Thanks for the reply,

**Comment by lightningsoon** [comment]
Emm...Are you ok?
I had the same problem.Could you please tell me how to deal with the things?

Look this step:

bash script/vgg_voc07.sh 0

reply:
Traceback (most recent call last):
  File "train_end2end.py", line 8, in <module>
    from rcnn.symbol import *
  File "F:\mxnet\example\rcnn\rcnn\symbol\__init__.py", line 1, in <module>
    from symbol_vgg import *
  File "F:\mxnet\example\rcnn\rcnn\symbol\symbol_vgg.py", line 2, in <module>
    import proposal
  File "F:\mxnet\example\rcnn\rcnn\symbol\proposal.py", line 11, in <module>
    from rcnn.processing.bbox_transform import bbox_pred, clip_boxes
  File "F:\mxnet\example\rcnn\rcnn\processing\bbox_transform.py", line 2, in <module>
    from ..cython.bbox import bbox_overlaps_cython
ImportError: No module named bbox
Traceback (most recent call last):
  File "test.py", line 4, in <module>
    from rcnn.tools.test_rcnn import test_rcnn
  File "F:\mxnet\example\rcnn\rcnn\tools\test_rcnn.py", line 6, in <module>
    from ..symbol import *
  File "F:\mxnet\example\rcnn\rcnn\symbol\__init__.py", line 1, in <module>
    from symbol_vgg import *
  File "F:\mxnet\example\rcnn\rcnn\symbol\symbol_vgg.py", line 2, in <module>
    import proposal
  File "F:\mxnet\example\rcnn\rcnn\symbol\proposal.py", line 11, in <module>
    from rcnn.processing.bbox_transform import bbox_pred, clip_boxes
  File "F:\mxnet\example\rcnn\rcnn\processing\bbox_transform.py", line 2, in <module>
    from ..cython.bbox import bbox_overlaps_cython
ImportError: No module named bbox

Why closed the issue? @Gelu74 @piiswrong

**Comment by lightningsoon** [comment]
That's all right.
I found ..cython.bbox.pyx and setup.py
then I open cmd and input `python setup.py install`
get another error:
EnvironmentError: The CUDA nvcc path could not be located in C:\Program Files\NVIDIA GPU Computing Toolkit\CUDA\v8.0\bin\nvcc
but I really don't have folder-nvcc,I have nvcc.exe and nvcc.profile

who knows where is the folder?

**Comment by niluanwudidadi** [comment]
I have met the same error with you.Have you solved this problem? @lightningsoon

**Comment by lightningsoon** [comment]
use linux to slove


发自网易邮箱大师
On 03/02/2017 15:20, niluanwudidadi wrote:

I have met the same error with you.Have you solved this problem? @lightningsoon
