### ISSUE TITLE
src/symbol/symbol.cc:155: Symbol.InferShapeKeyword argument name data not found. 

### ISSUE THREAD

**Issue by data-compute-geek** [dmlc/mxnet#4862]
I use AWS EC2 instance p2.16xlarge with 'Deep Learning AMI - Amazon Linux - 1.5 (MXNet with MKL Support) (ami-7cb9896b)'

Python version and distribution:
Python 2.7.12 (default, Sep  1 2016, 22:14:00)
[GCC 4.8.3 20140911 (Red Hat 4.8.3-9)] on linux2

## Error Message:

>>> model.fit(X=data_train,
...           eval_metric=mx.metric.np(Perplexity),
...           batch_end_callback=mx.callback.Speedometer(batch_size, 20),
...           epoch_end_callback=mx.callback.do_checkpoint("obama"))
[22:25:36] /home/ec2-user/src/mxnet/dmlc-core/include/dmlc/logging.h:235: [22:25:36] src/symbol/symbol.cc:155: Symbol.InferShapeKeyword argument name data not found.
Candidate arguments:
        [0]data/0
        [1]embed_weight
        [2]l0_i2h_weight
        [3]l0_i2h_bias
        [4]l0_init_h
        [5]l0_h2h_weight
        [6]l0_h2h_bias
        [7]l0_init_c
        [8]l1_i2h_weight
        [9]l1_i2h_bias
        [10]l1_init_h
        [11]l1_h2h_weight
        [12]l1_h2h_bias
        [13]l1_init_c
        [14]l2_i2h_weight
        [15]l2_i2h_bias
        [16]l2_init_h
        [17]l2_h2h_weight
        [18]l2_h2h_bias
        [19]l2_init_c
        [20]cls_weight
        [21]cls_bias
        [22]label/0
        [23]data/1
        [24]label/1
        [25]data/2
        [26]label/2
        [27]data/3
        [28]label/3
        [29]data/4
        [30]label/4
        [31]data/5
        [32]label/5
        [33]data/6
        [34]label/6
        [35]data/7
        [36]label/7
        [37]data/8
        [38]label/8
        [39]data/9
        [40]label/9
        [41]data/10
        [42]label/10
        [43]data/11
        [44]label/11
        [45]data/12
        [46]label/12
        [47]data/13
        [48]label/13
        [49]data/14
        [50]label/14
        [51]data/15
        [52]label/15
        [53]data/16
        [54]label/16
        [55]data/17
        [56]label/17
        [57]data/18
        [58]label/18
        [59]data/19
        [60]label/19
        [61]data/20
        [62]label/20
        [63]data/21
        [64]label/21
        [65]data/22
        [66]label/22
        [67]data/23
        [68]label/23
        [69]data/24
        [70]label/24
        [71]data/25
        [72]label/25
        [73]data/26
        [74]label/26
        [75]data/27
        [76]label/27
        [77]data/28
        [78]label/28
        [79]data/29
        [80]label/29
        [81]data/30
        [82]label/30
        [83]data/31
        [84]label/31
        [85]data/32
        [86]label/32
        [87]data/33
        [88]label/33
        [89]data/34
        [90]label/34
        [91]data/35
        [92]label/35
        [93]data/36
        [94]label/36
        [95]data/37
        [96]label/37
        [97]data/38
        [98]label/38
        [99]data/39
        [100]label/39
        [101]data/40
        [102]label/40
        [103]data/41
        [104]label/41
        [105]data/42
        [106]label/42
        [107]data/43
        [108]label/43
        [109]data/44
        [110]label/44
        [111]data/45
        [112]label/45
        [113]data/46
        [114]label/46
        [115]data/47
        [116]label/47
        [117]data/48
        [118]label/48
        [119]data/49
        [120]label/49
        [121]data/50
        [122]label/50
        [123]data/51
        [124]label/51
        [125]data/52
        [126]label/52
        [127]data/53
        [128]label/53
        [129]data/54
        [130]label/54
        [131]data/55
        [132]label/55
        [133]data/56
        [134]label/56
        [135]data/57
        [136]label/57
        [137]data/58
        [138]label/58
        [139]data/59
        [140]label/59
        [141]data/60
        [142]label/60
        [143]data/61
        [144]label/61
        [145]data/62
        [146]label/62
        [147]data/63
        [148]label/63
        [149]data/64
        [150]label/64
        [151]data/65
        [152]label/65
        [153]data/66
        [154]label/66
        [155]data/67
        [156]label/67
        [157]data/68
        [158]label/68
        [159]data/69
        [160]label/69
        [161]data/70
        [162]label/70
        [163]data/71
        [164]label/71
        [165]data/72
        [166]label/72
        [167]data/73
        [168]label/73
        [169]data/74
        [170]label/74
        [171]data/75
        [172]label/75
        [173]data/76
        [174]label/76
        [175]data/77
        [176]label/77
        [177]data/78
        [178]label/78
        [179]data/79
        [180]label/79
        [181]data/80
        [182]label/80
        [183]data/81
        [184]label/81
        [185]data/82
        [186]label/82
        [187]data/83
        [188]label/83
        [189]data/84
        [190]label/84
        [191]data/85
        [192]label/85
        [193]data/86
        [194]label/86
        [195]data/87
        [196]label/87
        [197]data/88
        [198]label/88
        [199]data/89
        [200]label/89
        [201]data/90
        [202]label/90
        [203]data/91
        [204]label/91
        [205]data/92
        [206]label/92
        [207]data/93
        [208]label/93
        [209]data/94
        [210]label/94
        [211]data/95
        [212]label/95
        [213]data/96
        [214]label/96
        [215]data/97
        [216]label/97
        [217]data/98
        [218]label/98
        [219]data/99
        [220]label/99
        [221]data/100
        [222]label/100
        [223]data/101
        [224]label/101
        [225]data/102
        [226]label/102
        [227]data/103
        [228]label/103
        [229]data/104
        [230]label/104
        [231]data/105
        [232]label/105
        [233]data/106
        [234]label/106
        [235]data/107
        [236]label/107
        [237]data/108
        [238]label/108
        [239]data/109
        [240]label/109
        [241]data/110
        [242]label/110
        [243]data/111
        [244]label/111
        [245]data/112
        [246]label/112
        [247]data/113
        [248]label/113
        [249]data/114
        [250]label/114
        [251]data/115
        [252]label/115
        [253]data/116
        [254]label/116
        [255]data/117
        [256]label/117
        [257]data/118
        [258]label/118
        [259]data/119
        [260]label/119
        [261]data/120
        [262]label/120
        [263]data/121
        [264]label/121
        [265]data/122
        [266]label/122
        [267]data/123
        [268]label/123
        [269]data/124
        [270]label/124
        [271]data/125
        [272]label/125
        [273]data/126
        [274]label/126
        [275]data/127
        [276]label/127
        [277]data/128
        [278]label/128

infer_shape error. Arguments:
  softmax_label: (32, 129)
  l2_init_c: (32, 512)
  l0_init_c: (32, 512)
  l1_init_h: (32, 512)
  l0_init_h: (32, 512)
  l2_init_h: (32, 512)
  data: (32, 129)
  l1_init_c: (32, 512)
Traceback (most recent call last):
  File "<stdin>", line 4, in <module>
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 763, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/model.py", line 487, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 459, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/symbol.py", line 526, in _infer_shape_impl
    ctypes.byref(complete)))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.7.0-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [22:25:36] src/symbol/symbol.cc:155: Symbol.InferShapeKeyword argument name data not found.
Candidate arguments:
        [0]data/0
        [1]embed_weight
        [2]l0_i2h_weight
        [3]l0_i2h_bias
        [4]l0_init_h
        [5]l0_h2h_weight
        [6]l0_h2h_bias
        [7]l0_init_c
        [8]l1_i2h_weight
        [9]l1_i2h_bias
        [10]l1_init_h
        [11]l1_h2h_weight
        [12]l1_h2h_bias
        [13]l1_init_c
....

## Minimum reproducible example
I used exactly the same code here:
http://mxnet.io/tutorials/python/char_lstm.html
Note that if I run jupter notebook, the code runs without error. But the code errors when I try to run the code in python. 

## Steps to reproduce
Run the example code in a standalone python session.  The following step gives the error.
model.fit(X=data_train,
          eval_metric=mx.metric.np(Perplexity),
          batch_end_callback=mx.callback.Speedometer(batch_size, 20),
          epoch_end_callback=mx.callback.do_checkpoint("obama"))
The above step generates the error.

**Comment by data-compute-geek** [comment]
I solved the issue. The mxnet version on the AMI is old, and should be updated.
