### ISSUE TITLE
Initialise module with some fixed parameter

### ISSUE THREAD

**Issue by georg-at-github** [dmlc/mxnet#4929]
Hello,

I am using Python 3.5 and trying to pass a fixed (non-trainable) variable ('weights') to a module:

`weight_matrix = mx.nd.array([[[74.8], [117], [67]]])`
`data = mx.sym.Variable('data')`
`label = mx.sym.Variable('softmax_label')  #Shape (1,3); float32`
`weights = mx.sym.Variable('weights')`
`weights = mx.sym.Reshape(data=weights, shape=(3, 1))`
`net = mx.sym.FullyConnected(data=data, name='fc1', num_hidden=128)`
`net = mx.sym.Activation(data=net, name='relu1', act_type="relu")`
`net = mx.sym.FullyConnected(data=net, name='fc2', num_hidden=3)`
`net = mx.sym.SoftmaxActivation(data=net, name='softmax')   #Shape = (1,3); float32`
`net = mx.sym.MakeLoss(mx.sym.dot(mx.sym.square(label - net), weights))`
`mod = mx.mod.Module(net, fixed_param_names=['weights'])`
`mod.fit(train_dataIterator, optimizer_params={'learning_rate': 0.01, 'momentum': 0.9},
        num_epoch=1, arg_params={'weights': weight_matrix}, allow_missing=True)`

This raises the following error:

> [19:37:44] D:\Program Files (x86)\Jenkins\workspace\mxnet\mxnet\dmlc-core\include\dmlc/logging.h:300: [19:37:44] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\operator\tensor\./matrix_op-inl.h:466: dot currently only support 2D*2D array or 1D*1D array(1,3) v.s. ()
infer_shape error. Arguments:
Traceback (most recent call last):
  softmax_label: (1, 3)
  data: (1, 1, 145, 10)
  File "C:\Development\Anaconda3\lib\site-packages\IPython\core\interactiveshell.py", line 2885, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-89-005b424281de>", line 13, in <module>
    num_epoch=1, arg_params={'weights': weight_matrix}, allow_missing=True)
  File "C:\Development\mxnet\Python\mxnet\module\base_module.py", line 388, in fit
    for_training=True, force_rebind=force_rebind)
  File "C:\Development\mxnet\Python\mxnet\module\module.py", line 345, in bind
    grad_req=grad_req)
  File "C:\Development\mxnet\Python\mxnet\module\executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "C:\Development\mxnet\Python\mxnet\module\executor_group.py", line 279, in bind_exec
    shared_group))
  File "C:\Development\mxnet\Python\mxnet\module\executor_group.py", line 483, in _bind_ith_exec
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "C:\Development\mxnet\Python\mxnet\symbol.py", line 542, in infer_shape
    return self._infer_shape_impl(False, *args, **kwargs)
  File "C:\Development\mxnet\Python\mxnet\symbol.py", line 609, in _infer_shape_impl
    ctypes.byref(complete)))
  File "C:\Development\mxnet\Python\mxnet\base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Error in operator dot4: [19:37:44] d:\program files (x86)\jenkins\workspace\mxnet\mxnet\src\operator\tensor\./matrix_op-inl.h:466: dot currently only support 2D*2D array or 1D*1D array(1,3) v.s. ()

It seems as if initialising 'weights' via 'weight_matrix' does not work. I have tried to initialise 'weights' manually by 
`test_mod = mx.mod.Module(weights, fixed_param_names=["weights"])`
`test_mod.bind(data_shapes=[('weights', (1, 3, 1))], for_training=False, force_rebind=True)`
`test_mod.init_params(arg_params={'weights' : weight_matrix})`
and this seems to work, as
`test_mod.get_params()`
yields the desired outcome ('weights_matrix').

Could you suggest any solution?

**Comment by georg-at-github** [comment]
I believe I found the solution: The issue is with the definition of the fit function. It binds the module like this:

`self.bind(data_shapes=train_data.provide_data, label_shapes=train_data.provide_label,
                  for_training=True, force_rebind=force_rebind)`

The problem is the data_shapes attribute: It does not allow to define any other data than the one provided by the data iterator. I have modified the fit function to accept a data_shape parameter, which is then passed to the bind function. This way I managed to solve my problem.
