### ISSUE TITLE
I use PythonNet to import mxnet in the C# and window10, but have a bug, other import is normal.

### ISSUE THREAD

**Issue by whaozl** [dmlc/mxnet#5136]
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\Python27\lib\site-packages\mxnet-0.9.3-py2.7.egg\mxnet\__init__.py", line 24, in <module>
    from . import model
  File "C:\Python27\lib\site-packages\mxnet-0.9.3-py2.7.egg\mxnet\model.py", line 27, in <module>
    from sklearn.base import BaseEstimator
  File "C:\Python27\lib\site-packages\sklearn\__init__.py", line 57, in <module>
    from .base import clone
  File "C:\Python27\lib\site-packages\sklearn\base.py", line 12, in <module>
    from .utils.fixes import signature
  File "C:\Python27\lib\site-packages\sklearn\utils\__init__.py", line 11, in <module>
    from .validation import (as_float_array,
  File "C:\Python27\lib\site-packages\sklearn\utils\validation.py", line 18, in <module>
    from ..utils.fixes import signature
  File "C:\Python27\lib\site-packages\sklearn\utils\fixes.py", line 45, in <module>
    from scipy.special import expit     # SciPy >= 0.10
  File "C:\Python27\lib\site-packages\scipy\special\__init__.py", line 643, in <module>
    from ._ellip_harm import ellip_harm, ellip_harm_2, ellip_normal
  File "C:\Python27\lib\site-packages\scipy\special\_ellip_harm.py", line 7, in <module>
    from ._ellip_harm_2 import _ellipsoid, _ellipsoid_norm
  File "scipy\special\_ellip_harm_2.pyx", line 5, in init scipy.special._ellip_harm_2 (scipy\special\_ellip_harm_2.c:7385)
  File "C:\Python27\lib\site-packages\scipy\integrate\__init__.py", line 59, in <module>
    from ._bvp import solve_bvp
  File "C:\Python27\lib\site-packages\scipy\integrate\_bvp.py", line 10, in <module>
    from scipy.sparse.linalg import splu
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\__init__.py", line 116, in <module>
    from .matfuncs import *
  File "C:\Python27\lib\site-packages\scipy\sparse\linalg\matfuncs.py", line 19, in <module>
    import scipy.misc
  File "C:\Python27\lib\site-packages\scipy\misc\__init__.py", line 62, in <module>
    from .pilutil import *
  File "C:\Python27\lib\site-packages\scipy\misc\pilutil.py", line 19, in <module>
    from PIL import Image, ImageFilter
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 57, in <module>
    __import__("FixTk")
  File "C:\Python27\Lib\lib-tk\FixTk.py", line 59, in <module>
    prefix = convert_path(prefix)
  File "C:\Python27\Lib\lib-tk\FixTk.py", line 37, in convert_path
    ctypes.windll.kernel32.CloseHandle(hdir)
WindowsError: [Error -1073741816] Windows Error 0xC0000008
```

```
---------------------------
Intel(r) Visual Fortran run-time error 
---------------------------
forrtl: error (200): program aborting due to window-CLOSE event
Image              PC                Routine            Line        Source             
KERNELBASE.dll     00007FFF663C7E23  Unknown               Unknown  Unknown
KERNEL32.dll       00007FFF67C18364  Unknown               Unknown  Unknown
ntdll.dll          00007FFF69F370D1  Unknown               Unknown  Unknown
```

this code is :
```java
        static void Main(string[] args)
        {
            PythonEngine.Initialize();
            IntPtr pythonLock = PythonEngine.AcquireLock();
            PythonEngine.RunSimpleString("import sys\n");
            PythonEngine.RunSimpleString("import os\n");
            PythonEngine.RunSimpleString("import mxnet as mx\n");
            PyObject po = PythonEngine.RunString("os.getcwd()");
            Console.WriteLine(po.Repr());
            PythonEngine.ReleaseLock(pythonLock);
            PythonEngine.Shutdown();
        }
```

**Comment by denfromufa** [comment]
This is similar to this issue, try suggestion from here:

https://github.com/pythonnet/pythonnet/issues/152

**Comment by whaozl** [comment]
@denfromufa `Py.Import("pip")` work, but `PythonEngine.RunSimpleString("import mxnet as mx\n")` also don't work.

**Comment by denfromufa** [comment]
@whaozl where did you get binaries for mxnet on Windows, Python 2.7?

**Comment by denfromufa** [comment]
did you try the suggestions from the link above?

**Comment by whaozl** [comment]
I solve this problem, Thank you very much, I reinstall this python2.7 and pythonnet. mxnet I compile the resource code.
