### ISSUE TITLE
Problem in SliceChannel with a buckteting cnn-lstm-ctc model for ocr tasks.

### ISSUE THREAD

**Issue by xinghedyc** [dmlc/mxnet#5162]
## Environment info
Operating System: ubuntu 16.04

Compiler: gcc 5.4

Package used (Python/R/Scala/Julia): Python

MXNet version: 0.9.3

Python version and distribution: Anaconda 2.7.11

## Error Message:
Please paste the full error message, including stack trace.
when I train my model, the error occurs like this:
```
[23:04:39] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
Traceback (most recent call last):
  File "text_deep_ocr.py", line 162, in <module>
    batch_end_callback  = mx.callback.Speedometer(BATCH_SIZE, 50))
  File "/home/dyc/mxnet/python/mxnet/module/base_module.py", line 410, in fit
    self.forward_backward(data_batch)
  File "/home/dyc/mxnet/python/mxnet/module/base_module.py", line 143, in forward_backward
    self.forward(data_batch, is_train=True)
  File "/home/dyc/mxnet/python/mxnet/module/bucketing_module.py", line 261, in forward
    data_batch.provide_label)
  File "/home/dyc/mxnet/python/mxnet/module/bucketing_module.py", line 208, in switch_bucket
    symbol, data_names, label_names = self._sym_gen(bucket_key)
  File "text_deep_ocr.py", line 93, in sym_gen
    num_label = num_label,dropout=0.5),('data','l0_init_c','l1_init_c','l0_init_h','l1_init_h'), ('label',)
  File "/home/dyc/mxnet/example/warpctc/text_lstm.py", line 134, in bi_lstm_unroll
    column_features = mx.sym.SliceChannel(data=conv, num_outputs=seq_len,axis=3, squeeze_axis=1)
  File "/home/dyc/mxnet/python/mxnet/_ctypes/symbol.py", line 181, in creator
    ctypes.byref(sym_handle)))
  File "/home/dyc/mxnet/python/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Invalid Parameter format for num_outputs expect int but value='None', in operator SliceChannel(name="", axis="3", squeeze_axis="1", num_outputs="None")
```
## Minimum reproducible example
```
def sym_gen(seq_len):
    return bi_lstm_unroll(seq_len,
                       num_hidden=num_hidden,
                       num_label = num_label,dropout=0.5),('data','l0_init_c','l1_init_c','l0_init_h','l1_init_h'),('label',)
```
```
model = mx.mod.BucketingModule(
    sym_gen             = sym_gen,
    default_bucket_key  = 40,
    context             = contexts)
```
my lstm model :
```
def bi_lstm_unroll(seq_len,
                num_hidden, num_label,dropout=0):
    last_states = []
    last_states.append(LSTMState(c = mx.sym.Variable("l0_init_c"), h = mx.sym.Variable("l0_init_h")))
    last_states.append(LSTMState(c = mx.sym.Variable("l1_init_c"), h = mx.sym.Variable("l1_init_h")))
    forward_param = LSTMParam(i2h_weight=mx.sym.Variable("l0_i2h_weight"),
                              i2h_bias=mx.sym.Variable("l0_i2h_bias"),
                              h2h_weight=mx.sym.Variable("l0_h2h_weight"),
                              h2h_bias=mx.sym.Variable("l0_h2h_bias"))
    backward_param = LSTMParam(i2h_weight=mx.sym.Variable("l1_i2h_weight"),
                              i2h_bias=mx.sym.Variable("l1_i2h_bias"),
                              h2h_weight=mx.sym.Variable("l1_h2h_weight"),
                              h2h_bias=mx.sym.Variable("l1_h2h_bias"))
    assert(len(last_states) == 2)

    # embeding layer
    data = mx.sym.Variable('data')
    label = mx.sym.Variable('label')
    #mask  = mx.sym.Variable('mask')
    conv=lenet(data)
    #conv = vggnet(data)
    column_features = mx.sym.SliceChannel(data=conv, num_outputs=seq_len,axis=3, squeeze_axis=1)
    #masks = mx.sym.SliceChannel(data=mask,  num_outputs=seq_len, squeeze_axis=1)
    hidden_all = []
    forward_hidden = []
    for seqidx in range(seq_len):
        #mask_in = masks[seqidx]
        hidden =mx.sym.Flatten(data=column_features[seqidx])
        if dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=dropout)
        next_state = lstm(num_hidden, indata=hidden,
                          #mask = mask_in,
                          prev_state=last_states[0],
                          param=forward_param,
                          seqidx=seqidx, layeridx=0)
        hidden = next_state.h
        last_states[0] = next_state
        if dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=dropout)
  
        forward_hidden.append(hidden)


    backward_hidden = []
    for seqidx in range(seq_len):
        k = seq_len - seqidx - 1
        #mask_in_back = masks[k]
        hidden =mx.sym.Flatten(data=column_features[k])
        if dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=dropout)
        next_state = lstm(num_hidden, indata=hidden,
                          #mask = mask_in_back,
                          prev_state=last_states[1],
                          param=backward_param,
                          seqidx=k, layeridx=1)
        hidden = next_state.h
        last_states[1] = next_state
        if dropout > 0.:
            hidden = mx.sym.Dropout(data=hidden, p=dropout)
        backward_hidden.insert(0, hidden)
        
    hidden_all = []
    for i in range(seq_len):
        hidden_all.append(mx.sym.Concat(*[forward_hidden[i], backward_hidden[i]], dim=1))

    hidden_concat = mx.sym.Concat(*hidden_all, dim=0)
    pred = mx.sym.FullyConnected(data=hidden_concat, num_hidden=4119)
    print (pred.infer_shape(data=(32,3,32,320)))
    label = mx.sym.Reshape(data=label, shape=(-1,))
    label = mx.sym.Cast(data = label, dtype = 'int32')
    #does Warp-CTC support bucketing?
    sm = mx.sym.WarpCTC(data=pred, label=label, label_length = num_label, input_length = seq_len)
    return sm
```
and I do provide bucket_key in each data_batch:
```
class SimpleBatch(object):
    def __init__(self, data_names, data, label_names, label, bucket_key):
        self.data = data
        self.label = label
        self.data_names = data_names
        self.label_names = label_names
        self.bucket_key = bucket_key
```
```
data_batch = SimpleBatch(data_names, data_all, label_names, label_all,(buck_idx+1)*self.factor)
```

## What have you tried to solve it?

1.make sure I do provide bucket_key and default_bucket_key

**Comment by Godricly** [comment]
What is buck_idx+1*self.factor doing? I didnt see any connection between it and the seq_len here. Also the warpctc requires label_length. is your  label_length fixed all the time ?

**Comment by Godricly** [comment]
```python
    def sym_gen(bucket_key):
        label_length, lstm_length = bucket_key.split(',')
        lstm_length = int(lstm_length)
        label_length = int(label_length)
```

 what I passed in is a string like '1,2'. I split it and convert it to int for network generation.

**Comment by xinghedyc** [comment]
@Godricly  my label_length is fixed ,and ( buck_idx+1)*self.factor is actually equal to bucket_key.

**Comment by xinghedyc** [comment]
@Godricly I removed the mx.io.PrefetchingIter, this problem solved.
However new problem occurd:
```
  File "text_deep_ocr.py", line 162, in <module>
    batch_end_callback  = mx.callback.Speedometer(BATCH_SIZE, 50))
  File "/home/dyc/mxnet/python/mxnet/module/base_module.py", line 410, in fit
    self.forward_backward(data_batch)
  File "/home/dyc/mxnet/python/mxnet/module/base_module.py", line 143, in forward_backward
    self.forward(data_batch, is_train=True)
  File "/home/dyc/mxnet/python/mxnet/module/bucketing_module.py", line 261, in forward
    data_batch.provide_label)
  File "/home/dyc/mxnet/python/mxnet/module/bucketing_module.py", line 214, in switch_bucket
    force_rebind=False, shared_module=self._curr_module)
  File "/home/dyc/mxnet/python/mxnet/module/module.py", line 345, in bind
    grad_req=grad_req)
  File "/home/dyc/mxnet/python/mxnet/module/executor_group.py", line 187, in __init__
    self.bind_exec(data_shapes, label_shapes, shared_group)
  File "/home/dyc/mxnet/python/mxnet/module/executor_group.py", line 279, in bind_exec
    shared_group))
  File "/home/dyc/mxnet/python/mxnet/module/executor_group.py", line 532, in _bind_ith_exec
    arg_arr = shared_exec.arg_dict[name]
KeyError: 'convolution7_weight'
```

**Comment by Godricly** [comment]
it looks like that variable is missing. Can you double check your network and your iter?

**Comment by xinghedyc** [comment]
@Godricly  Thanks a lot for your suggestion, I solve the problem by adding name to each symbol ,
such as :
```
conv1 = mx.symbol.Convolution(name='conv1',data=data, kernel=(3,3), num_filter=64,pad=(1,1))
```

**Comment by xinghedyc** [comment]
problem sovled
