### ISSUE TITLE
SqueezeNet converted from caffemodel: mismatch shape results mod.set_params ERROR

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5238]
I recently downloaded caffemodel from [DeepScale/SqueezeNet](https://github.com/DeepScale/SqueezeNet) and converted caffemodel(**deploy.prototxt, squeezenet_v1.0.caffemodel** in SqueezeNet_v1.0 directory) to MXNet model using MXNet caffeconvert tool.

After writing `run_inference.py` according to official guide(how to use pretrained model to predict), I ran `python run_infercen.py`. It outputed below error messages(see **Error Message**):

## Environment info

- Operating System: TegraX1 Ubuntu 16.04.2 LTS
- Linux tegra-ubuntu 3.10.96-tegra
- Compiler: gcc version 5.4.0 20160609 (Ubuntu/Linaro 5.4.0-6ubuntu1~16.04.4)
- Package used (Python/R/Scala/Julia):python
- MXNet version:0.9.4
- Or if installed from source: Yes
- Python version and distribution: Python 2.7.12

## Error Message:
```shell
(py-Test-MXNet-OpenBLAS) yuanshuai@tegra-ubuntu:~/sdcard/code/mxnet_inference/SqueezeNet/SqueezeNet_v1.0$ python run_inference.py 
[14:56:41] **/mnt/sdcard/yuanshuai/code/mxnet_openblas/dmlc-core/include/dmlc/./logging.h:300: [14:56:41] src/ndarray/ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (1,) to.shape=(1,1000,1)**

Stack trace returned 7 entries:
[bt] (0) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x48) [0x7f8e4a9520]
[bt] (1) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet10CopyFromToERKNS_7NDArrayEPS0_i+0x388) [0x7f8ea85210]
[bt] (2) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x80d330) [0x7f8ea2a330]
[bt] (3) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0xd3c) [0x7f8ecdbfc4]
[bt] (4) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f8fabbe60]
[bt] (5) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f8fabc7b8]
[bt] (6) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f8fadbb30]

Traceback (most recent call last):
  **File "run_inference.py", line 30, in <module>
    mod.set_params(arg_params, aux_params)
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/base_module.py", line 557, in set_params
    allow_missing=allow_missing, force_init=force_init)**
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/module.py", line 264, in init_params
    _impl(desc, arr, arg_params)
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/module/module.py", line 252, in _impl
    cache_arr.copyto(arr)
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/ndarray.py", line 556, in copyto
    return _internal._copyto(self, out=other)
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [14:56:41] src/ndarray/ndarray.cc:239: Check failed: from.shape() == to->shape() operands shape mismatchfrom.shape = (1,) to.shape=(1,1000,1)

Stack trace returned 7 entries:
[bt] (0) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN4dmlc15LogMessageFatalD1Ev+0x48) [0x7f8e4a9520]
[bt] (1) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN5mxnet10CopyFromToERKNS_7NDArrayEPS0_i+0x388) [0x7f8ea85210]
[bt] (2) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(+0x80d330) [0x7f8ea2a330]
[bt] (3) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(MXImperativeInvoke+0xd3c) [0x7f8ecdbfc4]
[bt] (4) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call_SYSV+0x64) [0x7f8fabbe60]
[bt] (5) /usr/lib/aarch64-linux-gnu/libffi.so.6(ffi_call+0xc0) [0x7f8fabc7b8]
[bt] (6) /mnt/sdcard/yuanshuai/virtualenvs/py-Test-MXNet-OpenBLAS/lib/python2.7/lib-dynload/_ctypes.aarch64-linux-gnu.so(_ctypes_callproc+0x670) [0x7f8fadbb30]
```
## What have you tried to solve it?

I thought problem may be about input shape(according to the key word **shape mismatch**). However, I tried other models(such as vgg16) with running a wrong input shape. I found a mismatch error is same as converted SqueezeNet.

So, my problem became what's matching input shape of SqueezeNet. I found input size is **224*224** in [SqueezeNet papar](http://arxiv.org/abs/1602.07360), but I tried...... 

1. To find the matching size, I tried running a script, making input size from 100 to 500. However, I failed. Maybe I should try more bigger size?　＿（：з」∠）＿
2. (Trying) Due to caffemodel created by caffe, maybe I can try to install the MXNet with Caffe interface....
3. (Trying) According to symbol(SqueezeNet's symbol.py can be found on the Internet) and params file converted from caffemodel, maybe a third solution. Because I found there're some SqueezeNet model(only contains symbol) wiritten by MXNet, I think maybe author want to train a SqueezeNet model, not predict using pretraind model.

## Key part code
```Python
sym, arg_params, aux_params = mx.model.load_checkpoint('squeezenet_v1.0.caffe2mxnetmodel_deploy', 1)
arg_params['prob_label'] = mx.nd.array([0])

mod = mx.mod.Module(symbol=sym, context=mx.cpu(0))
data_shape = (224, 224)
#data_shape = (int(sys.argv[1]), int(sys.argv[1]))
print data_shape
predict_times = 1 
mod.bind(for_training=False, data_shapes=[('data', (1, 3, data_shape[0], data_shape[1]))])
mod.set_params(arg_params, aux_params)

# Before prediction, original image is resized to data_shape too!
img = cv2.resize(img, data_shape)
```

It always logged as above error message. Sigh......

**Comment by tornadomeet** [comment]
mxnet already provide the converted squeeze model in http://data.dmlc.ml/mxnet/models/imagenet/squeezenet/

**Comment by ysh329** [comment]
@tornadomeet Thanks a lot. However, I have a question: If I try two solutions below, could I success?

1. Due to caffemodel created by caffe, maybe I can try to install the MXNet with Caffe interface....
2. According to symbol(SqueezeNet's symbol.py can be found on the Internet) and params file converted from caffemodel, I can try to copy the params into symbol to make prediction. Because I found there're some SqueezeNet model(only contains symbol) wiritten by MXNet, I think maybe author want to train a SqueezeNet model, not predict using pretraind model.
