### ISSUE TITLE
Problem with 'test' after saving checkpoint with -stack-rnn True for cudnn_lstm_bucketing.py example

### ISSUE THREAD

**Issue by sergeykolychev** [dmlc/mxnet#5328]
```
/mxnet/example/rnn$ python cudnn_lstm_bucketing.py --gpus 0 --model-prefix fused-stack --load-epoch 1 --stack-rnn 1 --test
WARNING: discarded 89 sentences longer than the largest bucket.
WARNING: discarded 4 sentences longer than the largest bucket.
Traceback (most recent call last):
  File "cudnn_lstm_bucketing.py", line 194, in <module>
    test(args)
  File "cudnn_lstm_bucketing.py", line 175, in test
    _, arg_params, aux_params = mx.rnn.load_rnn_checkpoint(stack, args.model_prefix, args.load_epoch)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/rnn/rnn.py", line 76, in load_rnn_checkpoint
    arg = cell.pack_weights(arg)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/rnn/rnn_cell.py", line 885, in pack_weights
    args = cell.pack_weights(args)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/rnn/rnn_cell.py", line 393, in pack_weights
    weight.append(args.pop(wname))
KeyError: 'lstm_l0_i2h_i_weight'
[10:25:06] /home/ubuntu/mxnet/dmlc-core/include/dmlc/./logging.h:300: [10:25:06] /home/ubuntu/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: err == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR

Stack trace returned 5 entries:
[bt] (0) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZN7mshadow9NewStreamINS_3gpuEEEPNS_6StreamIT_EEbb+0x2168) [0x7fce86f8c028]
[bt] (1) /usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/libmxnet.so(_ZNSt17_Function_handlerIFvvEZZN5mxnet6engine23ThreadedEnginePerDevice13PushToExecuteEPNS2_8OprBlockEbENKUlvE1_clEvEUlvE_E9_M_invokeERKSt9_Any_data+0xcf) [0x7fce86fb280f]
[bt] (2) /usr/lib/x86_64-linux-gnu/libstdc++.so.6(+0xb8c80) [0x7fce773b9c80]
[bt] (3) /lib/x86_64-linux-gnu/libpthread.so.0(+0x76ba) [0x7fce9c8876ba]
[bt] (4) /lib/x86_64-linux-gnu/libc.so.6(clone+0x6d) [0x7fce9c5bd82d]

[10:25:06] /home/ubuntu/mxnet/dmlc-core/include/dmlc/./logging.h:300: [10:25:06] /home/ubuntu/mxnet/mshadow/mshadow/./stream_gpu-inl.h:125: Check failed: err == CUDNN_STATUS_SUCCESS (4 vs. 0) CUDNN_STATUS_INTERNAL_ERROR
```

**Comment by sergeykolychev** [comment]
@piiswrong Basically 'test' does not work if the checkpoint is saved with --stack-rnn True flag.
Is this known issue ?
