### ISSUE TITLE
neural-style example: error with --gpu 0, ok with --gpu -1

### ISSUE THREAD

**Issue by matt32106** [dmlc/mxnet#5378]
## Environment info
Operating System: Ubuntu 16.04
Python version and distribution: 2.7
CUDA V8.0.61 & cuDNN 5.1
NVIDIA GTX1060
MXNET commit parse head abf4c76804a133c4e4adba1b817cbf50cafaf243
I can run R examples on gpu with no error.

## Steps to reproduce
Run the neural-style example:
```
hippo@hippo-camp:~/mxnet/example/neural-style$ python nstyle.py --gpu 0
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
[23:38:10] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[23:38:10] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[23:38:10] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[23:38:10] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[23:38:10] src/operator/tensor/./matrix_op-inl.h:156: Using target_shape will be deprecated.
[23:38:10] /home/travis/build/dmlc/mxnet-distro/mxnet-build/dmlc-core/include/dmlc/./logging.h:300: [23:38:10] src/c_api/c_api_ndarray.cc:270: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 23 entries:
[bt] (0) /home/hippo/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xa2c9c) [0x7fde815a3c9c]
[bt] (1) /home/hippo/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0x3646) [0x7fde81daf466]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fde8e700e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fde8e7008ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fde8e9103df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fde8e914d82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (10) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (11) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (12) python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (13) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (14) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (15) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (16) python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (17) python() [0x4f1def]
[bt] (18) python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (19) python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (20) python(Py_Main+0x68a) [0x49e14a]
[bt] (21) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fde8f7c8830]
[bt] (22) python(_start+0x29) [0x49d9d9]


Traceback (most recent call last):
  File "nstyle.py", line 259, in <module>
    train_nstyle(args)
  File "nstyle.py", line 167, in train_nstyle
    model_executor = model_module.get_executor(gram, content, size, dev)
  File "/home/hippo/mxnet/example/neural-style/model_vgg19.py", line 53, in get_executor
    arg_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=ctx) for shape in arg_shapes]))
  File "/home/hippo/.local/lib/python2.7/site-packages/mxnet/ndarray.py", line 1055, in zeros
    return _internal._zeros(shape=shape, ctx=ctx, dtype=dtype)
  File "/home/hippo/.local/lib/python2.7/site-packages/mxnet/_ctypes/ndarray.py", line 131, in generic_ndarray_function
    c_array(ctypes.c_char_p, [c_str(str(i)) for i in kwargs.values()])))
  File "/home/hippo/.local/lib/python2.7/site-packages/mxnet/base.py", line 75, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:38:10] src/c_api/c_api_ndarray.cc:270: Operator _zeros cannot be run; requires at least one of FCompute<xpu>, NDArrayFunction, FCreateOperator be registered

Stack trace returned 23 entries:
[bt] (0) /home/hippo/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(+0xa2c9c) [0x7fde815a3c9c]
[bt] (1) /home/hippo/.local/lib/python2.7/site-packages/mxnet/libmxnet.so(MXImperativeInvoke+0x3646) [0x7fde81daf466]
[bt] (2) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call_unix64+0x4c) [0x7fde8e700e40]
[bt] (3) /usr/lib/x86_64-linux-gnu/libffi.so.6(ffi_call+0x2eb) [0x7fde8e7008ab]
[bt] (4) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(_ctypes_callproc+0x48f) [0x7fde8e9103df]
[bt] (5) /usr/lib/python2.7/lib-dynload/_ctypes.x86_64-linux-gnu.so(+0x11d82) [0x7fde8e914d82]
[bt] (6) python(PyObject_Call+0x43) [0x4b0cb3]
[bt] (7) python(PyEval_EvalFrameEx+0x5faf) [0x4c9faf]
[bt] (8) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (9) python(PyEval_EvalFrameEx+0x68d1) [0x4ca8d1]
[bt] (10) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (11) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (12) python(PyEval_EvalFrameEx+0x5d8f) [0x4c9d8f]
[bt] (13) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (14) python(PyEval_EvalFrameEx+0x6099) [0x4ca099]
[bt] (15) python(PyEval_EvalCodeEx+0x255) [0x4c2765]
[bt] (16) python(PyEval_EvalCode+0x19) [0x4c2509]
[bt] (17) python() [0x4f1def]
[bt] (18) python(PyRun_FileExFlags+0x82) [0x4ec652]
[bt] (19) python(PyRun_SimpleFileExFlags+0x191) [0x4eae31]
[bt] (20) python(Py_Main+0x68a) [0x49e14a]
[bt] (21) /lib/x86_64-linux-gnu/libc.so.6(__libc_start_main+0xf0) [0x7fde8f7c8830]
[bt] (22) python(_start+0x29) [0x49d9d9]
```
If i run with --gpu -1 (i.e. CPU) it works.

**Comment by matt32106** [comment]
My bad, ii forgot to reinstall mxnet python after updating.
Running the following solved the problem:
```
# Install MXNet Python package
    cd ~/mxnet/python
    sudo python setup.py install
```
