### ISSUE TITLE
import MXNet Error: undefined symbol: gotoblas

### ISSUE THREAD

**Issue by ysh329** [dmlc/mxnet#5479]
After I install MXNet, I tried to import. Hower, it output below message:

```shell
 yuens@Spark  ~  python -c "import mxnet as mx" 
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 11, in <module>
    import numpy as np
  File "/usr/lib/python2.7/dist-packages/numpy/__init__.py", line 180, in <module>
    from . import add_newdocs
  File "/usr/lib/python2.7/dist-packages/numpy/add_newdocs.py", line 13, in <module>
    from numpy.lib import add_newdoc
  File "/usr/lib/python2.7/dist-packages/numpy/lib/__init__.py", line 8, in <module>
    from .type_check import *
  File "/usr/lib/python2.7/dist-packages/numpy/lib/type_check.py", line 11, in <module>
    import numpy.core.numeric as _nx
  File "/usr/lib/python2.7/dist-packages/numpy/core/__init__.py", line 14, in <module>
    from . import multiarray
ImportError: /usr/lib/libblas.so.3: undefined symbol: gotoblas

```

**Comment by DevinCheung** [comment]
@ysh329 could you please describe how you solve it in detail? Thx

**Comment by ysh329** [comment]
I forgot detailed describe. try to re-install openblas.
