### ISSUE TITLE
OSError: .../anaconda3/lib/python3.6/site-packages/mxnet-0.9.4-py3.6.egg/mxnet/libmxnet.so: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringEv

### ISSUE THREAD

**Issue by wangg12** [dmlc/mxnet#5551]
## Environment info
Operating System: `Ubuntu 16.04`
Compiler: `gcc-4.8.5`

Package used (Python/R/Scala/Julia): `python 3.6`

MXNet version: `0.9.4`

Or if installed from source: `Yes`

MXNet commit hash (`git rev-parse HEAD`): `e4f73f1f4e76397992c4b0a33c139d52b4b7af0e`

Python version and distribution: `3.6`

## Error Message:
Please paste the full error message, including stack trace.
```
Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 12:22:00) 
[GCC 4.4.7 20120313 (Red Hat 4.4.7-1)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import mxnet
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/.../anaconda3/lib/python3.6/site-packages/mxnet-0.9.4-py3.6.egg/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/.../anaconda3/lib/python3.6/site-packages/mxnet-0.9.4-py3.6.egg/mxnet/base.py", line 46, in <module>
    _LIB = _load_lib()
  File "/.../anaconda3/lib/python3.6/site-packages/mxnet-0.9.4-py3.6.egg/mxnet/base.py", line 38, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)
  File "/.../anaconda3/lib/python3.6/ctypes/__init__.py", line 344, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /.../anaconda3/lib/python3.6/site-packages/mxnet-0.9.4-py3.6.egg/mxnet/libmxnet.so: undefined symbol: _ZNK6google8protobuf11MessageLite25InitializationErrorStringEv
```

**Comment by Manideep08** [comment]
I am also facing the same issue and my configuration is same
