### ISSUE TITLE
[Example]kaggle-ndsb1 : 'Namespace' object has no attribute 'model_prefix'

### ISSUE THREAD

**Issue by louiskoo520** [dmlc/mxnet#5594]
C:\ProgramData\Anaconda2\python.exe D:/Python/code/MXnet/example/kaggle-ndsb1/train_dsb.py
Namespace(batch_size=64, clip_gradient=5.0, data_dir='data48/', gpus=None, kv_store='local', load_epoch=None, log_dir='/tmp/', log_file=None, lr=0.01, lr_factor=1, lr_factor_epoch=15, network='dsb', num_classes=121, num_epochs=100, num_examples=20000, save_model_prefix='./models/sample_net')
2017-03-28 09:47:44,496 Node[0] start with arguments Namespace(batch_size=64, clip_gradient=5.0, data_dir='data48/', gpus=None, kv_store='local', load_epoch=None, log_dir='/tmp/', log_file=None, lr=0.01, lr_factor=1, lr_factor_epoch=15, network='dsb', num_classes=121, num_epochs=100, num_examples=20000, save_model_prefix='./models/sample_net')
Traceback (most recent call last):
  File "D:/Python/code/MXnet/example/kaggle-ndsb1/train_dsb.py", line 87, in <module>
    train_model.fit(args, net, get_iterator)
  File "D:\Python\code\MXnet\example\kaggle-ndsb1\train_model.py", line 29, in fit
    model_prefix = args.model_prefix
AttributeError: 'Namespace' object has no attribute 'model_prefix'

**Comment by louiskoo520** [comment]
Then I set as this:
    parser.add_argument('--model-prefix', type=str,default= "models/",
                    help='the prefix of the model to load/save')
Now I got this error:

C:\ProgramData\Anaconda2\python.exe D:/Python/code/MXnet/example/kaggle-ndsb1/train_dsb.py
Namespace(batch_size=64, clip_gradient=5.0, data_dir='data48/', gpus=None, kv_store='local', load_epoch=None, log_dir='/tmp/', log_file=None, lr=0.01, lr_factor=1, lr_factor_epoch=15, model_prefix='models/', network='dsb', num_classes=121, num_epochs=100, num_examples=20000, save_model_prefix='./models/sample_net')
2017-03-28 10:06:12,677 Node[0] start with arguments Namespace(batch_size=64, clip_gradient=5.0, data_dir='data48/', gpus=None, kv_store='local', load_epoch=None, log_dir='/tmp/', log_file=None, lr=0.01, lr_factor=1, lr_factor_epoch=15, model_prefix='models/', network='dsb', num_classes=121, num_epochs=100, num_examples=20000, save_model_prefix='./models/sample_net')
[10:06:12] D:\Python\MXNet\mxnet1\mxnet\src\io\iter_image_recordio.cc:220: ImageRecordIOParser: data48/tr.rec, use 3 threads for decoding..
[10:06:18] D:\Python\MXNet\mxnet1\mxnet\src\io\iter_image_recordio.cc:220: ImageRecordIOParser: data48/va.rec, use 3 threads for decoding..
D:\Python\code\MXnet\example\kaggle-ndsb1\train_model.py:79: DeprecationWarning: mxnet.model.FeedForward has been deprecated. Please use mxnet.mod.Module instead.
  **model_args)
[10:06:22] d:\python\mxnet\mxnet1\mxnet\dmlc-core\include\dmlc\./logging.h:300: [10:06:22] d:\python\mxnet\mxnet1\mxnet\src\operator\./pooling-inl.h:196: Check failed: param_.kernel[0] <= dshape[2] + 2 * param_.pad[0] kernel size (9) exceeds input (8 padded to 8)
Traceback (most recent call last):
  File "D:/Python/code/MXnet/example/kaggle-ndsb1/train_dsb.py", line 89, in <module>
    train_model.fit(args, net, get_iterator)
  File "D:\Python\code\MXnet\example\kaggle-ndsb1\train_model.py", line 100, in fit
    epoch_end_callback = checkpoint)
  File "C:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.4-py2.7.egg\mxnet\model.py", line 772, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "C:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.4-py2.7.egg\mxnet\model.py", line 500, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
infer_shape error. Arguments:
  File "C:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.4-py2.7.egg\mxnet\symbol.py", line 637, in infer_shape
  data: (64L, 3L, 36L, 36L)
  softmax_label: (64L,)
    res = self._infer_shape_impl(False, *args, **kwargs)
  File "C:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.4-py2.7.egg\mxnet\symbol.py", line 720, in _infer_shape_impl
    ctypes.byref(complete)))
  File "C:\ProgramData\Anaconda2\lib\site-packages\mxnet-0.9.4-py2.7.egg\mxnet\base.py", line 78, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base

**Comment by yajiedesign** [comment]
This issue is closed due to lack of activity in the last 90 days. Feel free to reopen if this is still an active issue. Thanks!
