### ISSUE TITLE
Windows error 126!

### ISSUE THREAD

**Issue by janelu9** [dmlc/mxnet#5623]
Traceback (most recent call last):

  File "<ipython-input-1-30eb4f951ea5>", line 1, in <module>
    import mxnet

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.9.3-py2.7.egg\mxnet\__init__.py", line 7, in <module>
    from .base import MXNetError

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.9.3-py2.7.egg\mxnet\base.py", line 43, in <module>
    _LIB = _load_lib()

  File "D:\Program Files\Anaconda2\lib\site-packages\mxnet-0.9.3-py2.7.egg\mxnet\base.py", line 35, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_GLOBAL)

  File "D:\Program Files\Anaconda2\lib\ctypes\__init__.py", line 362, in __init__
    self._handle = _dlopen(self._name, mode)

**Comment by janelu9** [comment]
mxnet 's version is 0.9.4,  the libmxnet.dll is build by vs2015

**Comment by yajiedesign** [comment]
lost depended dll.please put depended dll in env Path or python root path

**Comment by janelu9** [comment]
well, thank you

**Comment by sandycs** [comment]
lost depended dll.please put depended dll in env Path or python root path？
what dll are needed?
