### ISSUE TITLE
[scala] Module API: NullPointerException while calling bind() with forTraining=false

### ISSUE THREAD

**Issue by benqua** [dmlc/mxnet#5695]
While doing feature extraction from a pre-trained vgg16 network, a NullPointerException is thrown when bind is called with forTraining=false. See code below.

## Error Message:
```
[error] (run-main-0) java.lang.NullPointerException
java.lang.NullPointerException
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.ml$dmlc$mxnet$module$DataParallelExecutorGroup$$bindIthExec(DataParallelExecutorGroup.scala:641)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$bindExec$1.apply(DataParallelExecutorGroup.scala:354)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$$anonfun$bindExec$1.apply(DataParallelExecutorGroup.scala:353)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.TraversableLike$$anonfun$map$1.apply(TraversableLike.scala:234)
	at scala.collection.immutable.Range.foreach(Range.scala:160)
	at scala.collection.TraversableLike$class.map(TraversableLike.scala:234)
	at scala.collection.AbstractTraversable.map(Traversable.scala:104)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.bindExec(DataParallelExecutorGroup.scala:353)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup.<init>(DataParallelExecutorGroup.scala:315)
	at ml.dmlc.mxnet.module.DataParallelExecutorGroup$Builder.build(DataParallelExecutorGroup.scala:223)
	at ml.dmlc.mxnet.module.Module.bind(Module.scala:243)
	at benq.kaggle.natcons.FishDetector1$.main(FishDetector1.scala:36)
	at benq.kaggle.natcons.FishDetector1.main(FishDetector1.scala)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)

```

## Minimum reproducible example
```scala
    val path = "data/fd/windowed/"
    val prefix = "vgg16n"
    val lastLayerBeforeFC = "flatten_0"

    logger.info("Loading model")
    val (sym, argParams, auxParams) = Model.loadCheckpoint(prefix, 0)
    val net = sym.getInternals.get(s"${lastLayerBeforeFC}_output")
    val newArgParams = argParams.filterNot(_._1.contains("fc"))
    logger.info("newArgParams: " +newArgParams.mkString(", "))

    logger.info("get data iterator")
    val imgPath = "data/fd/windowed"
    val batchSize = 64
    val dataIter = ImageDataIter(imgPath, batchSize)

    logger.info("building network")
    val vgg16 = new Module(
      symbolVar = net,
      dataNames = IndexedSeq("data"),
      contexts = Context.gpu(0)
    )
    vgg16.bind(
      dataShapes = dataIter.provideData,
      forTraining = false
    )
    vgg16.initParams(argParams = newArgParams)

```
the NullPointerException is thrown when bind is called.

**Comment by Ldpe2G** [comment]
@benqua  I made a pr to fix this problem.

**Comment by benqua** [comment]
I confirm it now works as expected.
Thank you @Ldpe2G !
