### ISSUE TITLE
[example][rcnn][python] cv2.error

### ISSUE THREAD

**Issue by matt32106** [dmlc/mxnet#5731]
Am trying to run the rcnn example as per the instructinos contained in the README.
I have a recent mxnet, did make clean && make. 
Looks like a problem with opencv but i don't know how to fix it without breaking something else!?

Ubuntu 16.04
mxnet git clone from a few days ago.
Python 2.7.12

```
hippo@hippo-camp:~/mxnet/example/rcnn$ bash script/vgg_voc07.sh 0
Called with argument: Namespace(begin_epoch=0, dataset='PascalVOC', dataset_path='data/VOCdevkit', end_epoch=10, frequent=20, gpus='0', image_set='2007_trainval', kvstore='device', lr=0.001, lr_step='7', network='vgg', no_flip=False, no_shuffle=False, prefix='model/e2e', pretrained='model/vgg16', pretrained_epoch=0, resume=False, root_path='data', work_load_list=None)
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'FIXED_PARAMS': ['conv1', 'conv2'],
 'FIXED_PARAMS_SHARED': ['conv1', 'conv2', 'conv3', 'conv4', 'conv5'],
 'IMAGE_STRIDE': 0,
 'NUM_ANCHORS': 9,
 'NUM_CLASSES': 21,
 'PIXEL_MEANS': array([ 103.939,  116.779,  123.68 ]),
 'RCNN_FEAT_STRIDE': 16,
 'RPN_FEAT_STRIDE': 16,
 'SCALES': [(600, 1000)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': True,
          'HAS_RPN': False,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 16,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 1,
           'BATCH_ROIS': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': True,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_WEIGHTS': array([ 1.,  1.,  1.,  1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'CXX_PROPOSAL': True,
           'END2END': True,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000}}
num_images 5011
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/hippo/Downloads/opencv-3.2.0/modules/core/src/matrix.cpp, line 1931
Traceback (most recent call last):
  File "train_end2end.py", line 185, in <module>
    main()
  File "train_end2end.py", line 182, in main
    lr=args.lr, lr_step=args.lr_step)
  File "train_end2end.py", line 45, in train_net
    for image_set in image_sets]
  File "/home/hippo/mxnet/example/rcnn/rcnn/utils/load_data.py", line 11, in load_gt_roidb
    roidb = imdb.gt_roidb()
  File "/home/hippo/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 84, in gt_roidb
    gt_roidb = [self.load_pascal_annotation(index) for index in self.image_set_index]
  File "/home/hippo/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 100, in load_pascal_annotation
    size = cv2.imread(roi_rec['image']).shape
cv2.error: /home/hippo/Downloads/opencv-3.2.0/modules/core/src/matrix.cpp:1931: error: (-213) Unknown/unsupported array type in function type

Namespace(dataset='PascalVOC', dataset_path='data/VOCdevkit', epoch=10, gpu=0, has_rpn=True, image_set='2007_test', network='vgg', prefix='model/e2e', proposal='rpn', root_path='data', shuffle=False, thresh=0.001, vis=False)
{'ANCHOR_RATIOS': [0.5, 1, 2],
 'ANCHOR_SCALES': [8, 16, 32],
 'FIXED_PARAMS': ['conv1', 'conv2'],
 'FIXED_PARAMS_SHARED': ['conv1', 'conv2', 'conv3', 'conv4', 'conv5'],
 'IMAGE_STRIDE': 0,
 'NUM_ANCHORS': 9,
 'NUM_CLASSES': 21,
 'PIXEL_MEANS': array([ 103.939,  116.779,  123.68 ]),
 'RCNN_FEAT_STRIDE': 16,
 'RPN_FEAT_STRIDE': 16,
 'SCALES': [(600, 1000)],
 'TEST': {'BATCH_IMAGES': 1,
          'CXX_PROPOSAL': True,
          'HAS_RPN': True,
          'NMS': 0.3,
          'PROPOSAL_MIN_SIZE': 16,
          'PROPOSAL_NMS_THRESH': 0.7,
          'PROPOSAL_POST_NMS_TOP_N': 2000,
          'PROPOSAL_PRE_NMS_TOP_N': 20000,
          'RPN_MIN_SIZE': 16,
          'RPN_NMS_THRESH': 0.7,
          'RPN_POST_NMS_TOP_N': 300,
          'RPN_PRE_NMS_TOP_N': 6000},
 'TRAIN': {'ASPECT_GROUPING': True,
           'BATCH_IMAGES': 2,
           'BATCH_ROIS': 128,
           'BBOX_MEANS': [0.0, 0.0, 0.0, 0.0],
           'BBOX_NORMALIZATION_PRECOMPUTED': False,
           'BBOX_REGRESSION_THRESH': 0.5,
           'BBOX_STDS': [0.1, 0.1, 0.2, 0.2],
           'BBOX_WEIGHTS': array([ 1.,  1.,  1.,  1.]),
           'BG_THRESH_HI': 0.5,
           'BG_THRESH_LO': 0.0,
           'CXX_PROPOSAL': True,
           'END2END': False,
           'FG_FRACTION': 0.25,
           'FG_THRESH': 0.5,
           'RPN_BATCH_SIZE': 256,
           'RPN_BBOX_WEIGHTS': [1.0, 1.0, 1.0, 1.0],
           'RPN_CLOBBER_POSITIVES': False,
           'RPN_FG_FRACTION': 0.5,
           'RPN_MIN_SIZE': 16,
           'RPN_NEGATIVE_OVERLAP': 0.3,
           'RPN_NMS_THRESH': 0.7,
           'RPN_POSITIVE_OVERLAP': 0.7,
           'RPN_POSITIVE_WEIGHT': -1.0,
           'RPN_POST_NMS_TOP_N': 2000,
           'RPN_PRE_NMS_TOP_N': 12000}}
num_images 4952
OpenCV Error: The function/feature is not implemented (Unknown/unsupported array type) in type, file /home/hippo/Downloads/opencv-3.2.0/modules/core/src/matrix.cpp, line 1931
Traceback (most recent call last):
  File "test.py", line 41, in <module>
    main()
  File "test.py", line 38, in main
    args.vis, args.shuffle, args.has_rpn, args.proposal, args.thresh)
  File "/home/hippo/mxnet/example/rcnn/rcnn/tools/test_rcnn.py", line 28, in test_rcnn
    roidb = imdb.gt_roidb()
  File "/home/hippo/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 84, in gt_roidb
    gt_roidb = [self.load_pascal_annotation(index) for index in self.image_set_index]
  File "/home/hippo/mxnet/example/rcnn/rcnn/dataset/pascal_voc.py", line 100, in load_pascal_annotation
    size = cv2.imread(roi_rec['image']).shape
cv2.error: /home/hippo/Downloads/opencv-3.2.0/modules/core/src/matrix.cpp:1931: error: (-213) Unknown/unsupported array type in function type



```

**Comment by matt32106** [comment]
I can't say what did not work but problem solved after:
```
sudo pip install opencv-python
git pull
make clean
make
```
