### ISSUE TITLE
How can I resume training on the checkpoint(saved) model

### ISSUE THREAD

**Issue by freesouls** [dmlc/mxnet#592]
for example, I have trained a model for 10 rounds, and save the model successfully. What if I want to go on training base on the saved model, saying, I want to train 10 more rounds. I can not find some documentation.

**Comment by yao5461** [comment]
Hi Binbin,
An example:
```python
pretrained_model = mx.model.FeedForward.load("xxx", 10)  
model = mx.model.FeedForward(symbol=pretrained_model.symbol, arg_params=pretrained_model.arg_params, aux_params=pretrained_model.aux_params, num_epoch=20, begin_epoch=11, .....)
model.fit(...)
```
refer to https://github.com/dmlc/mxnet/issues/479

**Comment by machuck** [comment]
I also have successfully saved the model epoch by epoch using:


mx.model.FeedForward.create(
  ...,
  ...,
  epoch_end_callback=mx.callback.do_checkpoint(prefix) )

now I am trying to load the model to continue, but got the following error:

Traceback (most recent call last):
  File "xxx.py", line 114, in <module>
    loaded = mx.model.FeedForward.load("xxx",150)
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/model.py", line 703, in load
    symbol, arg_params, aux_params = load_checkpoint(prefix, epoch)
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/model.py", line 344, in load_checkpoint
    symbol = sym.load('%s-symbol.json' % prefix)
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/symbol.py", line 768, in load
    check_call(_LIB.MXSymbolCreateFromFile(c_str(fname), ctypes.byref(handle)))
  File "/usr/local/lib/python3.4/dist-packages/mxnet-0.5.0-py3.4.egg/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: Parameter scalar is not presented
