### ISSUE TITLE
python package installation fails with verbatim instructions from install wiki (Ubuntu 14.04)

### ISSUE THREAD

**Issue by worldveil** [dmlc/mxnet#600]
My machine:

```bash
$ uname -a
Linux xxxxxxxx 3.16.0-50-generic #66~14.04.1-Ubuntu SMP Thu Sep 10 17:05:00 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.6
```

I followed the instructions here:
http://mxnet.readthedocs.org/en/latest/build.html

```bash
$ git clone --recursive https://github.com/dmlc/mxnet mxnet
$ sudo apt-get update -y && sudo apt-get upgrade -y
$ sudo apt-get install -y build-essential git libblas-dev libopencv-dev
$ cd mxnet
$ make -j4
$ cd python; sudo python setup.py install
```

The error is:

```
Traceback (most recent call last):
  File "setup.py", line 26, in <module>
    url='https://github.com/dmlc/mxnet')
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 73, in run
    self.do_egg_install()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/install.py", line 96, in do_egg_install
    cmd.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 381, in run
    self.easy_install(spec, not self.no_deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 597, in easy_install
    return self.install_item(None, spec, tmpdir, deps, True)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 648, in install_item
    self.process_distribution(spec, dist, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 694, in process_distribution
    [requirement], self.local_index, self.easy_install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 620, in resolve
    dist = best[req.key] = env.best_match(req, ws, installer)
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 858, in best_match
    return self.obtain(req, installer) # try and download/install
  File "/usr/lib/python2.7/dist-packages/pkg_resources.py", line 870, in obtain
    return installer(requirement)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 616, in easy_install
    return self.install_item(spec, dist.location, tmpdir, deps)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 646, in install_item
    dists = self.install_eggs(spec, download, tmpdir)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 834, in install_eggs
    return self.build_and_install(setup_script, setup_base)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1040, in build_and_install
    self.run_setup(setup_script, setup_base, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/command/easy_install.py", line 1025, in run_setup
    run_setup(setup_script, args)
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 50, in run_setup
    lambda: execfile(
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 100, in run
    return func()
  File "/usr/lib/python2.7/dist-packages/setuptools/sandbox.py", line 52, in <lambda>
    {'__file__':setup_script, '__name__':'__main__'}
  File "setup.py", line 264, in <module>
    
  File "setup.py", line 256, in setup_package
    
  File "/tmp/easy_install-XDSsCy/numpy-1.10.1/numpy/distutils/core.py", line 169, in setup
  File "/usr/lib/python2.7/distutils/core.py", line 151, in setup
    dist.run_commands()
  File "/usr/lib/python2.7/distutils/dist.py", line 953, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/usr/lib/python2.7/dist-packages/setuptools/command/bdist_egg.py", line 177, in run
    self.run_command("egg_info")
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-XDSsCy/numpy-1.10.1/numpy/distutils/command/egg_info.py", line 10, in run
  File "/usr/lib/python2.7/distutils/cmd.py", line 326, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python2.7/distutils/dist.py", line 972, in run_command
    cmd_obj.run()
  File "/tmp/easy_install-XDSsCy/numpy-1.10.1/numpy/distutils/command/build_src.py", line 153, in run
  File "/tmp/easy_install-XDSsCy/numpy-1.10.1/numpy/distutils/command/build_src.py", line 173, in build_sources
  File "/tmp/easy_install-XDSsCy/numpy-1.10.1/numpy/distutils/command/build_src.py", line 262, in build_npy_pkg_config
AttributeError: 'NoneType' object has no attribute 'append'
```

Perhaps I'm missing something simple. I will continue to investigate.

**Comment by mli** [comment]
can you please have a `git pull` and install again? i try it some minutes ago with the same ubuntu and python version, it works fine

**Comment by worldveil** [comment]
I tried `git pull` and installing again, same issue. 

I then tried deleting the entire repo, re-cloning, re-building, and re-installing. Same issue. 

Are you using Python 2.7.6?

**Comment by mli** [comment]
yeah, `Python 2.7.6` with numpy `1.10.1`. @antinucleon @tqchen any idea about the error?

**Comment by worldveil** [comment]
I can confirm this fails with a clean EC2 instance:

```bash
$ uname -a
Linux ip-172-31-26-87 3.13.0-48-generic #80-Ubuntu SMP Thu Mar 12 11:16:15 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
$ python --version
Python 2.7.6
```

and returns the same error.

**Comment by mli** [comment]
@worldveil oh, yeah, i repeated the problem on ec2 too... it looks like due to the numpy automatically installed by `setup.py`

i resolved the this problem by 

```
sudo apt-get install python-numpy
```

it will install a lower version

```
ubuntu@ip-172-30-0-100:~/mxnet/python$ pip list | grep numpy
numpy (1.8.2)
```

but i do have a numpy 1.10.1 installed on a machine it works well. @antinucleon can you have a look at it?

**Comment by tqchen** [comment]
closing due to inactive status, feel free to reopen if there is update

**Comment by wangdelp** [comment]
tried mli's solution, still get the same error: AttributeError: 'NoneType' object has no attribute 'append'. @worldveil  have you solved the error? Thanks

**Comment by qizhuli** [comment]
I had the same problem `AttributeError: 'NoneType' object has no attribute 'append'.` while trying to install mxnet python package. @mli's solution solved my problem beautifully. Thanks @mli!
