### ISSUE TITLE
Create shared layer as in #557

### ISSUE THREAD

**Issue by biycyr** [dmlc/mxnet#6424]
@tqchen I have tried to create shared layers. I tried your answer of #557 
in mxnet/example/image-classification/symbols/mlp.py:
 `
data = mx.symbol.Variable('data')
`
`
data = mx.sym.Flatten(data=data)
`
`
fc1_weight = mx.symbol.Variable('fc1_weight',init=mx.init.Xavier())
`
`
b1_weight = mx.symbol.Variable('b1_wweight',init=mx.init.Xavier())
`
`
fc2_weight = mx.symbol.Variable('fc2_wweight',init=mx.init.Xavier())
`
`
b2_weight = mx.symbol.Variable('b2_weight',init=mx.init.Xavier())
`
`
fc3_weight = mx.symbol.Variable('fc3_weight',init=mx.init.Xavier())
`
`
b3_weight = mx.symbol.Variable('b3_weight',init=mx.init.Xavier())
`
`
fc1 = mx.symbol.FullyConnected(data = data, weight=fc1_weight,bias=b1_weight,name='fc1', num_hidden=128)
`
`
act1 = mx.symbol.Activation(data = fc1, name='relu1', act_type="relu")
`
`
fc2 = mx.symbol.FullyConnected(data = act1, weight=fc2_weight,bias=b2_weight,name = 'fc2', num_hidden = 64)
`
`
act2 = mx.symbol.Activation(data = fc2, name='relu2', act_type="relu")
`
`
fc3 = mx.symbol.FullyConnected(data = act2, weight=fc3_weight,bias=b3_weight,name='fc3', num_hidden=num_classes)
`
`
mlp = mx.symbol.SoftmaxOutput(data = fc3, name = 'softmax')
`

but I get

Traceback (most recent call last):
  File "mxnet/example/image-classification/train_mnist.py", line 76, in <module>
    fit.fit(args, sym, get_mnist_iter)
  File "/home/ycliu/mxnet-ssd/mxnet/example/image-classification/common/fit.py", line 187, in fit
    monitor            = monitor)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/base_module.py", line 448, in fit
    allow_missing=allow_missing, force_init=force_init)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/module.py", line 273, in init_params
    _impl(desc, arr, arg_params)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/module/module.py", line 268, in _impl
    initializer(name, arr)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/initializer.py", line 79, in __call__
    _INITIALIZER_REGISTRY[klass.lower()](**kwargs)._init_weight(desc, arr)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.9.5-py2.7.egg/mxnet/initializer.py", line 371, in _init_weight
    fan_in, fan_out = shape[1] * hw_scale, shape[0] * hw_scale
IndexError: tuple index out of range

Do I need to assign the shape of weights first?

**Comment by piiswrong** [comment]
b3_weight = mx.symbol.Variable('b3_weight',init=mx.init.Xavier())

This is bias, not weight, you can't init bias with Xavier. It needs to be zero or one

**Comment by biycyr** [comment]
It works! thanks for quick reply!
