### ISSUE TITLE
BatchNorm and Dropout error

### ISSUE THREAD

**Issue by ashwin-cognitiv** [dmlc/mxnet#6490]
## Environment info
Operating System: macOS

Package used (Python/R/Scala/Julia): Python 

MXNet version: 0.9.5

Python version and distribution: Python 3.6

## Error Message:
When I pass in the symbol into the Batch norm and Dropout functions without explicitly saying data =, I get this error. If I explicitly say data =, I get a data argument not recognized error.
Error: 
`Traceback (most recent call last):
  File "test.py", line 51, in <module>
    path + "test1.csv", path + "test2.csv")
  File ".../mxnetengine.py", line 65, in fit
    net = mx.symbol.BatchNorm(net)
  File "/usr/local/lib/python3.6/site-packages/mxnet/_ctypes/symbol.py", line 191, in creator
    s._compose(*args, name=name, **symbol_kwargs)
  File "/usr/local/lib/python3.6/site-packages/mxnet/symbol.py", line 298, in _compose
    raise TypeError('Compose expect `Symbol` as arguments')
TypeError: Compose expect Symbol as arguments`

## Minimum reproducible example
_Note: I have an object known as model_version that has a list of hidden layer objects (hidden_layers) of my own class, which just record the number of neurons and their layer number._ 

```Python
net = mx.sym.Variable('data')
label = mx.sym.Variable('label')
for hidden_layer in model_version.model.hidden_layers:
     if hidden_layer.has_batch_normalization:
          net = mx.symbol.BatchNorm(net)
     if hidden_layer.dropout_percent != 0:
          net = mx.symbol.Dropout(net, p = hidden_layer.dropout_percent)
    net = mx.sym.FullyConnected(net, name='h' + str(hidden_layer.layer_number), 
                                                       num_hidden=hidden_layer.neurons)
    net = property(self._get_activation(net, hidden_layer))
```

Thank you!

**Comment by ashwin-cognitiv** [comment]
@piiswrong Any idea what I'm doing wrong? I don't understand where the error is coming from, because the for loop runs for the amount of hidden layers that I have.
