### ISSUE TITLE
lstm warp-ctc ocr example failed when run with multiple gpus in data parallel mode

### ISSUE THREAD

**Issue by qclu** [dmlc/mxnet#6587]
I try ocr recognition example, now it can work well in single gpu mode.
But when I tried it with multiple gpus, it failed when check accuracy.
`contexts = [mx.context.gpu(2), mx.context.gpu(3)]                        `
Above, I select gpu 2 and 3, error will occure.
`/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py:526: DeprecationWarning: Calling initializer with init(str, NDArray) has been deprecated.please use init(mx.init.InitDesc(...), NDArray) instead.
  self.initializer(k, v)
OCR-ALP-DIGITS  2017-06-06 10:25:09,627 Start training with [gpu(2), gpu(3)]
iter
Traceback (most recent call last):
  File "lstm_ocr_alp-dig.py", line 226, in <module>
    epoch_end_callback = mx.callback.do_checkpoint(prefix, 1))
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py", line 826, in fit
    sym_gen=self.sym_gen)
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/model.py", line 260, in _train_multi_device
    executor_manager.update_metric(eval_metric, data_batch.label)
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/executor_manager.py", line 424, in update_metric
    self.curr_execgrp.update_metric(metric, labels)
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/executor_manager.py", line 276, in update_metric
    metric.update(labels_slice, texec.outputs)
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/metric.py", line 717, in update
    reval = self._feval(label, pred)
  File "/usr/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/metric.py", line 756, in feval
    return numpy_feval(label, pred)
  File "lstm_ocr_alp-dig.py", line 174, in Accuracy_LCS
    p.append(np.argmax(pred[k * BATCH_SIZE + i]))
IndexError: index 1280 is out of bounds for axis 0 with size 1280`

But if I just use one gpu, it will work.

**Comment by qclu** [comment]
Error occured when compute accuracy.

**Comment by changss** [comment]
same problem，could you tell me how to fix it?

**Comment by qclu** [comment]
@changss 
You should change batch size binding to each gpu.
