### ISSUE TITLE
Custom operator always pop up error about num of arguments.

### ISSUE THREAD

**Issue by Zehaos** [dmlc/mxnet#6739]
I'm trying to write my own custom operator, when I exec it, it always pop up error about num of arguments.
I check my args setting and it seems all right. What' going wrong here?
### Error Message
```
Traceback (most recent call last):
  File "_ctypes/callbacks.c", line 315, in 'calling callback function'
  File "/home/shizehao/anaconda2/envs/mx/lib/python2.7/site-packages/mxnet-0.9.5-py2.7.egg/mxnet/operator.py", line 608, in creator
    op_prop = prop_cls(**kwargs)
TypeError: __init__() takes exactly 2 arguments (1 given)
bash: line 1:  7595 Segmentation fault      
```

### Exec Code
```
conv_C4_dr_clip = mx.symbol.Custom(
                             top_down_feature=conv_P5_up, 
                             op_type='clip_feature', 
                             name="stage3_clip",
                             bottom_up_feature=conv_C4_dr)
```
### Custom Op
```
"""
Clip feature map
"""

import mxnet as mx
import numpy as np

DEBUG = True

class ClipFeatureOperator(mx.operator.CustomOp):
    def __init__(self, bottom_up_feature):
        super(ClipFeatureOperator, self).__init__()
        self._bottom_up_shape = np.shape(bottom_up_feature.asnumpy()[2:])
        if DEBUG:
            print 'bottom_up_shape: {}'.format(self._bottom_up_shape)

    def forward(self, is_train, req, in_data, out_data, aux):
        top_down = in_data[0]
        top_down = top_down.asnumpy()
        self._top_down_shape = np.shape(top_down)[2:]
        if DEBUG:
            print 'top_down_shape: {}'.format( self._top_down_shape)

        self._dy = self._top_down_shape[0] - self._bottom_up_shape[0]
        self._dx = self._top_down_shape[1] - self._bottom_up_shape[1]

        # if shape are equaled, do nothing
        if (self._dy==0) and (self._dx==0):
            self.assign(out_data[0], req[0], in_data[0])
        else: # clip top_down_feature
            clipped_feature = top_down[:, :, 0:(-self._dy), 0:(-self._dx)]
            self.assign(out_data[0], req[0], clipped_feature)


    def backward(self, req, out_grad, in_data, out_data, in_grad, aux):
        o_grad = out_grad[0].asnumpy()
        # if no clip, do nothing
        if (self._dy==0) and (self._dx==0):
            self.assign(in_grad[0], req[0], o_grad)
        else: # pad grad with zeros
            pad_o_grad = np.pad(o_grad, ((0, 0), (0, 0), (0, self._dy), (0, self._dx)), 'constant', constant_values=0)
            self.assign(in_grad[0], req[0], pad_o_grad)


@mx.operator.register("clip_feature")
class ClipFeatureProp(mx.operator.CustomOpProp):
    def __init__(self, bottom_up_feature):
        super(ClipFeatureProp, self).__init__(need_top_grad=False)
        self._bottom_up_feature = bottom_up_feature

    def list_arguments(self):
        return ['top_down_feature']

    def list_outputs(self):
        return ['clipped_feature']

    def infer_shape(self, in_shape):
        top_down_shape = in_shape[0]
        clipped_feature_shape = np.shape(self._bottom_up_feature)
        return [top_down_shape], [clipped_feature_shape]

    def create_operator(self, ctx, shapes, dtypes):
        return ClipFeatureOperator(bottom_up_feature=self._bottom_up_feature)

    def declare_backward_dependency(self, out_grad, in_data, out_data):
        return []

```

**Comment by Zehaos** [comment]
The 2nd symbol argument cause this error.
