### ISSUE TITLE
GPU memory issue

### ISSUE THREAD

**Issue by Strateus** [dmlc/mxnet#675]
Im not sure if its a bug or not, i loaded a model from caffe zoo (pre-converted to mxnet format):
```
>>> import mxnet as mx
>>> import time
>>> model = mx.model.FeedForward.load('/root/models/mxnet_vgg_face', 1, numpy_batch_size=2, ctx=[mx.gpu(0)]) 
```
made iterator of 11 images, batch size = 2
```
dataiter = mx.io.ImageRecordIter(path_imgrec="/root/test_images/output.bin", data_shape=(3,224,224), path_imglist="/root/test_images/list.txt", batch_size = 2)
```
before start checked my GPU memory, im not sure whats MiB but its almost empty and my card should have 1Gb:
```
root@gpu:~/mxnet# nvidia-smi
Sun Nov 22 00:03:16 2015       
+------------------------------------------------------+                       
| NVIDIA-SMI 352.39     Driver Version: 352.39         |                       
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 650     Off  | 0000:01:00.0     N/A |                  N/A |
| 40%   36C    P8    N/A /  N/A |     53MiB /  2046MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
```
Then CUDA said im out of memory:
```
>>> t1=time.time(); res = model.predict(dataiter); print 'Timing (per image): %sms' % str(((time.time()-t1)*1000))
[00:08:10] ./dmlc-core/include/dmlc/logging.h:208: [00:08:10] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
[00:08:10] ./dmlc-core/include/dmlc/logging.h:208: [00:08:10] src/engine/./threaded_engine.h:295: [00:08:10] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
terminate called after throwing an instance of 'dmlc::Error'
  what():  [00:08:10] src/engine/./threaded_engine.h:295: [00:08:10] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
Aborted (core dumped)
```

If i load with batch_size = 1, then everything goes correct:
```
>>> model = mx.model.FeedForward.load('/root/models/mxnet_vgg_face', 1, numpy_batch_size=1, ctx=[mx.gpu(0)])  
>>> dataiter = mx.io.ImageRecordIter(path_imgrec="/root/test_images/output.bin", data_shape=(3,224,224), path_imglist="/root/test_images/list.txt", batch_size = 1)
[00:08:43] src/io/iter_image_recordio.cc:67: Loaded ImageList from /root/test_images/list.txt 11 Image records
[00:08:43] src/io/iter_image_recordio.cc:212: ImageRecordIOParser: /root/test_images/output.bin, use 3 threads for decoding..
>>> t1=time.time(); res = model.predict(dataiter); print 'Timing (per image): %sms' % str(((time.time()-t1)*1000))
Timing (per image): 2753.91817093ms
>>> 
```
And my GPU memory at half it seems:
```
root@gpu:~/mxnet# watch nvidia-smi
Every 2,0s: nvidia-smi                                                                                                                                                                                              Sun Nov 22 00:13:50 2015

Sun Nov 22 00:13:50 2015
+------------------------------------------------------+
| NVIDIA-SMI 352.39     Driver Version: 352.39         |
|-------------------------------+----------------------+----------------------+
| GPU  Name        Persistence-M| Bus-Id        Disp.A | Volatile Uncorr. ECC |
| Fan  Temp  Perf  Pwr:Usage/Cap|         Memory-Usage | GPU-Util  Compute M. |
|===============================+======================+======================|
|   0  GeForce GTX 650     Off  | 0000:01:00.0     N/A |                  N/A |
| 40%   37C    P8    N/A /  N/A |    801MiB /  2046MiB |     N/A      Default |
+-------------------------------+----------------------+----------------------+
```
My output.bin is 87Kb:
```
-rw-r--r--  1 root root 87368 ________. 21 19:37 output.bin
```

So what is wrong with batch size = 2? Is it loading twice the model if i double the batch size? Or there is an issue with total files of 11, which gives 5.5 if i divide 11 on 2?

Sorry if a dupe, i wasnt able to find an asnwer on such case.

**Comment by mli** [comment]
i guess it's due to the bug we found last week, there is a strange memory allocation/deallocation (or the model) during the start. since vgg model is pretty large, so mxnet reaches the gpu memory limit on that moment.

**Comment by tqchen** [comment]
Could due to nonlinear memory request of CuDNN, but we are not yet sure about this in the moment.

**Comment by antinucleon** [comment]
You can try this to see whether it works. Add explicit parameter
```workspace``` in each convolution layer. Default value is 512MB and it
may be too large for ancient cards. Try to set 64MB in each convolution
layer, for example:
```conv2 = mx.sym.Convolution(data=conv1, kernel=(3,3), pad=(1,1),
workspace=64, num_filter=128)```

On Sat, Nov 21, 2015 at 3:02 PM, Tianqi Chen <notifications@github.com>
wrote:

> Could due to nonlinear memory request of CuDNN, but we are not yet sure
> about this in the moment.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dmlc/mxnet/issues/675#issuecomment-158685213>.
>

**Comment by Strateus** [comment]
Is it possible to do after you loaded a model?
model.symbol seems doesn't allow to change workspace

**Comment by antinucleon** [comment]
One simple hack is change the symbol.json directly and add this parameter to the json file.

**Comment by Strateus** [comment]
Just tried. If i set 64 to workspaces of all layers, Exception raised:
```
mxnet.base.MXNetError: value 64for Parameter workspace exceed bound [128,4096)
```
If i set 128 in all layers - core dumped.
If i set 128 in all layers with num_filters == 128, and workspace == num_filters on the rest - still dumps on out of memory. Memory load seems to be the same: up to 800MiB.

**Comment by dongb5** [comment]
I was also got by this GPU memory problem with vgg network.

**Comment by piiswrong** [comment]
I think there is either a bug with memory allocation or calculation of required memory. I suspect the later.
A simple way to check would be to comment out the memory requirement checking code and see if it goes out of memory.

**Comment by Strateus** [comment]
Where i can find this code to comment out?

**Comment by amirkhango** [comment]
I got the problem when i run neural-stytle's  run.py file. 
:./dmlc-core/include/dmlc/logging.h:208: [19:17:17] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory
I don't know if they're the same

**Comment by tqchen** [comment]
There is a recent update to control the workspace size for cuDNN. Please try the newest version, which fixed the probem

**Comment by ThakurRajAnand** [comment]
@tqchen I tried what you suggested and even tried with cuDNN and I am still getting this error

what():  [19:45:57] src/engine/./threaded_engine.h:295: [19:45:57] ./mshadow/mshadow/./tensor_gpu-inl.h:44: Check failed: e == cudaSuccess CUDA: out of memory


NOTE - I installed mxnet today from github

**Comment by hwu84** [comment]
I think I have similar issue using R. I have a AWS g2.8xlarge instance and just installed mxnet. When I run the Lenet from tutorial with new dataset, in this case c(112,112,3,100), it has the following error:
<img width="965" alt="screenshot 2016-02-16 23 36 56" src="https://cloud.githubusercontent.com/assets/13645961/13100808/80733384-d506-11e5-944b-b3bdc09d2171.png">

I already change the workspace = 64 for each convolution layer. If I use default workspace = 128, core dumped after finish 1 round.  By the way, I can run the tutorial code for MNIST.
I don't think it is because the size of input file since I only used a very small set. Any idea ? Thanks in advance.

**Comment by amellnik** [comment]
I'm also seeing the same thing with MXNet.jl and on the LeNet example, even with the batch size turned all the way down.  (The 3-layer MLP example works fine, but cifar also won't run on a gpu).  Starting the training quickly uses up all the GPU memory.  If there's any more information I can provide to help on this please let me know.

![image](https://cloud.githubusercontent.com/assets/7132414/13617811/6d304aca-e535-11e5-94e6-b0faef8ad1ed.png)

**Comment by lbr0307** [comment]
I am having the same issue in running /mxnet/example/neural-style 
```
python nstyle.py 
```

I got _cudaMalloc failed: out of memory_. Here is my stack trace:

```
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
MODEL!!! vgg19
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:03] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:05] src/operator/./cudnn_convolution-inl.h:55: Running performance tests to find the best convolution algorithm, this can take a while... (setting env variable MXNET_CUDNN_AUTOTUNE_DEFAULT to 0 to disable)
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
Skip argument target_gram_0
Skip argument target_gram_1
Skip argument target_gram_2
Skip argument target_gram_3
Skip argument target_gram_4
Skip argument target_content
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] src/operator/tensor/./matrix_op-inl.h:158: Using target_shape will be deprecated.
[23:19:23] /usr/local/mxnet/dmlc-core/include/dmlc/./logging.h:300: [23:19:23] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010f43d948 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010fd5578a _ZN5mxnet7storage23GPUPooledStorageManager5AllocEm + 506
[bt] (2) 2   libmxnet.so                         0x000000010fd55cc6 _ZN5mxnet11StorageImpl5AllocEmNS_7ContextE + 518
[bt] (3) 3   libmxnet.so                         0x000000010fa5f150 _ZNSt3__110shared_ptrIN5mxnet7NDArray5ChunkEE11make_sharedIJmRNS1_7ContextERbRiEEES4_DpOT_ + 240
[bt] (4) 4   libmxnet.so                         0x000000010fa5efb0 _ZN5mxnet7NDArrayC2ERKN4nnvm6TShapeENS_7ContextEbi + 480
[bt] (5) 5   libmxnet.so                         0x000000010faad435 _ZN5mxnet4exec13GraphExecutor19InitDataEntryMemoryERKNSt3__16vectorINS_7NDArrayENS2_9allocatorIS4_EEEE + 4581
[bt] (6) 6   libmxnet.so                         0x000000010faa9993 _ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEES4_NS7_4lessISE_EENSC_INS7_4pairIKSE_S4_EEEEEERKNS7_6vectorINS_7NDArrayENSC_ISP_EEEEST_RKNSO_INS_9OpReqTypeENSC_ISU_EEEEST_PNS_8ExecutorE + 1123
[bt] (7) 7   libmxnet.so                         0x000000010fab06de _ZN5mxnet8Executor4BindEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEES3_NS6_4lessISD_EENSB_INS6_4pairIKSD_S3_EEEEEERKNS6_6vectorINS_7NDArrayENSB_ISO_EEEESS_RKNSN_INS_9OpReqTypeENSB_IST_EEEESS_PS0_ + 270
[bt] (8) 8   libmxnet.so                         0x000000010fa61018 MXExecutorBindEX + 2376
[bt] (9) 9   _ctypes.so                          0x000000010537f7d7 ffi_call_unix64 + 79

Traceback (most recent call last):
  File "nstyle.py", line 260, in <module>
    train_nstyle(args)
  File "nstyle.py", line 184, in train_nstyle
    style_loss, content_loss, size, dev)
  File "/usr/local/mxnet/example/neural-style/model_vgg19.py", line 65, in get_executor
    executor = out.bind(ctx=ctx, args=arg_dict, args_grad=grad_dict, grad_req="write")
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/symbol.py", line 935, in bind
    ctypes.byref(handle)))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.9.4-py2.7.egg/mxnet/base.py", line 77, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:19:23] src/storage/./pooled_storage_manager.h:80: cudaMalloc failed: out of memory

Stack trace returned 10 entries:
[bt] (0) 0   libmxnet.so                         0x000000010f43d948 _ZN4dmlc15LogMessageFatalD2Ev + 40
[bt] (1) 1   libmxnet.so                         0x000000010fd5578a _ZN5mxnet7storage23GPUPooledStorageManager5AllocEm + 506
[bt] (2) 2   libmxnet.so                         0x000000010fd55cc6 _ZN5mxnet11StorageImpl5AllocEmNS_7ContextE + 518
[bt] (3) 3   libmxnet.so                         0x000000010fa5f150 _ZNSt3__110shared_ptrIN5mxnet7NDArray5ChunkEE11make_sharedIJmRNS1_7ContextERbRiEEES4_DpOT_ + 240
[bt] (4) 4   libmxnet.so                         0x000000010fa5efb0 _ZN5mxnet7NDArrayC2ERKN4nnvm6TShapeENS_7ContextEbi + 480
[bt] (5) 5   libmxnet.so                         0x000000010faad435 _ZN5mxnet4exec13GraphExecutor19InitDataEntryMemoryERKNSt3__16vectorINS_7NDArrayENS2_9allocatorIS4_EEEE + 4581
[bt] (6) 6   libmxnet.so                         0x000000010faa9993 _ZN5mxnet4exec13GraphExecutor4InitEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS7_12basic_stringIcNS7_11char_traitsIcEENS7_9allocatorIcEEEES4_NS7_4lessISE_EENSC_INS7_4pairIKSE_S4_EEEEEERKNS7_6vectorINS_7NDArrayENSC_ISP_EEEEST_RKNSO_INS_9OpReqTypeENSC_ISU_EEEEST_PNS_8ExecutorE + 1123
[bt] (7) 7   libmxnet.so                         0x000000010fab06de _ZN5mxnet8Executor4BindEN4nnvm6SymbolERKNS_7ContextERKNSt3__13mapINS6_12basic_stringIcNS6_11char_traitsIcEENS6_9allocatorIcEEEES3_NS6_4lessISD_EENSB_INS6_4pairIKSD_S3_EEEEEERKNS6_6vectorINS_7NDArrayENSB_ISO_EEEESS_RKNSN_INS_9OpReqTypeENSB_IST_EEEESS_PS0_ + 270
[bt] (8) 8   libmxnet.so                         0x000000010fa61018 MXExecutorBindEX + 2376
[bt] (9) 9   _ctypes.so                          0x000000010537f7d7 ffi_call_unix64 + 79
```
My system is MacOS 10.12.4 Beta and my Graphics is NVIDIA GeForce GT 750M 2048 MB.

**Comment by YokkaBear** [comment]
I also have the same problem:  
`mxnet.base.MXNetError: [11:18:15] src/storage/./pooled_storage_manager.h:157: cudaMalloc failed: out of memory
Stack trace:
  [bt] (0) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x49640b) [0x7fcd6d02340b]
  [bt] (1) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2e5cc5b) [0x7fcd6f9e9c5b]
  [bt] (2) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x2e6286f) [0x7fcd6f9ef86f]
  [bt] (3) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(mxnet::NDArray::CheckAndAlloc() const+0x1cc) [0x7fcd6d09b9ec]
  [bt] (4) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x25caf98) [0x7fcd6f157f98]
  [bt] (5) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x25cb357) [0x7fcd6f158357]
  [bt] (6) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x25d127a) [0x7fcd6f15e27a]
  [bt] (7) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x25b18e1) [0x7fcd6f13e8e1]
  [bt] (8) /data/wangyoujia/anaconda2/envs/my_env37/lib/python3.6/site-packages/mxnet/libmxnet.so(+0x25b4dc0) [0x7fcd6f141dc0]`
Could anyone have found any way to solve this? thx a lot.
