### ISSUE TITLE
'NoneType' object has no attribute 'data'

### ISSUE THREAD

**Issue by universewill** [dmlc/mxnet#6810]
I am using mxnet to do transfer learning with python code, and encounters error. I checked the data batch generated by my dataiter, it seems to be ok. Here is the error:  

---
Traceback (most recent call last):
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 104, in <module>
    test_train()
  File "/Users/nali/PycharmProjects/mxnet-ir/test.py", line 100, in test_train
    epoch_end_callback=mx.callback.do_checkpoint("models/ir-blur"))
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 826, in fit
    sym_gen=self.sym_gen)
  File "/Library/Python/2.7/site-packages/mxnet/model.py", line 237, in _train_multi_device
    executor_manager.load_data_batch(data_batch)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 412, in load_data_batch
    self.curr_execgrp.load_data_batch(data_batch)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 259, in load_data_batch
    _load_data(data_batch, self.data_arrays)
  File "/Library/Python/2.7/site-packages/mxnet/executor_manager.py", line 95, in _load_data
    _load_general(batch.data, targets)
AttributeError: 'NoneType' object has no attribute 'data'
  
---
Here is the code:

    optimizer = mx.optimizer.SGD(momentum=0.99)  # lr_scheduler=lr_scheduler)
    model = mx.model.FeedForward(
        allow_extra_params=True,
        ctx=dev,
        symbol=network,
        num_epoch=200,
        learning_rate=0.1*1e-2,
        wd=0.0001,
        initializer=mx.init.Load("./ResNet/resnet-18-0000.params", default_init=mx.init.Xavier(rnd_type="gaussian", factor_type="in", magnitude=2)),
        optimizer=optimizer)
    model.fit(X=train_set,
              eval_metric=Auc(),
              kvstore='local_allreduce_device',
              batch_end_callback=mx.callback.Speedometer(batch_size, 10),
              epoch_end_callback=mx.callback.do_checkpoint("models/ir-blur"))

**Comment by universewill** [comment]
I debug the code and find that the error occurs when i run iter on my train data.
Here is the simplified code:

train_set = DataIter(...)
for batch in train_set:
       print len(batch)

An error will tell me the batch is a 'NoneType' object and has no len().
My DataIter is customerized following the link: http://mxnet.io/tutorials/basic/data.html

I don't know why this happens.

**Comment by universewill** [comment]
The next() function in my data iter is wrong.
