### ISSUE TITLE
Training Faster R-CNN on own dataset

### ISSUE THREAD

**Issue by maxrichter-scdm** [dmlc/mxnet#6915]
Hi,

I cloned the R-CNN repository _https://github.com/dmlc/mxnet/tree/master/example/rcnn_ and successfully trained it on the VOC2007 dataset.

I created my own dataset and adapted the `pascal_voc.py` file. 
This included changing the number of classes to 13. 
The resolution of my pictures is 600*800 pixel, so a bit larger than the VOC dataset.

In my trainval images, I have 2000 examples, so 3000 less than than in VOC. 
I am using mxnet 0.10 in python for this.

I trained on the data for 10 epochs, losses are continously going down, but I was getting no results testing the model.

Did someone had a similar experience or knows what I am missing?

**Comment by muchuanyun** [comment]
What do you mean by "getting no results testing the model"?

If you use "test.py", it should be fed with network, end_epoch and model prefix. The expected output should be AP for each category and mAP. If you use "demo.py", the code should be adapted a little, as it works only for VGG now.

Could you provide more details? @maxrichter-scdm

**Comment by szha** [comment]
@apache/mxnet-committers: This issue has been inactive for the past 90 days. It has no label and needs triage.

For general "how-to" questions, our [user forum](https://discuss.mxnet.io/) (and [Chinese version](https://discuss.gluon.ai/)) is a good place to get help.

**Comment by Ram124** [comment]
@muchuanyun  @maxrichter-scdm 

when i run demo.py. I am getting something like this.
What is this??

(mxnet_p27) ubuntu@ip-172-31-10-202:~/mx-rcnn-1$ python demo.py --prefix model/vgg16 --epoch 0 --image myimage.jpg --gpu 0 --vis
Traceback (most recent call last):
File "demo.py", line 143, in 
main()
File "demo.py", line 138, in main
predictor = get_net(symbol, args.prefix, args.epoch, ctx)
File "demo.py", line 49, in get_net
assert k in arg_params, k + ' not initialized'
AssertionError: rpn_conv_3x3_weight not initialized

Any help is really appreciated

**Comment by scindew** [comment]
I have the exact error. Did you solve it?
