### ISSUE TITLE
Errors about multi machine training(Distribution training)

### ISSUE THREAD

**Issue by meanmee** [dmlc/mxnet#7088]
## Environment info
Operating System:Ubuntu 14.04

Compiler:g++ 4.8

Package used (Python/R/Scala/Julia):Python

MXNet version:

Or if installed from source: from source

MXNet commit hash (`git rev-parse HEAD`): 70a781b62a0dcaf782cf5cf96394b1e87091ed5f

If you are using python package, please provide

Python version and distribution: 2.7 anaconda2

If you are using R package, please provide

R `sessionInfo()`:

## Error Message:

I am sure i input the correct password but return the Permission denied info anyway. also the both machines are sshable.(the user wuxiaomin are not the admin in both machines).

2017-07-19 12:00:32,848 INFO rsync /home/wuxiaomin/software/mxnet/example/image-classification/ -> xxx.xxx.xxx.xxx:/tmp/mxnet
/bin/sh: 1: launcher: not found
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wuxiaomin/software/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/tracker.py", line 363, in <lambda>
    target=(lambda: subprocess.check_call(self.cmd, env=env, shell=True)), args=())
  File "/home/wuxiaomin/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'launcher ssh' returned non-zero exit status 127

wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
wuxiaomin@amax:~/software/mxnet/example/image-classification$ wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied (publickey,password).
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied (publickey,password).
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied, please try again.
wuxiaomin@xxx.xxx.xxx.xxx's password: 
Permission denied (publickey,password).

## Minimum reproducible example

python ../../tools/launch.py -s 2 -n 2 -H hosts --sync-dst-dir /tmp/mxnet -- launcher ssh

**Comment by meanmee** [comment]
Seems like the port is wrong?

**Comment by meanmee** [comment]
The ssh problems sovled but new error raised:

2017-07-19 17:59:40,763 INFO rsync /home/wuxiaomin/software/mxnet/example/image-classification/ -> 10.29.150.107:/tmp/mxnet
[17:59:41] src/van.cc:75: Bind to role=scheduler, id=1, ip=10.29.150.106, port=9108, is_recovery=0
Traceback (most recent call last):
  File "train_mnist.py", line 8, in <module>
    from common import find_mxnet, fit
  File "/tmp/mxnet/common/find_mxnet.py", line 3, in <module>
    import mxnet as mx
  File "/tmp/mxnet/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/tmp/mxnet/mxnet/base.py", line 69, in <module>
    _LIB = _load_lib()
  File "/tmp/mxnet/mxnet/base.py", line 61, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/mxnet/mxnet/libmxnet.so: undefined symbol: cblas_dtrsm
Traceback (most recent call last):
  File "train_mnist.py", line 8, in <module>
    from common import find_mxnet, fit
  File "/tmp/mxnet/common/find_mxnet.py", line 3, in <module>
    import mxnet as mx
  File "/tmp/mxnet/mxnet/__init__.py", line 7, in <module>
    from .base import MXNetError
  File "/tmp/mxnet/mxnet/base.py", line 69, in <module>
    _LIB = _load_lib()
  File "/tmp/mxnet/mxnet/base.py", line 61, in _load_lib
    lib = ctypes.CDLL(lib_path[0], ctypes.RTLD_LOCAL)
  File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
    self._handle = _dlopen(self._name, mode)
OSError: /tmp/mxnet/mxnet/libmxnet.so: undefined symbol: cblas_dtrsm
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wuxiaomin/software/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/home/wuxiaomin/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.29.150.107 -p 22 'export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9108; export DMLC_PS_ROOT_URI=10.29.150.106; export DMLC_NUM_SERVER=1; export DMLC_NUM_WORKER=1; cd /tmp/mxnet; python train_mnist.py --network lenet --kv-store dist_sync --gpus 0'' returned non-zero exit status 1

Exception in thread Thread-2:
Traceback (most recent call last):
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/home/wuxiaomin/anaconda2/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/home/wuxiaomin/software/mxnet/tools/../dmlc-core/tracker/dmlc_tracker/ssh.py", line 60, in run
    subprocess.check_call(prog, shell = True)
  File "/home/wuxiaomin/anaconda2/lib/python2.7/subprocess.py", line 186, in check_call
    raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.29.150.107 -p 22 'export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9108; export DMLC_PS_ROOT_URI=10.29.150.106; export DMLC_NUM_SERVER=1; export DMLC_NUM_WORKER=1; cd /tmp/mxnet; python train_mnist.py --network lenet --kv-store dist_sync --gpus 0'' returned non-zero exit status 1

**Comment by meanmee** [comment]
proble solved

**Comment by coderzbx** [comment]
@meanmee how to resolve this problem?Thank you~
