### ISSUE TITLE
[example] train_model.py AttributeError: 'Namespace' object has no attribute 'clip_gradient'

### ISSUE THREAD

**Issue by qiaohaijun** [dmlc/mxnet#723]
# ../../tools/launch.py -n 2 python train_mnist.py
2015-11-26 10:03:21,152 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
2015-11-26 10:03:21,153 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
[10:03:22] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[10:03:22] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[10:03:22] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
Traceback (most recent call last):
  File "train_mnist.py", line 122, in <module>
    train_model.fit(args, net, get_iterator)
  File "/search/data/user/qhj/github/mxnet/example/image-classification/train_model.py", line 51, in fit
    clip_gradient      = args.clip_gradient,
AttributeError: 'Namespace' object has no attribute 'clip_gradient'
[10:03:22] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
Traceback (most recent call last):
  File "train_mnist.py", line 122, in <module>
    train_model.fit(args, net, get_iterator)
  File "/search/data/user/qhj/github/mxnet/example/image-classification/train_model.py", line 51, in fit
    clip_gradient      = args.clip_gradient,
AttributeError: 'Namespace' object has no attribute 'clip_gradient'
2015-11-26 10:03:22,423 DEBUG Thread %d exit with 0

**Comment by qiaohaijun** [comment]
env:
1. g++ 4.8
2. cuda 7.0

execution:
1. git pull
2. git submodule update

**Comment by mli** [comment]
should be fixed by #724 please have a `git pull`

**Comment by qiaohaijun** [comment]
the problem has solved
