### ISSUE TITLE
Does neural-style support cpu run?

### ISSUE THREAD

**Issue by breezedeus** [dmlc/mxnet#862]
I got this error:
```
[root@localhost neural-style]# python run.py 
INFO:root:load the content image, size = (1000, 1500)
INFO:root:resize the content image to (400, 600)
[11:30:29] ./dmlc-core/include/dmlc/././logging.h:208: [11:30:29] src/storage/storage.cc:44: Please compile with CUDA enabled
Traceback (most recent call last):
  File "run.py", line 115, in <module>
    model_executor = importlib.import_module('model_' + args.model).get_model(size, dev)
  File "/root/softwares/mxnet/example/neural-style/model_vgg19.py", line 50, in get_model
    arg_dict = dict(zip(arg_names, [mx.nd.zeros(shape, ctx=ctx) for shape in arg_shapes]))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 428, in zeros
    arr = empty(shape, ctx)
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 411, in empty
    return NDArray(handle=_new_alloc_handle(shape, ctx, False))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 45, in _new_alloc_handle
    ctypes.byref(hdl)))
  File "/usr/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 74, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [11:30:29] src/storage/storage.cc:44: Please compile with CUDA enabled

```

**Comment by piiswrong** [comment]
yes, run python run.py and look at the options
