### ISSUE TITLE
How to train a model using multiple machines?

### ISSUE THREAD

**Issue by wsybupt** [dmlc/mxnet#922]
According to this https://github.com/dmlc/mxnet/tree/master/example/image-classification
I have 2 ssh-able machines and I have mount "10.108.165.17:/mxnet " to "10.108.165.123:/mxnet". But when I do distributed training on 10.108.165.17, I get the error messages:
```
wsy@wsy-ThinkCentre-XXXX:/mxnet$ tools/launch.py -n 2 -H hosts python example/image-classification/train_mnist.py --kv-store dist_sync
OpenCV is unavailable.
Traceback (most recent call last):
File "example/image-classification/train_mnist.py", line 1, in <module>
import find_mxnet
File "/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
Traceback (most recent call last):
File "example/image-classification/train_mnist.py", line 1, in <module>
Traceback (most recent call last):
File "example/image-classification/train_mnist.py", line 1, in <module>
import mxnet as mx
File "/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
from .base import MXNetError
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
_LIB = _load_lib()
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /mxnet/python/mxnet/../../lib/libmxnet.so)
import find_mxnet
File "/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
import find_mxnet
File "/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
Exception in thread Thread-4:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/mxnet/tools/../ps-lite/tracker/dmlc_ssh.py", line 60, in run
subprocess.check_call(prog, shell = True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.108.165.123 'export LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib/openmpi; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9504; export DMLC_PS_ROOT_URI=127.0.1.1; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /mxnet/; python example/image-classification/train_mnist.py --kv-store dist_sync'' returned non-zero exit status 1

import mxnet as mx
File "/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
import mxnet as mx
File "/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
from .base import MXNetError
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
from .base import MXNetError
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
Traceback (most recent call last):
File "example/image-classification/train_mnist.py", line 1, in <module>
_LIB = _load_lib()
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
_LIB = _load_lib()
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
import find_mxnet
File "/mxnet/example/image-classification/find_mxnet.py", line 7, in <module>
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /mxnet/python/mxnet/../../lib/libmxnet.so)
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /mxnet/python/mxnet/../../lib/libmxnet.so)
import mxnet as mx
File "/mxnet/example/image-classification/../../python/mxnet/__init__.py", line 7, in <module>
Exception in thread Thread-3:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/mxnet/tools/../ps-lite/tracker/dmlc_ssh.py", line 60, in run
subprocess.check_call(prog, shell = True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.108.165.123 'export LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib/openmpi; export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9504; export DMLC_PS_ROOT_URI=127.0.1.1; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /mxnet/; python example/image-classification/train_mnist.py --kv-store dist_sync'' returned non-zero exit status 1

from .base import MXNetError
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 43, in <module>
_LIB = _load_lib()
File "/mxnet/example/image-classification/../../python/mxnet/base.py", line 35, in _load_lib
lib = ctypes.cdll.LoadLibrary(lib_path[0])
File "/usr/lib/python2.7/ctypes/__init__.py", line 443, in LoadLibrary
return self._dlltype(name)
File "/usr/lib/python2.7/ctypes/__init__.py", line 365, in __init__
self._handle = _dlopen(self._name, mode)
OSError: /usr/lib/x86_64-linux-gnu/libgomp.so.1: version `GOMP_4.0' not found (required by /mxnet/python/mxnet/../../lib/libmxnet.so)
Exception in thread Thread-2:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/mxnet/tools/../ps-lite/tracker/dmlc_ssh.py", line 60, in run
subprocess.check_call(prog, shell = True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.108.165.123 'export LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib/openmpi; export DMLC_ROLE=server; export DMLC_PS_ROOT_PORT=9504; export DMLC_PS_ROOT_URI=127.0.1.1; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /mxnet/; python example/image-classification/train_mnist.py --kv-store dist_sync'' returned non-zero exit status 1
Exception in thread Thread-5:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 810, in __bootstrap_inner
self.run()
File "/usr/lib/python2.7/threading.py", line 763, in run
self.__target(*self.__args, **self.__kwargs)
File "/mxnet/tools/../ps-lite/tracker/dmlc_ssh.py", line 60, in run
subprocess.check_call(prog, shell = True)
File "/usr/lib/python2.7/subprocess.py", line 540, in check_call
raise CalledProcessError(retcode, cmd)
CalledProcessError: Command 'ssh -o StrictHostKeyChecking=no 10.108.165.123 'export LD_LIBRARY_PATH=:/usr/local/lib:/usr/local/lib/openmpi; export DMLC_ROLE=worker; export DMLC_PS_ROOT_PORT=9504; export DMLC_PS_ROOT_URI=127.0.1.1; export DMLC_NUM_SERVER=2; export DMLC_NUM_WORKER=2; cd /mxnet/; python example/image-classification/train_mnist.py --kv-store dist_sync'' returned non-zero exit status 1

```

my hosts is like this:
```
$cat hosts
10.108.165.123
```

**Comment by wsybupt** [comment]
@mli

**Comment by mli** [comment]
it seems that there are two errors:

1. GOMP_4.0 is not found. you may try `ldd mxnet/lib/libmxnet.so` on both 10.108.165.17 and 10.108.165.123 to see if there is any missing library
2. launch.py mistakenly get a local ip, see `export DMLC_PS_ROOT_URI=127.0.1.1`, while the correct one should be `10.108.165.17`. the codes are there, i will try to find a solution

https://github.com/dmlc/ps-lite/blob/55ee9bdbf7e5bf1cbde423ba118041e1a7dcca1b/tracker/tracker.py#L384

**Comment by mli** [comment]
let's move to #903
