### ISSUE TITLE
Getting KVStore error for 'image-classification' examples.

### ISSUE THREAD

**Issue by jrosebr1** [dmlc/mxnet#947]
I just pulled down 0.5.0 of mxnet and installed it on my Amazon EC2 instance. However, when I try to run `train_mnist.py` and `train_cifar10.py` I get the following output:

<pre>$ python train_mnist.py
2015-12-15 23:39:23,949 Node[0] start with arguments Namespace(batch_size=128, data_dir='mnist/', gpus=None, kv_store='local', load_epoch=None, lr=0.1, lr_factor=1, lr_factor_epoch=1, model_prefix=None, network='mlp', num_epochs=10, num_examples=60000)
[23:39:25] src/io/iter_mnist.cc:91: MNISTIter: load 60000 images, shuffle=1, shape=(128,784)
[23:39:25] src/io/iter_mnist.cc:91: MNISTIter: load 10000 images, shuffle=1, shape=(128,784)
Traceback (most recent call last):
  File "train_mnist.py", line 122, in <module>
    train_model.fit(args, net, get_iterator)
  File "/home/ubuntu/mxnet/example/image-classification/train_model.py", line 69, in fit
    epoch_end_callback = checkpoint)
  File "/home/ubuntu/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 724, in fit
    kvstore, len(self.ctx), self.arg_params)
  File "/home/ubuntu/.virtualenvs/mxnet/local/lib/python2.7/site-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 145, in _create_kvstore
    raise TypeError('kvstore must be either KVStore or str')
TypeError: kvstore must be either KVStore or str</pre>

I've tried manually setting `--kv-store "local"` in the command line arguments (even though "local" is what the value defaults to). I'm sure there is something simple I'm missing, but I'm not seeing it.

**Comment by MonPower** [comment]
I met the same problem, even when I set --kv-store "local", the problem still exists, do you know other solutions? Thanks

**Comment by mli** [comment]
please reinstall the mxnet python package, since we slightly changed `model.py`

**Comment by MonPower** [comment]
@mli Thanks, it is ok now

**Comment by jrosebr1** [comment]
@mli: Confirmed, re-installing the `mxnet` Python package resolved the issue. Thanks!
