### ISSUE TITLE
Why predictions with different batch size will cause error?

### ISSUE THREAD

**Issue by hehaodele** [dmlc/mxnet#992]
The codes are as following:
```
print model.predict(np_to_mxIter(val, 500))
print model.predict(np_to_mxIter(train, 1000))
```
with the definition of ```np_to_mxIter```
```
def np_to_mxIter(data, bs):
    dataIter = mx.io.NDArrayIter(
        data = data[:, 0:470],
        label = data[:, 471:472].flatten(),
        batch_size = bs,
        shuffle = False)
    return dataIter
```
Yet I encounter the following error:
```
./dmlc-core/include/dmlc/logging.h:208: [00:24:22] src/ndarray/ndarray.cc:159: Check failed: from.shape() == to->shape() operands shape mismatch
Traceback (most recent call last):
  File "/home/hehaodele/workspace/hhnet/src/Hmain.py", line 119, in <module>
    go_train()
  File "/home/hehaodele/workspace/hhnet/src/Hmain.py", line 97, in go_train
    print model.predict(np_to_mxIter(train, 1000))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/model.py", line 561, in predict
    _load_data(batch, data_arrays)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor.py", line 297, in _load_data
    _load_general(batch.data, targets)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/executor.py", line 290, in _load_general
    d_src.copyto(d_targets)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 361, in copyto
    return NDArray._copyto(self, out=other)
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/ndarray.py", line 654, in unary_ndarray_function
    c_array(NDArrayHandle, (out.handle,))))
  File "/usr/local/lib/python2.7/dist-packages/mxnet-0.5.0-py2.7.egg/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [00:24:22] src/ndarray/ndarray.cc:159: Check failed: from.shape() == to->shape() operands shape mismatch
```
Any ideas to solve it? Thanks.

**Comment by antinucleon** [comment]
In bind symbol process, the input shape is fixed to [nbatch, channel, h, w] or [nbatch, ndim]. It you want to predict on different batch size, you need to bind again with new shape.

**Comment by Azure-Vani** [comment]
I met this issue, too. 

It should be better if there is a way to change the required batch_size temporarily since in some cases I only want to make prediction on singal data and it always doesn't meet the batch_size requirements.

**Comment by pluskid** [comment]
In the new module API, you can force re-bind with new batch size.
