### ISSUE TITLE
Error with "USE_DIST_KVSTORE = 1" when building on Amazon EC2

### ISSUE THREAD

**Issue by xgastaldi** [dmlc/mxnet#994]
Hi everyone,

I am trying to build mxnet on a g2.2xlarge to try distributed training on a GPU cluster.
I followed the instructions here http://mxnet.readthedocs.org/en/latest/aws.html and everything works until I run make -j8 which gives me the error below:

make CXX=g++ DEPS_PATH=/home/ubuntu/mxnet/deps -C ./ps-lite ps
make[1]: Entering directory `/home/ubuntu/mxnet/ps-lite'
/home/ubuntu/mxnet/deps/bin/protoc --cpp_out=./src --proto_path=./src src/meta.proto
make[1]: /home/ubuntu/mxnet/deps/bin/protoc: Command not found
make[1]: *** [src/meta.pb.h] Error 127
make[1]: Leaving directory `/home/ubuntu/mxnet/ps-lite'
make: *** [ps-lite/build/libps.a] Error 2
make: *** Waiting for unfinished jobs....

I tried turning on all the flags one by one and all of them allow me to build except "USE_DIST_KVSTORE = 1" which returns the error above. Any idea how to solve that?

**Comment by antinucleon** [comment]
You need to install protobuf compiler.

**Comment by mli** [comment]
ps-lite will build protobuf automatically. this bug seems due to someone updated ps-lite into not well tested version. i made a quick fix, please `git pull` and `git submodule update` and then build

**Comment by xgastaldi** [comment]
Thanks! I managed to make it work for a GPU cluster.
FYI, I had to change the code a bit from ../../tools/launch.py to ../mxnet/tools/launch.py

I still have some trouble running the S3 example and get the following error:

./dmlc-core/include/dmlc/logging.h:208: [23:41:36] src/symbol/symbol.cc:121: Symbol.InterShapeKeyword argument name softmax_label not found.
Candidate arguments:
        [0]data
        [1]convolution0_weight
        [2]convolution0_bias
        [3]batchnorm0_gamma
        [4]batchnorm0_beta
        [5]convolution1_weight
        [6]convolution1_bias
        [7]batchnorm1_gamma
        [8]batchnorm1_beta
        [9]fullyconnected0_weight
        [10]fullyconnected0_bias
        [11]softmaxoutput0_label

Traceback (most recent call last):
  File "tests/python/gpu/test_conv.py", line 61, in <module>
    momentum      = 0.9)
  File "/home/ubuntu/mxnet/python/mxnet/model.py", line 771, in create
    work_load_list=work_load_list)
  File "/home/ubuntu/mxnet/python/mxnet/model.py", line 623, in fit
    self._init_params(dict(data.provide_data+data.provide_label))
  File "/home/ubuntu/mxnet/python/mxnet/model.py", line 441, in _init_params
    arg_shapes, _, aux_shapes = self.symbol.infer_shape(**input_shapes)
  File "/home/ubuntu/mxnet/python/mxnet/symbol.py", line 376, in infer_shape
    ctypes.byref(complete)))
  File "/home/ubuntu/mxnet/python/mxnet/base.py", line 76, in check_call
    raise MXNetError(py_str(_LIB.MXGetLastError()))
mxnet.base.MXNetError: [23:41:36] src/symbol/symbol.cc:121: Symbol.InterShapeKeyword argument name softmax_label not found.
Candidate arguments:
        [0]data
        [1]convolution0_weight
        [2]convolution0_bias
        [3]batchnorm0_gamma
        [4]batchnorm0_beta
        [5]convolution1_weight
        [6]convolution1_bias
        [7]batchnorm1_gamma
        [8]batchnorm1_beta
        [9]fullyconnected0_weight
        [10]fullyconnected0_bias
        [11]softmaxoutput0_label

I don't think it comes from the S3 connection because I get the same error when using data_dir = '/home/ubuntu/mnist'

**Comment by tqchen** [comment]
Was due to the recent update of data iter interface, need to add name to final softmax layer.

**Comment by mli** [comment]
i suggest to use examples in https://github.com/dmlc/mxnet/tree/master/example/image-classification

the end-to-end examples under tests/ are not tested for some days,

**Comment by xgastaldi** [comment]
Ok, thanks :)

**Comment by tqchen** [comment]
You can fix the problem by adding parameter ```name``` to the final layer.
e.g.

```python
final_net = Softmax(in, name='softmax');
```

Please see if it solves your problem, and submit a PR if you fixed it :)

**Comment by xgastaldi** [comment]
It worked, thanks for your help! I submitted a new PR.
